-- Remaining Batches 3-9 (70 kayıt)
INSERT INTO prices (origin, destination, partner, transport_type, vehicle_type, price, weight, cbm, ldm, dimensions, valid_until, notes) VALUES ('DE95 Tirschenreuth', 'Rotterdam, NL', 'FAB', 'Karayolu', 'Flatbed', 1500.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 807 km'),
('DE95 Tirschenreuth', 'Rotterdam, NL', 'FAB', 'Karayolu', 'Lowbed', 1700.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 807 km'),
('DE95 Tirschenreuth', 'Zeebrügge, BE', 'Muje', 'Karayolu', 'Flatbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 845 km'),
('DE95 Tirschenreuth', 'Zeebrügge, BE', 'Muje', 'Karayolu', 'Lowbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 845 km'),
('DE95 Tirschenreuth', 'Zeebrügge, BE', 'FAB', 'Karayolu', 'Flatbed', 1600.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 845 km'),
('DE95 Tirschenreuth', 'Zeebrügge, BE', 'FAB', 'Karayolu', 'Lowbed', 1750.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 845 km'),
('DE95 Tirschenreuth', 'Antwerpen, BE', 'Muje', 'Karayolu', 'Flatbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 850 km'),
('DE95 Tirschenreuth', 'Antwerpen, BE', 'Muje', 'Karayolu', 'Lowbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 850 km'),
('DE95 Tirschenreuth', 'Antwerpen, BE', 'FAB', 'Karayolu', 'Flatbed', 1600.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 850 km'),
('DE95 Tirschenreuth', 'Antwerpen, BE', 'FAB', 'Karayolu', 'Lowbed', 1750.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 850 km');
INSERT INTO prices (origin, destination, partner, transport_type, vehicle_type, price, weight, cbm, ldm, dimensions, valid_until, notes) VALUES ('DE95 Tirschenreuth', 'Ankara, TR', 'Muje', 'Karayolu', 'Flatbed', 10500.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2503 km'),
('DE95 Tirschenreuth', 'Ankara, TR', 'Muje', 'Karayolu', 'Lowbed', 10500.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2503 km'),
('DE95 Tirschenreuth', 'Ankara, TR', 'SM', 'Karayolu', 'Flatbed', 5250.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2503 km'),
('DE95 Tirschenreuth', 'Ankara, TR', 'SM', 'Karayolu', 'Lowbed', 6250.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2503 km'),
('DE95 Tirschenreuth', 'Ankara, TR', 'FAB', 'Karayolu', 'Flatbed', 5150.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2503 km'),
('DE95 Tirschenreuth', 'Ankara, TR', 'FAB', 'Karayolu', 'Lowbed', 5500.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2503 km'),
('DE95 Tirschenreuth', 'Barcelona, ES', 'Muje', 'Karayolu', 'Flatbed', 5000.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1571 km'),
('DE95 Tirschenreuth', 'Barcelona, ES', 'Muje', 'Karayolu', 'Lowbed', 5000.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1571 km'),
('DE95 Tirschenreuth', 'Enfield*, IE', 'DFDS', 'Karayolu', 'Flatbed', 4195.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1845 km'),
('DE95 Tirschenreuth', 'Leiria*, PT', 'DFDS', 'Karayolu', 'Flatbed', 4995.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2539 km');
INSERT INTO prices (origin, destination, partner, transport_type, vehicle_type, price, weight, cbm, ldm, dimensions, valid_until, notes) VALUES ('DE95 Tirschenreuth', 'Leiria*, PT', 'Muje', 'Karayolu', 'Flatbed', 8000.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2539 km'),
('DE95 Tirschenreuth', 'Leiria*, PT', 'Muje', 'Karayolu', 'Lowbed', 8000.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2539 km'),
('DE95 Tirschenreuth', 'Newark*, GB', 'DFDS', 'Karayolu', 'Flatbed', 3695.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1339 km'),
('DE95 Tirschenreuth', 'Lissabon*, PT', 'DFDS', 'Karayolu', 'Flatbed', 5195.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2631 km'),
('DE95 Tirschenreuth', 'Lissabon*, PT', 'Muje', 'Karayolu', 'Flatbed', 8300.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2631 km'),
('DE95 Tirschenreuth', 'Lissabon*, PT', 'Muje', 'Karayolu', 'Lowbed', 8300.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2631 km'),
('DE95 Tirschenreuth', 'Maia*, PT', 'DFDS', 'Karayolu', 'Flatbed', 4750.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2474 km'),
('DE95 Tirschenreuth', 'Maia*, PT', 'Muje', 'Karayolu', 'Flatbed', 7500.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2474 km'),
('DE95 Tirschenreuth', 'Maia*, PT', 'Muje', 'Karayolu', 'Lowbed', 7500.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2474 km'),
('DE95 Tirschenreuth', 'Pinto*, ES', 'DFDS', 'Karayolu', 'Flatbed', 5540.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2184 km');
INSERT INTO prices (origin, destination, partner, transport_type, vehicle_type, price, weight, cbm, ldm, dimensions, valid_until, notes) VALUES ('DE95 Tirschenreuth', 'Pinto*, ES', 'Muje', 'Karayolu', 'Flatbed', 7100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2184 km'),
('DE95 Tirschenreuth', 'Pinto*, ES', 'Muje', 'Karayolu', 'Lowbed', 7100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2184 km'),
('DE95 Tirschenreuth', 'Puurs*, BE', 'Muje', 'Karayolu', 'Flatbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 776 km'),
('DE95 Tirschenreuth', 'Puurs*, BE', 'Muje', 'Karayolu', 'Lowbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 776 km'),
('DE95 Tirschenreuth', 'Puurs*, BE', 'FAB', 'Karayolu', 'Flatbed', 1450.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 776 km'),
('DE95 Tirschenreuth', 'Puurs*, BE', 'FAB', 'Karayolu', 'Lowbed', 1650.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 776 km'),
('DE95 Tirschenreuth', 'Steyrermühl*, AT', 'Muje', 'Karayolu', 'Flatbed', 1250.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 351 km'),
('DE95 Tirschenreuth', 'Steyrermühl*, AT', 'Muje', 'Karayolu', 'Lowbed', 1250.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 351 km'),
('DE95 Tirschenreuth', 'Tuzla, TR', 'Muje', 'Karayolu', 'Flatbed', 9300.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km'),
('DE95 Tirschenreuth', 'Tuzla, TR', 'Muje', 'Karayolu', 'Lowbed', 9300.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km');
INSERT INTO prices (origin, destination, partner, transport_type, vehicle_type, price, weight, cbm, ldm, dimensions, valid_until, notes) VALUES ('DE95 Tirschenreuth', 'Tuzla, TR', 'SM', 'Karayolu', 'Flatbed', 5000.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km'),
('DE95 Tirschenreuth', 'Tuzla, TR', 'SM', 'Karayolu', 'Lowbed', 6000.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km'),
('DE95 Tirschenreuth', 'Tuzla, TR', 'FAB', 'Karayolu', 'Flatbed', 4750.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km'),
('DE95 Tirschenreuth', 'Tuzla, TR', 'FAB', 'Karayolu', 'Lowbed', 4950.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km'),
('DE95 Tirschenreuth', 'Werkendam*, NL', 'Muje', 'Karayolu', 'Flatbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 783 km'),
('DE95 Tirschenreuth', 'Werkendam*, NL', 'Muje', 'Karayolu', 'Lowbed', 2100.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 783 km'),
('DE95 Tirschenreuth', 'Werkendam*, NL', 'FAB', 'Karayolu', 'Flatbed', 1450.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 783 km'),
('DE95 Tirschenreuth', 'Werkendam*, NL', 'FAB', 'Karayolu', 'Lowbed', 1650.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 783 km'),
('DE95 Tirschenreuth', 'Fredericia*, DK', 'Muje', 'Karayolu', 'Flatbed', 2300.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 856 km'),
('DE95 Tirschenreuth', 'Fredericia*, DK', 'Muje', 'Karayolu', 'Lowbed', 2300.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 856 km');
INSERT INTO prices (origin, destination, partner, transport_type, vehicle_type, price, weight, cbm, ldm, dimensions, valid_until, notes) VALUES ('DE95 Tirschenreuth', 'Fredericia*, DK', 'FAB', 'Karayolu', 'Flatbed', 1700.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 856 km'),
('DE95 Tirschenreuth', 'Fredericia*, DK', 'FAB', 'Karayolu', 'Lowbed', 1950.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 856 km'),
('Loading address', 'Enfield, IE', 'MT (Partner)', 'Karayolu', 'Tautliner 4 LDM', 1065.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1845 km - *gerish ile aktarmalı'),
('Loading address', 'Enfield, IE', 'MT (Partner)', 'Karayolu', 'Tautliner 8 LDM', 1775.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1845 km - *gerish ile aktarmalı'),
('Loading address', 'Enfield, IE', 'MT (Partner)', 'Karayolu', 'Tautliner FTL', 2655.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1845 km - *gerish ile aktarmalı'),
('Loading address', 'Leiria, PT', 'MT (Partner)', 'Karayolu', 'Tautliner 4 LDM', 1600.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2539 km'),
('Loading address', 'Leiria, PT', 'MT (Partner)', 'Karayolu', 'Tautliner 8 LDM', 2300.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2539 km'),
('Loading address', 'Leiria, PT', 'MT (Partner)', 'Karayolu', 'Tautliner FTL', 2750.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2539 km'),
('Loading address', 'Newark, GB', 'MT (Partner)', 'Karayolu', 'Tautliner 4 LDM', 1125.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1339 km - *gerish ile aktarmalı'),
('Loading address', 'Newark, GB', 'MT (Partner)', 'Karayolu', 'Tautliner 8 LDM', 1855.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1339 km - *gerish ile aktarmalı');
INSERT INTO prices (origin, destination, partner, transport_type, vehicle_type, price, weight, cbm, ldm, dimensions, valid_until, notes) VALUES ('Loading address', 'Newark, GB', 'MT (Partner)', 'Karayolu', 'Tautliner FTL', 2825.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 1339 km - *gerish ile aktarmalı'),
('Loading address', 'Lissabon, PT', 'MT (Partner)', 'Karayolu', 'Tautliner 4 LDM', 1700.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2631 km'),
('Loading address', 'Lissabon, PT', 'MT (Partner)', 'Karayolu', 'Tautliner 8 LDM', 2400.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2631 km'),
('Loading address', 'Lissabon, PT', 'MT (Partner)', 'Karayolu', 'Tautliner FTL', 2970.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2631 km'),
('Loading address', 'Maia, PT', 'MT (Partner)', 'Karayolu', 'Tautliner 4 LDM', 1550.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2474 km'),
('Loading address', 'Maia, PT', 'MT (Partner)', 'Karayolu', 'Tautliner 8 LDM', 2250.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2474 km'),
('Loading address', 'Maia, PT', 'MT (Partner)', 'Karayolu', 'Tautliner FTL', 2725.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2474 km'),
('Loading address', 'Tuzla, TR', 'MT (Partner)', 'Karayolu', 'Tautliner 4 LDM', 1200.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km'),
('Loading address', 'Tuzla, TR', 'MT (Partner)', 'Karayolu', 'Tautliner 8 LDM', 2000.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km'),
('Loading address', 'Tuzla, TR', 'MT (Partner)', 'Karayolu', 'Tautliner FTL', 2800.0, NULL, NULL, NULL, '', NULL, 'Mesafe: 2076 km');
