-- Part 3/5
-- Customers 275 to 411 (137 total)

INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Hegelmann Transporte Sp. z o.o.', 'Kucelinska 22', NULL, '42-200', 'PL', 'Czestochowa', NULL, 'hegelmanntransportes@example.com'),
  ('Heimatlicht GmbH & Co. KG', 'Seiboldsdorfer Mühle 9', NULL, '83278', 'DE', 'Traunstein', NULL, 'heimatlichtgmbhcokg@example.com'),
  ('Heinrich Glaeser Nachf. GmbH', 'Blaubeurer Str. 263', NULL, '89081', 'DE', 'Ulm', NULL, 'heinrichglaesernachf@example.com'),
  ('Heinrich Salm KG', 'Printzstraße 5', NULL, '76139', 'DE', 'Karlsruhe', NULL, 'Poersel@salm-karlsruhe.de'),
  ('Heizomat GmbH', 'Maicha 21', NULL, '91710', 'DE', 'Gunzenhausen', NULL, 'heizomatgmbh@example.com'),
  ('Heldenstern*UG', 'Herrengut 15', NULL, '76530', 'DE', 'Baden-Baden', NULL, 'heldensternug@example.com'),
  ('Hellmann Worldwide Logistics Road & Rail GmbH & Co. KG', 'Ludwig- Erhard- Strasse 7', NULL, '28197', 'DE', 'Bremen', NULL, 'hellmannworldwidelog@example.com'),
  ('Helmut Müller GmbH | Internationale Spedition', 'Adam-Geisler-Str. 1', NULL, '82140', 'DE', 'Olching', NULL, 'helmutmllergmbhinter@example.com'),
  ('Henan Aotie International Freight Forwarding Co.,Ltd.', 'Room 2012, Expo Center, 28 Dongfeng Road, Jinshui District,', NULL, NULL, 'CN', 'City ,Henan Province,China', NULL, 'henanaotieinternatio@example.com'),
  ('Henke Marc', 'Dessauerstr. 60', NULL, '45472', 'DE', 'Mülheim an der Ruhr', NULL, 'Marc.Henke@pet-logistics.com'),
  ('Hesse GmbH & Co. KG', 'Warendorfer Str. 21', NULL, '59075', 'DE', 'Hamm', NULL, 'hessegmbhcokg@example.com'),
  ('Hessischer Leichtathletik-Verband', 'Otto-Fleck-Schneise 4', NULL, '60528', 'DE', 'Frankfurt am Main', NULL, 'hessischerleichtathl@example.com'),
  ('Het beste van de Kweker', 'Lange Broekweg', NULL, '2671DT', 'NL', 'Naaldwijk', NULL, 'hetbestevandekweker@example.com'),
  ('Hierl & Müller', 'Gustav-Hertz-Str. 10', NULL, '94315', 'DE', 'Straubing', NULL, 'hierlmller@example.com'),
  ('Highleigh Nurseries', 'Highleigh Road, Sidlesham,', NULL, 'PO20 7NR', 'UK', 'Chichester, West Sussex', NULL, 'highleighnurseries@example.com'),
  ('Hoever-Papertrade UG (haftungsbeschränkt)', 'Bleckering 14', NULL, '22119', 'DE', 'Hamburg', NULL, 'hoeverpapertradeugha@example.com'),
  ('Hope Tree International GmbH', 'Ostergartenstr. 10', NULL, '82538', 'DE', 'Geretsried', NULL, 'hopetreeinternationa@example.com'),
  ('Hubert Plenter GmbH', 'Amelunxenstaße 1', NULL, '48167', 'DE', 'Münster', NULL, 'hubertplentergmbh@example.com'),
  ('I.Q.Courier e.K.', 'Carl-Zeiss-Ring 15a', NULL, '85737', 'DE', 'Ismaning', NULL, 'iqcourierek@example.com'),
  ('IEM GmbH', 'Sreitelsfingerstraße 45E', NULL, '88131', 'DE', 'Lindau', '+49 (0) 151232 09767', 'iemgmbh@example.com'),
  ('IIC AG', 'Breisacher Strasse 86', NULL, '79110', 'DE', 'Freiburg im Breisgau', NULL, 'iicag@example.com'),
  ('IKAU INVEST s.r.o.', 'Rehorova 1004/32', NULL, 'CZ', 'CZ', 'Praha 3', NULL, 'ikauinvestsro@example.com'),
  ('IKRA UK Limited', 'Mulberry Way, Belvedere', NULL, 'DA17 6AN', 'UK', 'Kent', NULL, 'ikrauklimited@example.com'),
  ('IMEDCO AG', 'Industriestrasse West 14', NULL, '4614', 'CH', 'Hägendorf', '+41 62 209 40 20', 'imedcoag@example.com'),
  ('IMF Modell- u. Formenbau Illertal GmbH', 'Gassenäcker 45', NULL, '89195', 'DE', 'Staig', NULL, 'imfmodelluformenbaui@example.com'),
  ('INOTEC GmbH', 'Dieselstraße 1', NULL, '72770', 'DE', 'Reutlingen', NULL, 'inotecgmbh@example.com'),
  ('INOX Schleiftechnik GmbH & Co. KG', 'Otto-Stoelcker-Str. 31', NULL, '35066', 'DE', 'Frankenberg', '06451 210060', 'info@inox-schleiftechnik.de'),
  ('INTER-PAPIER Handelsgesellschaft mbH', 'Friedenstraße 2', NULL, '25421', 'DE', 'Pinneberg', NULL, 'interpapierhandelsge@example.com'),
  ('INTERMODAL SOLUTIONS LTD', 'Sredets area, street Lyuben Karavelov, bl 28, ap. 7', NULL, NULL, 'BG', 'Sofia', NULL, 'intermodalsolutionsl@example.com'),
  ('IPS – Intelligente Prozesslösungen GmbH', 'Dr.-Gustav-Adolph-Str. 2', NULL, '82049', 'DE', 'Pullach', '+49 89 4161 4885-0', 'info@ips-energy.com'),
  ('IVECO Poland SP. Z.O.O', 'Al. Wyscigowa', NULL, '2681', 'PL', 'Warsawa', NULL, 'ivecopolandspzoo@example.com'),
  ('IVECO SPA', 'Via Puglia 35', NULL, '10156', 'IT', 'Torino (TO)', NULL, 'ivecospa@example.com'),
  ('InXpress Bonn', 'Merianstraße 43', NULL, '53177', 'DE', 'Bonn', '+49 (0)228 5349 438', 'inxpressbonn@example.com'),
  ('InXpress Frankfurt', 'Niedernhausener Straße 53', NULL, '60326', 'DE', 'Frankfurt am Main', NULL, 'inxpressfrankfurt@example.com'),
  ('InXpress Lindau/Kempten', 'Ellgasser Straße 9c', NULL, '88161', 'DE', 'Lindenberg im Allgäu', '+49 (0)8383 92 96 055', 'info.nusser@inxpress.com'),
  ('InXpress München', 'Schwanseestr. 71b', NULL, '81549', 'DE', 'München', NULL, 'serdar.buyar@inxpress.com'),
  ('InXpress Riviera', '10 Avenue du Docteur Fabre', NULL, '6160', 'FR', 'Juan Les Pins', NULL, 'inxpressriviera@example.com'),
  ('Indeed Ireland Opetations Ltd', '80 Sir John Rogersom´s Quay, Gran canal Dock, Block B, Capital Dock', NULL, NULL, 'IE', 'Dublin DO2 HE36', NULL, 'indeedirelandopetati@example.com'),
  ('Infraserv Vakuumservice GmbH', 'Gleiwitzer Straße 8', NULL, '85386', 'DE', 'Eching', NULL, 'wieland@infraservgmbh.com'),
  ('Ingenieurbüro RT', 'Auguste-Wittig-Str. 10', NULL, '83646', 'DE', 'Bad Tölz', NULL, 'ingenieurbrort@example.com'),
  ('Innotech GmbH', 'Lengloher Strasse 8', NULL, '83342', 'DE', 'Tacherting', NULL, 'innotechgmbh@example.com'),
  ('InternationalSpeedTransport Marta Kujda', 'Wojska Polskiego 25', NULL, 'PL69110', 'PL', 'Rzepin', NULL, 'internationalspeedtr@example.com'),
  ('Interteam Speditionsgesellschaft mbH', 'Kattjahren 8', NULL, '22359', 'DE', 'Hamburg', NULL, 'interteamspeditionsg@example.com'),
  ('Inxpress Freiburg', 'Breisgaustr. 18', NULL, '79312', 'DE', 'Emmerdingen', NULL, 'inxpressfreiburg@example.com'),
  ('Inxpress Germany GmbH', 'Curiestrasse 11', NULL, '55129', 'DE', 'Mainz', NULL, 'klaus-dieter.krost@inxpress.com'),
  ('Iveco Deutschland AG', 'Nicolaus-Otto-Straße 27', NULL, '89079', 'DE', 'Ulm', '+49 89 31771 0', 'ivecodeutschlandag@example.com'),
  ('Iveco France SAS', 'Rue Des Combats Du 24 Aout 44', NULL, '69200', 'FR', 'Venissieux', NULL, 'ivecofrancesas@example.com'),
  ('Iveco Schouten Almkerk', 'Postbus 61', NULL, '4286ZH', 'NL', 'Almkerk', NULL, 'eric.simons@ivecogroup.com'),
  ('J. DAHMEN & CO. KG, SOLINGEN', 'Dellenfeld 35', NULL, '42653', 'DE', 'Solingen', NULL, 'jdahmencokgsolingen@example.com'),
  ('J.B. Metal Vision GmbH', 'Dernekamp 74', NULL, '48249', 'DE', 'Dülmen', '+49 (0) 2594 – 78310', 'info@metalvision.de'),
  ('JELL GmbH & Co. KG', 'Am Anger 38', NULL, '83233', 'DE', 'Bernau am Chiemsee', NULL, 'jellgmbhcokg@example.com'),
  ('JIT Sp. z o.o.', 'Karmazynowa 32 K,', NULL, '02-887', 'PL', 'Warszawa', NULL, 'jitspzoo@example.com'),
  ('Jerzy Kakolewski Transport Miedzynarodowy Krajowy i Spediycja', 'ul. Podgorna 15 (DEBNO)', NULL, '62-060', 'PL', 'Stęszew', '+48 618 134 436', 'jkakolewski@wp.pl'),
  ('Johannes Michael Koch', 'Rudolf-Breitscheid-Str. 27', NULL, '90762', 'DE', 'Fürth', NULL, 'johannesmichaelkoch@example.com'),
  ('Jorns AG', 'Kirchgasse 12', NULL, '4932', 'CH', 'Lotzwil', '+41 62 919 80 50', 'jornsag@example.com'),
  ('Josef Wiegand GmbH & Co. KG', 'Landstraße 12', NULL, '36169', 'DE', 'Rasdorf', NULL, 'josefwiegandgmbhcokg@example.com'),
  ('Jörg Schwab Transport', 'Kreuzkirchstrasse 14', NULL, '93437', 'DE', 'Furth im Wald', NULL, 'jrgschwabtransport@example.com'),
  ('KAISER Process and Belt Technology GmbH / Member of the KICK Group', 'Siemensring 54 ? 56', NULL, '47877', 'DE', 'Willich', '+49 (0) 2154 89107 - 0', 'info@kaiser-pbt.de'),
  ('KAYAK SP. Z O.O.', 'UL. LEDÓCHOWSKIEGO 34', NULL, '63-400', 'PL', 'OSTRÓW WIELKOPOLSKI', NULL, 'kayakspzoo@example.com'),
  ('KLAFS GmbH', 'Erich-Klafs-Straße 3', NULL, '74523', 'DE', 'Schwäbisch Hall', NULL, 'klafsgmbh@example.com'),
  ('KNS Internationale Speditions GmbH', 'Liebigstrasse 2 - 20', NULL, '22113', 'DE', 'Hamburg', NULL, 'knsinternationalespe@example.com'),
  ('KS Tools Werkzeuge-Maschinen GmbH', 'Seligenstädter Grund 10-12', NULL, '63150', 'DE', 'Heusenstamm', '+49 6104 4974 11', 'kstoolswerkzeugemasc@example.com'),
  ('KST Georg Triebel', 'Zeithstraße 70A', NULL, '53819', 'DE', 'Neunkirchen-Seelscheid', NULL, 'kstgeorgtriebel@example.com'),
  ('Kajana Ltd.', 'Aphrodite 21', NULL, '8577', 'CY', 'Tala, Paphos, Cyprus', '01719122036', 'kai@kajana.eu'),
  ('Karl Pedross S.p.A.', 'Zona Industriale 1/c', NULL, '39021', 'IT', 'Laces (BZ)', NULL, 'karlpedrossspa@example.com'),
  ('Kassen- und Waagencenter Wägesystem WSM GmbH', 'Friedenstr. 18', NULL, '81671', 'DE', 'München', '089 450624-0', 'technik@wsm-gmbh.com'),
  ('Keco Module GmbH', 'Bruchstraße 8', NULL, '55263', 'DE', 'Ingelheim am Rhein', '(0176) 245 982 36', 'frachten@keco-module.de'),
  ('Keil Transport- und Logistik GmbH', 'Nikolaistr. 16', NULL, '30159', 'DE', 'Hannover', '+491633111260', 'keil.w@arcor.de'),
  ('Kempf & Seifried GmbH', 'Talweg 10', NULL, '72505', 'DE', 'Krauchenwies-Göggingen', NULL, 'seifried@kempf-seifried.de'),
  ('Kiesel Used GmbH', 'Baindter Straße 21', NULL, '88255', 'DE', 'Baienfurt', '49 751 50 04 859', 'h.denzel@kiesel.net'),
  ('Kirtur Turizm Insaat Taahhüt Elektrik San. Tic. Ltd. STİ', 'Bulgurlu mah. Alemdag cad. no: 60', 'Masaldan is merkezi E Blok, No: 4 Camlıca,', NULL, 'TR', 'Istanbul', '902164126010', 'info@kirtur.comtr'),
  ('Klöpfer Holzhandel GmbH & Co. KG', 'Schleißheimer Straße 104', NULL, '85748', 'DE', 'Garching bei München', NULL, 'klpferholzhandelgmbh@example.com'),
  ('Kometer Grabmale Steinmetzbetrieb', 'Georg-Meisenbach-Str. 4', NULL, '81549', 'DE', 'München', NULL, 'kometergrabmalestein@example.com'),
  ('Kraftwerk Living Technologies', 'Maria-Theresia-Strasse 49', NULL, '4600', 'AT', 'Wels', NULL, 'kraftwerklivingtechn@example.com'),
  ('Krakau & Söhne Gewürze GmbH', 'Thüringerstraße 43', NULL, '46286', 'DE', 'Dorsten', NULL, 'b.raedel@krakau-gewuerze.de'),
  ('Krones AG', 'Böhmerwaldstraße 5', NULL, '93073', 'DE', 'Neutraubling', NULL, 'kronesag@example.com'),
  ('Ktec-Service GmbH', 'Am Gewerbepark 12', NULL, '9431', 'AT', 'St. Stefan im Lavanttal', '+43 (0) 676 – 897 153 300', 'spareparts@ktec-service.at'),
  ('Kuehne + Nagel Ltd', 'Unit 1 , Heathrow South Cargo Centre', NULL, 'TW14 0PH', 'UK', 'Girling Way, Feltham', NULL, 'kuehnenagelltd@example.com'),
  ('Kugler Feinkost GmbH', 'Taxetstraße 5', NULL, '85599', 'DE', 'Vaterstetten', NULL, 'kuglerfeinkostgmbh@example.com'),
  ('KÜHNE+NAGEL (AG & Co.) KG', 'Hansastraße 10', NULL, '35708', 'DE', 'Haiger', NULL, 'khnenagelagcokg@example.com'),
  ('L.I.T. Air & Sea GmbH', 'Franz-Stickan-Straße 4', NULL, '28197', 'DE', 'Bremen', NULL, 'speed@lit.de'),
  ('L.I.T. Speed GmbH', 'Mottmannstraße 1-3', NULL, '53842', 'DE', 'Troisdorf', '+49 4401920303', 'speed@lit.de'),
  ('LB-Olympia GmbH', 'Rasmussengasse 4', NULL, '1210', 'AT', 'Wien', NULL, 'lbolympiagmbh@example.com'),
  ('LEWA Attendorn GmbH', 'Am Wassertor 5', NULL, '57439', 'DE', 'Attendorn', NULL, 'lewaattendorngmbh@example.com'),
  ('LGL Haushaltswaren GmbH', 'Helferner Weg 14b', NULL, '49214', 'DE', 'Bad Rothenfelde', NULL, 'rechnung@lgl.eu'),
  ('LIECO GmbH & Co KG', 'Diesseits 73', NULL, '4973', 'AT', 'Sankt Martin im Innkreis', NULL, 'liecogmbhcokg@example.com'),
  ('LMB Stahl- & Metallbau GmbH', 'Musenbergstraße 42', NULL, '81929', 'DE', 'München', NULL, 'lmbstahlmetallbaugmb@example.com'),
  ('LSP', 'Dachauer Str. 65', NULL, '80335', 'DE', 'München', NULL, 'lsp@example.com'),
  ('LUPİ LOJİSTİK ANONİM ŞİRKETİ', 'MEVLANA MAH.YILDIRIM BEYAZIT CAD.MORMENEKŞE SİTESİ NO:14 C  İC KAPİ NO', NULL, '4 ESEN', 'TR', 'Yurt Istabul', '6091229268', 'yildiz@lupilojistik.com'),
  ('La Nuova Casa GmbH & Co. KG', 'Landsberger Straße 374', NULL, '80687', 'DE', 'München', NULL, 'lanuovacasagmbhcokg@example.com'),
  ('Lacoste Austria GmbH', 'Söllheimerstrasse 16', NULL, '5020', 'AT', 'Salzburg', NULL, 'accounting-de@lacoste.com'),
  ('Lacoste Denmark ApS', 'Lindgreens Alle 12, 2.tv.', NULL, '2300', 'DK', 'Københagn S', NULL, 'lacostedenmarkaps@example.com'),
  ('Lacoste Germany GmbH', 'Leopoldstrasse 158', NULL, '80804', 'DE', 'München', '+49 06 98 679 80 90', 'info@lacoste.com'),
  ('Lacoste Germany GmbH c/o KPMG Tax AS', 'Postboks 7000', NULL, '306', 'NO', 'Oslo', NULL, 'lacostegermanygmbhco@example.com'),
  ('Lacoste Sweden AB', 'Sank Eriksgatan 119', NULL, '131 43', 'SE', 'Stockholm', NULL, 'lacosteswedenab@example.com'),
  ('Lacoste Switzerland AG', 'Wright-Strasse 9', NULL, '8152', 'CH', 'Opfikon', NULL, 'accounting-ch@lacoste.com'),
  ('Lacoste UK Ltd', '4th Floor - Holborn Gate – 326-330 High Holborn', NULL, 'WC1V 7PP', 'UK', 'London', NULL, 'skegel@lacoste.com'),
  ('Landeshauptstadt München', 'Schäflarnstr.10', NULL, '81371', 'DE', 'München', NULL, 'landeshauptstadtmnch@example.com'),
  ('Landeshauptstadt München Referat für Bildung und Sport', 'Bayerstr. 28', NULL, '80335', 'DE', 'München', NULL, 'landeshauptstadtmnch@example.com'),
  ('Landi Sp. z o.o.', 'Nowogrodzka 50/515', NULL, '00-695', 'PL', 'Warszawa', NULL, 'office@landilogistics.com'),
  ('Lectra Deutschland GmbH', 'Adalperostr. 80', NULL, '85737', 'DE', 'Ismaning', NULL, 'lectradeutschlandgmb@example.com'),
  ('Liebherr-Werk Nenzing GmbH', 'Dr. Hans Liebherr Str. 1', NULL, '6710', 'AT', 'Nenzing', '+43 50809 44934', 'lwn-disposition@liebherr.com'),
  ('Life is good GmbH', 'Reichenbachstraße 33', NULL, '80469', 'DE', 'München', NULL, 'lifeisgoodgmbh@example.com'),
  ('Ligural Sp. z o.o.', 'Adam Mickiewicza 36A', NULL, '01-616', 'PL', 'Warszawa', NULL, 'liguralspzoo@example.com'),
  ('Limexo Europe s.r.o.', 'Ricni 456/10', NULL, '11800', 'CZ', 'Praha', NULL, 'invoice@limexo.eu'),
  ('Lini''s Bites GmbH', 'Gärtnerplatz 1', NULL, '80469', 'DE', 'Munich', NULL, 'linisbitesgmbh@example.com'),
  ('Ludwig Schleicher Anlagenbau GmbH & Co. KG', 'Neu-Weiher-Str. 4', NULL, '92690', 'DE', 'Pressath', NULL, 'ludwigschleicheranla@example.com'),
  ('M.J Global Logistic Co.,Ltd.', '240, Jungang-daero, Dong-gu, 6F, Hyundai Insurance Building', NULL, NULL, 'KR', 'Busan', NULL, 'mjgloballogisticcolt@example.com'),
  ('MAGNA Projektentwicklung West GmbH', 'Limbecker Platz 1', NULL, '45127', 'DE', 'Essen', NULL, 'magnaprojektentwickl@example.com'),
  ('MAKO TSL sp. z o.o.', 'ulica Leona Droszyńskiego 24', NULL, '80-381', 'PL', 'Gdansk', '+48585003434', 'info@makotsl.com'),
  ('MARTIN BRAUN KG', 'Tillystraße 17', NULL, '30459', 'DE', 'Hannover', NULL, 'martinbraunkg@example.com'),
  ('MASCHINENHANDEL Heinz Singler', 'Elbestraße 51', NULL, '82538', 'DE', 'Geretsried', '08171 6838', 'singler@t-online.de'),
  ('MBS Logistics GmbH', 'Hansestrasse 57', NULL, '51149', 'DE', 'Köln', NULL, 'mbslogisticsgmbh@example.com'),
  ('ME-Pressen GmbH', 'Hertener Straße 108', NULL, '45892', 'DE', 'Gelsenkirchen', NULL, 'mepressengmbh@example.com'),
  ('MEDIA 6 AGENCEMENT SHOP FITTINGS', '5, avenue des Berthaudières', NULL, '44680', 'FR', 'Sainte Pazanne', NULL, 'media6agencementshop@example.com'),
  ('MEP S.R.L.', 'zona ind.le S.Maria a Terme', NULL, '63087', 'IT', 'Comunanza', '+39 0736 845076', 'info@mep-snc.com'),
  ('MGZ München', 'Bayerstr. 3-5', NULL, '80335', 'DE', 'München', '+49 (0)89 30 90 886-0', 'rechnungen@mgz-muenchen.de'),
  ('MIDDLE EAST AIRLINES – AIRLIBAN S.A.L', 'Hugo-Eckener-Ring 161', 'Frankfurt Airport Center 1 Geb. 234', '60549', 'DE', 'Frankfurt am Main', NULL, 'AridiMo@mea.aero'),
  ('MIKI - TRANS Lukasz Kaliszewski', 'Brzozie Lubawskie 73', NULL, '13-306', 'PL', 'Kurzetnik', NULL, 'mikitranslukaszkalis@example.com'),
  ('MKS Maschinen Handels GmbH', 'Lothforster Str. 46', NULL, '41849', 'DE', 'Wassenberg', NULL, 'mksmaschinenhandelsg@example.com'),
  ('MM Stahlbau GmbH', 'Dorfstraße 24', NULL, '86676', 'DE', 'Ehekirchen', NULL, 'mmstahlbaugmbh@example.com'),
  ('MONTRASIO Werkzeugmaschinen GmbH', 'Lanzstraße 6', NULL, '68789', 'DE', 'Sankt Leon-Rot', '+49-6227-8651-0', 'carlo.montrasio@montrasio-gmbh.de'),
  ('MPIPZ Köln', 'Carl von Linne Weg 10', NULL, '50829', 'DE', 'Köln', NULL, 'mpipzkln@example.com'),
  ('MPM GmbH', 'Lengloher Str. 8', NULL, '83342', 'DE', 'Tacherting', NULL, 'mpmgmbh@example.com'),
  ('MS Marine GmbH', 'Gewerbegebiet Ost 31', NULL, '92353', 'DE', 'Postbauer-Heng', '+49 9188 3079896', 'post@ms-marine.de'),
  ('MSD Express GmbH', 'Dieselstr. 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'msdexpressgmbh@example.com'),
  ('MSD Transporte - Dejan Gavrilovic', 'Dieselstr. 28', NULL, '85748', 'DE', 'Garching', NULL, 'msdtransportedejanga@example.com'),
  ('Mack Rides GmbH & Co KG', 'Mauermattenstrasse 4', NULL, '79183', 'DE', 'Waldkirch', '+49 7681 2000-0', 'info@mack-rides.com'),
  ('Maier Pharma Vertrieb GmbH', 'Gewerbering 5', NULL, '85777', 'DE', 'Fahrenzhausen', NULL, 'corina.flamensbeck@maierpharma.de'),
  ('Mallorca Real Estate GmbH & Co. KG', 'Isarwinkel 8', NULL, '81379', 'DE', 'München', NULL, 'mallorcarealestategm@example.com'),
  ('Mamarella GmbH', 'Geisenhausenerstr. 17', NULL, '81379', 'DE', 'München', NULL, 'mamarellagmbh@example.com'),
  ('MankeTech GmbH', 'Stahlstr. 27', NULL, '33415', 'DE', 'Verl', NULL, 'manketechgmbh@example.com'),
  ('Manolya Electronics GmbH & Co KG', 'Kurfürstendamm 59', NULL, '10707', 'DE', 'Berlin', '+49 30 397 444 60', 'y.shatalinskyi@manolya.de'),
  ('Maschinen Stockert Großhandels- Gesellschaft mit beschränkter Haftung', 'Friedrich-Bergius-Straße 17+1', NULL, '85662', 'DE', 'Hohenbrunn', NULL, 'sa.stockert@maschinen-stockert.de'),
  ('MedAdvance GmbH & Co. KG', 'Reisertstr. 24', NULL, '53773', 'DE', 'Hennef (Sieg)', NULL, 'medadvancegmbhcokg@example.com'),
  ('MediaRange GmbH', 'Zum Quellenpark 29', NULL, '65812', 'DE', 'Bad Soden am Taunus', '+49 6196 523 81 85', 'kontakt@mediarange.de'),
  ('Medien-Dienstleistungen Knoblich GmbH', 'Senftlstraße 1', NULL, '81541', 'DE', 'München', NULL, 'mediendienstleistung@example.com');