-- SQL to import customers into Supabase
-- Total customers: 681

-- Batch 1/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('089 Paletten - Paletten & Gitterboxen Handel', 'Hochmutting 1', NULL, '85764', 'DE', 'Oberschleißheim', NULL, '089palettenpaletteng@example.com'),
  ('270 Vision Ltd', 'Caxton Close, Unit 34 Basepoint Business Centre', NULL, 'SP10 3FG', 'UK', 'Andover', NULL, '270visionltd@example.com'),
  ('3ks profile gmbh', 'Asangstrasße 16', NULL, '94436', 'DE', 'Simbach', NULL, '3ksprofilegmbh@example.com'),
  ('ACTIV-IMMOBILIEN GmbH & Co. KG', 'Ferdinand-Dünkel-Straße 5', NULL, '88433', 'DE', 'Schemmerhofen', NULL, 'activimmobiliengmbhc@example.com'),
  ('ACUA Ocean Limited', '86-90 Paul Street, 3rd Floor', NULL, 'EC2A 4NE', 'UK', 'London', NULL, 'acuaoceanlimited@example.com'),
  ('ADRA Trans Adrian Swierczynski', 'Szpegawa Bukowa 17', NULL, '83-112', 'PL', 'Lubiszewo', NULL, 'adratransadrianswier@example.com'),
  ('AERIUS Marine GmbH', 'Lübecker Straße 128', NULL, '22087', 'DE', 'Hamburg', NULL, 'aeriusmarinegmbh@example.com'),
  ('AERVIDEO GmbH', 'Wolframstraße 24', NULL, '70191', 'DE', 'Stuttgart', NULL, 'aervideogmbh@example.com'),
  ('AGMG MUNICH GmbH', 'Hauptstraße 39', NULL, '85579', 'DE', 'Neubiberg', NULL, 'info@agmgmunich.com'),
  ('AGS Engineering Metalltechnik GmbH', 'Ernst-Wiss-Straße 18', NULL, '65933', 'DE', 'Frankfurt am Main', NULL, 'agsengineeringmetall@example.com'),
  ('AKDB', 'Hansastraße 12-16', NULL, '80686', 'DE', 'München', NULL, 'akdb@example.com'),
  ('AMBERGREEN FACILITIES SL', 'PLANTA 12-MOD.B, PASEO CASTELLANA 95 - EDIF.TORRE EUROPA', NULL, '28046', 'ES', 'Madrid', NULL, 'ambergreenfacilities@example.com'),
  ('AMBERGREEN SOLUTIONS SL.', 'C/ DELS FOGAINERS, 84', NULL, '46190', 'ES', 'Ribarroja del Turia, Valencia', NULL, 'ambergreensolutionss@example.com'),
  ('AMHAIMAR IT', 'Schäftlarnstr. 10 (Altes Kontorhaus)', NULL, '81371', 'DE', 'München', NULL, 'amhaimarit@example.com'),
  ('ANTS Logistic GmbH', 'Karl-Schmid-Ring 9', NULL, '07743', 'DE', 'Jena', '+49 3641 3279270', 'info@ants-log.de'),
  ('ARGE VisionBox', 'Fürstenrieder Straße 5', NULL, '80687', 'DE', 'München', NULL, 'argevisionbox@example.com'),
  ('AS Grundbesitz & Beteiligungen GmbH', 'Am Heidenknock 10', NULL, '95326', 'DE', 'Kulmbach', NULL, 'asgrundbesitzbeteili@example.com'),
  ('AS Stahlpartner GmbH', 'Frankfurter Straße  49', NULL, '61239', 'DE', 'Ober-Mörlen', NULL, 'asstahlpartnergmbh@example.com'),
  ('ASTRAN CARGO SERVICES', '519 New Hythe Lane. Larkfield', NULL, 'ME20 6SB', 'UK', 'Maidstone, Kent', NULL, 'astrancargoservices@example.com'),
  ('ASW Maschinenbau', 'Hasenäcker 13', NULL, '88142', 'DE', 'Wasserburg (Bodensee)', NULL, 'aswmaschinenbau@example.com'),
  ('AUC - Akademie der Unfallchirurgie GmbH', 'Wilhelm-Hale-Straße 46 B', NULL, '80639', 'DE', 'München', NULL, 'aucakademiederunfall@example.com'),
  ('AVANTGARDE Gesellschaft für Kommunikation mbH', 'Atelierstraße 10', NULL, '81671', 'DE', 'Munich', NULL, 'rechnungen.kom@avantgarde.de'),
  ('AZ Armaturen GmbH', 'Waldstrasse 7', NULL, '78087', 'DE', 'Mönchweiler', NULL, 'azarmaturengmbh@example.com'),
  ('Abrechnung', 'Rütersbarg 52', NULL, '22529', 'DE', 'Hamburg', NULL, 'abrechnung@example.com'),
  ('Adinotec AG', 'Hohenzollernstrasse 89', NULL, '80796', 'DE', 'München', NULL, 'adinotecag@example.com'),
  ('Adinotech GmbH', 'Salztorgasse 5/5/17', NULL, '1010', 'AT', 'Wien', NULL, 'adinotechgmbh@example.com'),
  ('AdlerTech GbR', 'An der Waldburg 15', NULL, '01816', 'DE', 'Bad Gottleuba-Berggießhübel', NULL, 'kontakt@adler-tech.de'),
  ('Aero Ruzgar End. A.S.', 'Ege Serbest Bölgesi', 'Zafer Sb Mah.Yalçın Yolu Cad.No.13', '35410', 'TR', 'Gaziemir', '+90 232 251 93 71', 'aeroruzgarendas@example.com'),
  ('Aktiv Assekuranz Makler GmbH', 'Hanauer Straße 67', NULL, '80993', 'DE', 'München', NULL, 'aktivassekuranzmakle@example.com'),
  ('Akudmedpharm GmbH', 'Kolpingstr. 9', NULL, '97332', 'DE', 'Volkach', NULL, 'norbert.seis@gmx.net'),
  ('Albert Kerbl GmbH', 'Felizenzell 9', NULL, '84428', 'DE', 'Buchbach', NULL, 'albertkerblgmbh@example.com'),
  ('Albert-Ludwigs-Universität Freiburg', 'Rempartstr. 15', NULL, '79085', 'DE', 'Freiburg im Breisgau', NULL, 'albertludwigsunivers@example.com'),
  ('Alfons Koester & Co. GmbH', 'Am Trippelsberg 43', NULL, '40589', 'DE', 'Düsseldorf', '+49/211/879646 – 36', 'alfonskoestercogmbh@example.com'),
  ('Ali Tuna', 'Hansestr. 63 A', NULL, '51149', 'DE', 'Köln', NULL, 'alituna@example.com'),
  ('Allgaier GmbH', 'Max-Eyth-Straße 20', NULL, '89231', 'DE', 'Neu-Ulm', '+49 (0) 731 97 44 0 707', 'allgaiergmbh@example.com'),
  ('Allsta Spedition GmbH', 'Industriestraße 37', NULL, '28199', 'DE', 'Bremen', NULL, 'allstaspeditiongmbh@example.com'),
  ('Alpha Industries GmbH & Co. KG, European Headquarters', 'Siemensstraße 11', NULL, '63263', 'DE', 'Neu-Isenburg', '+4915222659661', 'accounting@alphaindustries.eu'),
  ('Alphabet Fuhrparkmanagement GmbH', 'Lilienthalalle 26', NULL, '80786', 'DE', 'München', NULL, 'alphabetfuhrparkmana@example.com'),
  ('Alpinia Institute for Life Sciences AG', 'Bahnhofstrasse 34', NULL, '8880', 'CH', 'Walenstadt', NULL, 'alpiniainstituteforl@example.com'),
  ('Alpinia Laudanum GmbH', 'Wipplingerstraße 29/4', NULL, '1010', 'AT', 'Wien', NULL, 'alpinialaudanumgmbh@example.com'),
  ('Antiquariat Schneider-Henn', 'Mühlbachstr. 19', NULL, '82229', 'DE', 'Seefeld', NULL, 'antiquariatschneider@example.com'),
  ('Antiquitäten am Alten Hof', 'Sparkassenstraße 11', NULL, '80331', 'DE', 'München', NULL, 'antiquittenamaltenho@example.com'),
  ('ApfelKomm GmbH', 'Kaasgrabengasse 52/2/5', NULL, '1190', 'AT', 'Wien', NULL, 'apfelkommgmbh@example.com'),
  ('Aplus Steuerberater München Lyssoudis & Kugler PartGmbB', 'Im Regerhof, Welfenstr. 22', NULL, '81541', 'DE', 'München', NULL, 'can@aplus-steuerberater.de'),
  ('AquaSoli GmbH & CO. KG', 'Birkenleiten 41', NULL, '81543', 'DE', 'München', NULL, 'aquasoligmbhcokg@example.com'),
  ('Aritex Cading Deutschland GmbH', 'Edisonstrasse 23', NULL, '74076', 'DE', 'Heilbronn', NULL, 'aritexcadingdeutschl@example.com'),
  ('Arno Rosenlöcher GmbH & Co. KG', 'Dieselstraße 28', NULL, '85748', 'DE', 'Garching', NULL, 'arnorosenlchergmbhco@example.com'),
  ('AsstrA Forwarding AG', 'Staubstrasse 15', NULL, '8038', 'CH', 'Zürich', '+41 44 211 72 60', 'office@asstra.com'),
  ('Asstra UK LTD', '13 The Causeway, Teddington', NULL, 'TW11 0JR', 'UK', 'Teddington', '+44-203-908-5667', 'office@asstra.co.uk'),
  ('Atlant Transport', 'ulica Okólna 27', NULL, '66-400', 'PL', 'Gorzow Wielkopolski', NULL, 'atlanttransport@example.com');

-- Batch 2/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Audio Reference GmbH', 'Alsterkrugchaussee 435', NULL, '22335', 'DE', 'Hamburg', NULL, 'audioreferencegmbh@example.com'),
  ('Auswärtiges Amt', 'Adenauerallee 99-103', NULL, '53113', 'DE', 'Bonn', NULL, 'auswrtigesamt@example.com'),
  ('Auto Magnus GmbH', 'Wasserbrugerlandstrasse 56', NULL, '81825', 'DE', 'München', NULL, 'automagnusgmbh@example.com'),
  ('Auvictum Erste Beteiligungs GmbH Seniorenresidenz Haus Seeufer', 'Bahnhofstraße 8-10', NULL, '59519', 'DE', 'Möhnesee', '+49 (0) 5272/391-415', 'auvictumerstebeteili@example.com'),
  ('Auvictum Zweite Beteiligungs GmbH', 'Kötztinger Straße 43', NULL, '94249', 'DE', 'Bodenmais', NULL, 'auvictumzweitebeteil@example.com'),
  ('B&E Internationale Logistik GmbH & Co. KG', 'Siemensstr. 4', NULL, '85716', 'DE', 'Unterschleißheim', NULL, 'beinternationalelogi@example.com'),
  ('B&L Property Management GmbH', 'Große Elbstraße 47', NULL, '22767', 'DE', 'Hamburg', NULL, 'blpropertymanagement@example.com'),
  ('BINDER GmbH & Co. KG', 'Eike-Kerstein-Straße 4', NULL, '31789', 'DE', 'Hameln', NULL, 'Paul.Alles@binder24.com'),
  ('BLG International Forwarding GmbH & Co. KG', 'Dieselstrasse 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'blginternationalforw@example.com'),
  ('BMW Group', 'Laaberstr. 7', NULL, '84130', 'DE', 'Dingolfing', '+49 8731 76-23803', 'stefan.wuerfel@bmw.de'),
  ('BOMAG GmbH', 'Hellerwald', NULL, '56154', 'DE', 'Boppard', NULL, 'bomaggmbh@example.com'),
  ('BOSPORUS Handelsgesellschaft mbH', 'Marktstr. 10 (AsmusHaus)', NULL, '50968', 'DE', 'Köln', NULL, 'bosporushandelsgesel@example.com'),
  ('BREB Schifffahrts GmbH & Co. KG MS Duhnen & c/o: Briese Schiffahrts Gmbh & Co. KG', 'Hafenstr. 12', NULL, '26789', 'DE', 'Leer', NULL, 'brebschifffahrtsgmbh@example.com'),
  ('BSH Hausgeräte GmbH', 'Carl-Wery-Straße 34', NULL, '81739', 'DE', 'Munich', NULL, 'bshhausgertegmbh@example.com'),
  ('BSP GmbH', 'Siebending 6', NULL, '9433', 'AT', 'Sankt Andrä', NULL, 'bspgmbh@example.com'),
  ('Barsan Global Logistik GmbH', 'Hertha-Sponer-Straße 1', NULL, '82216', 'DE', 'Maisach', NULL, 'barsangloballogistik@example.com'),
  ('Bartholet Maschinenbau AG', 'Lochriet', NULL, '8890', 'CH', 'Flums', NULL, 'bartholetmaschinenba@example.com'),
  ('BauKraftEvent', 'Bleichweg 5', NULL, '73485', 'DE', 'Unterschneidheim', NULL, 'baukraftevent@example.com'),
  ('Baumscheibenkontor', 'Agnes-Bernauer-Str. 1', NULL, '80687', 'DE', 'München', NULL, 'baumscheibenkontor@example.com'),
  ('Bavaria General Services GmbH', 'Bomhardstr. 7', NULL, '82031', 'DE', 'Grünwald', NULL, 'bavariageneralservic@example.com'),
  ('BayWa AG', 'Postfach 810106', NULL, '81901', 'DE', 'München', '+49 89 9222-0', 'baywaag@example.com'),
  ('Bayerische Landeszentrale für politische Bildungsarbeit', 'Englschalkinger Straße 12', NULL, '81925', 'DE', 'München', NULL, 'bayerischelandeszent@example.com'),
  ('Bayerisches Staatsministerium für Familie, Arbeit und Soziales', 'Winzererstr. 9', NULL, '80797', 'DE', 'München', NULL, 'bayerischesstaatsmin@example.com'),
  ('Bela Living GmbH', 'Wallstraße 9-13', NULL, '10179', 'DE', 'Berlin', '+4915566636411', 'service@bela-living.de'),
  ('Benediktuspark Am Stift GmbH', 'Stiftsplatz 2a', NULL, '37176', 'DE', 'Nörten-Hardenberg', '+49 (0) 5503 8085-0', 'noerten@auvictum.de'),
  ('Bertling Kazakh Logistics LLP', 'Building #9, Admiral Lev Vladimirsky street', NULL, 'E02A4H5', 'KZ', 'Atyrau', '+7 7122 763171/73/74/75', 'aigul.utepova@bertling.com'),
  ('Berylls Strategy Advisors GmbH', 'Maximilianstraße 34', NULL, '80539', 'DE', 'München', NULL, 'beryllsstrategyadvis@example.com'),
  ('Big Potato Limited', '1 Holywell Lane London', NULL, 'EC2A 3ET', 'UK', 'London', NULL, 'bigpotatolimited@example.com'),
  ('Blanke Briefhüllen GmbH', 'Allee 40', NULL, '74072', 'DE', 'Heilbronn', '07131 3899-500', 'info@brief-huellen.de'),
  ('Bosse Gartenbaubedarf e.K.', 'Gartenstr. 28', NULL, '75446', 'DE', 'Wiernsheim', NULL, 'bosse.mail@t-online.de'),
  ('Broszeit GmbH', 'Am Föhrenried 7', NULL, '88255', 'DE', 'Baindt-Schachen', NULL, 'broszeitgmbh@example.com'),
  ('Buchele Raumgestaltung GmbH', 'St.-Pauli Straße 10', NULL, '80336', 'DE', 'München', NULL, 'info@buchele-raumgestaltung.de'),
  ('Burak-Supermarkt GmbH', 'Eintrachtstr. 16', NULL, '81541', 'DE', 'München', NULL, 'buraksupermarktgmbh@example.com'),
  ('Burkart Dörrobst AG', 'Rüstenschwil 38', NULL, '5644', 'CH', 'Auw', NULL, 'burkartdrrobstag@example.com'),
  ('BÜNDNIS 90 / DIE GRÜNEN', 'Sendlinger Str. 47', NULL, '80331', 'DE', 'München', NULL, 'bndnis90diegrnen@example.com'),
  ('Bürkle Leisten & Profile GmbH', 'Siemensstraße 30', NULL, '67227', 'DE', 'Frankenthal (Pfalz)', NULL, 'brkleleistenprofileg@example.com'),
  ('C.E. Noerpel GmbH Zweigniederlassung Heidenheim', 'Wilhelm-Kentner-Str. 1', NULL, '89520', 'DE', 'Heidenheim an der Brenz', '+49 7314 0050', 'info@noerpel.de'),
  ('CAMP RAMPS', 'Wiesenstrasse 3', NULL, '52222', 'DE', 'Stolberg', NULL, 'campramps@example.com'),
  ('CAPRICE Schuhproduktion GmbH & Co. KG', 'Blocksbergstraße', NULL, '66955', 'DE', 'Pirmasens', '+49 (0) 63 31 / 27 33-0', 'ralf.koch@caprice.de'),
  ('CARGOBIZ MAGDALENA GO?AB', 'Nied?wiady 16/4', NULL, '62-800', 'PL', 'Kalisz', NULL, 'cargobizmagdalenagoa@example.com'),
  ('CBTS', 'Sulzbacher Straße 10', NULL, '71522', 'DE', 'Backnang', '+49(0) 7191 899 26 26', 'info@c-b-t-s.de'),
  ('CFG Hocholdinger INRES', 'Friedrich-Ebert-Allee 144', NULL, '53113', 'DE', 'Bonn', NULL, 'cfghocholdingerinres@example.com'),
  ('CHECK24 Vergleichsportal Möbel GmbH', 'Wallstr. 9-13', NULL, '10179', 'DE', 'Berlin', NULL, 'check24vergleichspor@example.com'),
  ('CHORAL GmbH', 'Machabäerstraße 28', NULL, '50668', 'DE', 'Köln', NULL, 'choralgmbh@example.com'),
  ('CHS Container Handel GmbH', 'Tillmannstraße 19', NULL, '28239', 'DE', 'Bremen', NULL, 'chscontainerhandelgm@example.com'),
  ('CLG - Consolidation & Logistics GmbH', 'Rossweg 20 - Gebäude C', NULL, '20457', 'DE', 'Hamburg', NULL, 'clgconsolidationlogi@example.com'),
  ('CLS Rimer', 'Bradley Str. 16', NULL, '89231', 'DE', 'Neu-Ulm', NULL, 'clsrimer@example.com'),
  ('COSRAU GmbH', 'Königstr. 22', NULL, '83022', 'DE', 'Rosenheim', '+49 8031 31029', 'info@cosrau.com'),
  ('CPI Vertex Antennentechnik GmbH', 'Baumstraße 50', NULL, '47198', 'DE', 'Duisburg', NULL, 'cpivertexantennentec@example.com'),
  ('CRAs Ausbau- & Montageservice', 'Schmiedestraße 14A', NULL, '14554', 'DE', 'Seddiner See', NULL, 'crasausbaumontageser@example.com');

-- Batch 3/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('CS Transitarios, LDA', 'Rua Dr. Joaquim Manuel da Costa 1086, 1o Esquerdo Sala 8', NULL, '4420-437', 'PT', 'Valbom - Gondomar', '+351 963 934 217', 'trafego@cstransitarios.pt'),
  ('CURT HENNE GmbH & Co.KG', 'Franz-Stickan-Straße 1', NULL, '28197', 'DE', 'Bremen', NULL, 'curthennegmbhcokg@example.com'),
  ('Cani Grup', 'Yalinayak Mah. Soda Bekire Caddesi Kapi No: 105', NULL, '33020', 'TR', 'Toroslar / Mersin', '+90 324 235 22 00', 'info@canigrup.com'),
  ('Caradvance', 'Kistlerhofstraße 170', NULL, '81379', 'DE', 'München', NULL, 'caradvance@example.com'),
  ('CargoCrew International GmbH', 'Poppenbütteler Bogen 39 (Haus B)', NULL, '22399', 'DE', 'Hamburg', '+49 (0)40 524 79 84 – 30', 'info@cargocrewInternational.de'),
  ('Cargosteer So. z.o.o.', 'ul.Slaska 17', NULL, '81-319', 'PL', 'Gdynia', NULL, 'cargosteersozoo@example.com'),
  ('Casa Fortunata GmbH', 'Maximiliansplatz 12', NULL, '80333', 'DE', 'München', NULL, 'casafortunatagmbh@example.com'),
  ('Cleansteel GmbH', 'Hutschenreutherstraße 4', NULL, '92637', 'DE', 'Weiden in der Oberpfalz', NULL, 'jan.filander@cleansteel.de'),
  ('Coach Stores Ltd t/a Coach, Stuart Weitzmann & Kate Spade', 'Seventh Floor Brunel Building 2 Canalside Walk', NULL, 'W2 1DG', 'UK', 'London', NULL, 'coachstoresltdtacoac@example.com'),
  ('Colt International GmbH', 'Max-Planck-Straße 5', NULL, '89340', 'DE', 'München', NULL, 'coltinternationalgmb@example.com'),
  ('Comarch AG', 'Riesstraße 16', NULL, '80992', 'DE', 'Munich', NULL, 'rechnungen-caag@comarch.de'),
  ('Comgistics GmbH', 'Rothenbaumchaussee 40', NULL, '20148', 'DE', 'Hamburg', NULL, 'comgisticsgmbh@example.com'),
  ('Compass Europe s. r. o.', 'Poľná 4', NULL, '903 01', 'SK', 'Senec', '+421 911 903 955', 'hricovec@compasspools.eu'),
  ('Compass Pools Deutschland GmbH', 'Am Lehmhügel 7', NULL, '94530', 'DE', 'Auerbach', '+49 (0)9901 90307 0', 'info@compasspools.de'),
  ('Concorde Home Entertainment GmbH', 'Luise-Ullrich-Straße 6', NULL, '82031', 'DE', 'Grünwald', NULL, 'concordehomeentertai@example.com'),
  ('Condrobs e.V.', 'Berg-am-Laim-Straße 47', NULL, '81673', 'DE', 'München', NULL, 'condrobsev@example.com'),
  ('Confiserie Marie Louise GmbH', 'Wittestrasse 26e', NULL, '13509', 'DE', 'Berlin', NULL, 'confiseriemarielouis@example.com'),
  ('Consors Finanz BNP Paribas S.A. Niederlassung Deutschland', 'Schwanthalerstraße 31', NULL, '80336', 'DE', 'München', NULL, 'consorsfinanzbnppari@example.com'),
  ('Constantia Pirk GmbH & Co. KG', 'Pirkmühle 14-16', NULL, '92712', 'DE', 'Pirk', '+49 961 87 0', 'office.pirk@cflex.com'),
  ('Constantin Film Produktion GmbH', 'Feilitzschstraße 6', NULL, '80802', 'DE', 'München', NULL, 'constantinfilmproduk@example.com'),
  ('Continental Building Services GmbH', 'Martinskirchweg 18', NULL, '67346', 'DE', 'Speyer', NULL, 'continentalbuildings@example.com'),
  ('Copyright Promotions Licensing Group GmbH', 'Thalkirchner Straße 2', NULL, '80337', 'DE', 'Munich', NULL, 'copyrightpromotionsl@example.com'),
  ('Crosspolimeri AG Schweiz', 'Hauptstrasse 300', NULL, '5064', 'CH', 'Wittenau', NULL, 'crosspolimeriagschwe@example.com'),
  ('Czarnecki Artur', 'Baakenallee 8', NULL, '20457', 'DE', 'Hamburg', NULL, 'Artur.Czarnecki@rwe.com'),
  ('DB Netz AG', 'Elisabeth-Schwarzhaupt-Platz 1', NULL, '10115', 'DE', 'Berlin', NULL, 'dbnetzag@example.com'),
  ('DESA Construction GmbH', 'Grafenberger Allee 277-287', NULL, '40237', 'DE', 'Düsseldorf', NULL, 'desaconstructiongmbh@example.com'),
  ('DFB EURO GmbH', 'Otto-Fleck-Schneise 6', NULL, '60528', 'DE', 'Frankfurt am Main', NULL, 'dfbeurogmbh@example.com'),
  ('DHL Freight GMbH', 'Postfach 20 03 62', NULL, '53133', 'DE', 'Bonn', NULL, 'dhlfreightgmbh@example.com'),
  ('DHL Global Forwarding (UK) Limited', 'Eastworth House, Eastworth Road,', NULL, 'KT16 8SH', 'UK', 'Chertsey, Surrey.', NULL, 'dhlglobalforwardingu@example.com'),
  ('DHL Global Forwarding GmbH', 'Flughafenallee 11', NULL, '28199', 'DE', 'Bremen', NULL, 'dhlglobalforwardingg@example.com'),
  ('DLS Land und Seespeditionsgesellschaft mbH', 'Jacorbsrade 1', NULL, '22962', 'DE', 'Siek', NULL, 'dlslandundseespediti@example.com'),
  ('DOK Kindersuesswaren GmbH', 'Aspastraße 24', NULL, '59394', 'DE', 'Nordkirchen', NULL, 'dokkindersuesswareng@example.com'),
  ('DREWS Fuhrgeschäft', 'Buchholzstr. 59', NULL, '49377', 'DE', 'Vechta', NULL, 'drewsfuhrgeschft@example.com'),
  ('DSS 24 UG', 'Ludwig-Erhard-Str. 11', NULL, '85375', 'DE', 'Neufahrn', NULL, 'dss24ug@example.com'),
  ('DTL Ulus. Tas. ve Loj. Hiz. Dis Tic. Ltd. Sti.', 'UNIVERSITE MAH. KAMP SK. İLCAN SITESI NO:1 KAPI NO: 6', NULL, NULL, 'TR', 'Istanbul', NULL, 'dtlulustasvelojhizdi@example.com'),
  ('DYCKHOFF GmbH', 'Hauenhorster Straße 131', NULL, '48431', 'DE', 'Rheine', NULL, 'f.viets@dyckhoff24.de'),
  ('DYWIDAG Sp. z o.o.', 'ul. Gen. Hallera 78', NULL, '41-709', 'PL', 'Ruda Śląska', NULL, 'Witold.Kierczak@dywidag.com'),
  ('DYWIDAG Systems International GmbH', 'Neuhofweg 5', NULL, '85716', 'DE', 'Unterschleißheim', '+49-89-30 90 50-100', 'dsihv@dywidag.com'),
  ('DYWIDAG-Systems International B.V.', 'Veilingweg 2', NULL, '5301KM', 'NL', 'Zaltbommel', NULL, 'dywidagsystemsintern@example.com'),
  ('DYWIDAG-Systems International GmbH', 'Germanenstraße 8', NULL, '86343', 'DE', 'Königsbrunn', NULL, 'Joachim.Truetsch@dywidag.com'),
  ('Deniz Caliskan', 'Am Bleichbach 9', NULL, '85452', 'DE', 'Moosinning', NULL, 'denizcaliskan@example.com'),
  ('Deutsche Post AG', 'Franz-Zebisch-Str. 15', NULL, '92637', 'DE', 'Weiden', NULL, 'deutschepostag@example.com'),
  ('Deutsche Rettungsdiensthilfe e.V.', 'Baubergerstraße 61', NULL, '80992', 'DE', 'München', NULL, 'info@deutsche-rettungsdiensthilfe.de'),
  ('Dietz Kältetechnik GmbH & Co. KG', 'Steindamm 48', NULL, '28719', 'DE', 'Bremen', '0421 / 63 26 29', 'buchhaltung@dietz-kaelte.de'),
  ('Dipol GmbH', 'Dillenburger Weg 50', NULL, '40229', 'DE', 'Düsseldorf', NULL, 'dipolgmbh@example.com'),
  ('Direct-Route Sarl', '1, rue de Stockholm', NULL, '75008', 'FR', 'Paris', NULL, 'directroutesarl@example.com'),
  ('Dispo', 'Gewerbegebiet Ost 31', NULL, '92353', 'DE', 'Postbauer-Heng', NULL, 'dispo@ms-marine.de'),
  ('Dominic Laufenberg', 'Dorotheenstraße 12', NULL, '22301', 'DE', 'Hamburg', NULL, 'dominiclaufenberg@example.com'),
  ('Dr. Ingrid Th.Schwerzel-Schoer', 'Mauerkircherstraße 1/b', NULL, '81679', 'DE', 'München', NULL, 'dringridthschwerzels@example.com'),
  ('Dr. Ljubomir Petkov', 'Albert-Rosshaupter Str.67', NULL, '81369', 'DE', 'München', NULL, 'drljubomirpetkov@example.com');

-- Batch 4/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('DrGreen GmbH', 'Schnelldorf 64', NULL, '4975', 'AT', 'Suben', NULL, 'team@drgreen.at'),
  ('Drahtseilwerk GmbH', 'Auf der Bult 14 - 16', NULL, '27574', 'DE', 'Bremerhaven', NULL, 'drahtseilwerkgmbh@example.com'),
  ('Druckerei Vogl GmbH & Co.KG', 'Georg-Wimmer-Ring 9', NULL, '85604', 'DE', 'Zorneding', '+49 (0) 8106-23081-70', 'versand@druckerei-vogl.de'),
  ('Dunkermotoren GmbH', 'Allmendstr. 11', NULL, '79848', 'DE', 'Bonndorf/Schwarzwald', '+49 7703 930 - 0', 'info.dunkermotoren@ametek.com'),
  ('Duotec Medical GmbH', 'Dr.-Kurt-Huber-Str. 6', NULL, '82031', 'DE', 'Grünwald', NULL, 'duotecmedicalgmbh@example.com'),
  ('Dwuzet Fassadentechnik GmbH', 'Bredowstrasse 10', NULL, '22113', 'DE', 'Hamburg', NULL, 'dwuzetfassadentechni@example.com'),
  ('Düllberg Konzentra GmbH & Co. KG', 'Obenhauptstrasse 3', NULL, '22335', 'DE', 'Hamburg', NULL, 'dllbergkonzentragmbh@example.com'),
  ('E-proPLAST GmbH', 'An der Asbacher Str. 38', NULL, '98574', 'DE', 'Schmalkalden', NULL, 'eproplastgmbh@example.com'),
  ('ED-TRANS', '6 bis rue Deneb', NULL, '72230', 'FR', 'MONCE EN BELIN', NULL, 'edtrans@example.com'),
  ('EGLI AG Process Technology', 'Wilerstrasse 7', NULL, '9606', 'CH', 'Bütschwil', '+41 71 982 88 00', 'info@egliag.com'),
  ('ELH Waggonbau Niesky GmbH', 'Am Waggonbau 11', NULL, '2906', 'DE', 'Niesky', NULL, 'elhwaggonbaunieskygm@example.com'),
  ('ELOS Speditions GmbH - Projektspedition Berlin', 'Storkower Straße 113', NULL, '10407', 'DE', 'Berlin', NULL, 'elosspeditionsgmbhpr@example.com'),
  ('EM Golfplatz/Management GmbH', 'Renkenstr. 12', NULL, '82266', 'DE', 'Inning am Ammersee', NULL, 'emgolfplatzmanagemen@example.com'),
  ('EMEF-Energie', 'Hauptstraße 371', NULL, '53639', 'DE', 'Königswinter', '02223/7922070', 'info@emef-energie.de'),
  ('EMINIA TRADING GmbH', 'Gernotstrasse 16', NULL, '44319', 'DE', 'Dortmund', NULL, 'eminiatradinggmbh@example.com'),
  ('EMO-TRANS GmbH', 'Raiffeisenstr. 30', NULL, '70794', 'DE', 'Filderstadt', NULL, 'emotransgmbh@example.com'),
  ('EMO-TRANS GmbH', 'Huettruper Heide 88', NULL, '48268', 'DE', 'Greven', '+49 (0) 2571-916616', 'info@emo.de'),
  ('ENEOP 3', 'Avenida Cabo Verde No 36', NULL, '4900-568', 'PT', 'Viana do Castelo', NULL, 'eneop3@example.com'),
  ('ENERCON GMBH', 'Via Carlo Veneziani N 58', NULL, '148', 'IT', 'Roma RM', NULL, 'enercongmbh@example.com'),
  ('ENERCON GmbH Greek Branch', '49A L. Doukissis Plakentias', NULL, '152 34', 'GR', 'Chalandri-Athens', '+30 210 683 84 90', 'enercongmbhgreekbran@example.com'),
  ('ENERCON GmbH Sucursal PT', 'Avenida de Cabo Verde 36', NULL, '4900-568', 'PT', 'Viana do Castelo', NULL, 'enercongmbhsucursalp@example.com'),
  ('ENERCON Logistic GmbH', 'Holzweg 87', NULL, '26605', 'DE', 'Aurich', '+49 49 41 927-0', 'info@enercon.de'),
  ('ENERCON WindEnergy Pvt.Ltd.', 'Bellary Road', NULL, '560092', 'IN', 'Bengaluru', NULL, 'enerconwindenergypvt@example.com'),
  ('ERFURT & Sohn KG', 'Hugo-Erfurt-Straße 1', NULL, '42399', 'DE', 'Wuppertal', '+49 202 6110 353', 'G.Ensabella@erfurt.com'),
  ('EURO-Masten GmbH', 'Spenglerstraße 89', NULL, '23556', 'DE', 'Lübeck', '0451 79 10 75', 'k.zielke@euromasten.de'),
  ('EVG Edelstahlvertriebsgesellschaft mbH', 'Otto-Stoelcker-Str. 37', NULL, '35066', 'DE', 'Frankenberg', NULL, 'evgedelstahlvertrieb@example.com'),
  ('Eesti Kultuuriministeerium', 'Suur-Karja 23', NULL, '10148', 'EE', 'Tallinn', NULL, 'eestikultuuriministe@example.com'),
  ('Elis München GmbH', 'Stahlgruberring 19', NULL, '81829', 'DE', 'München', NULL, 'elismnchengmbh@example.com'),
  ('Elke Höver - Höver-Papertrade', 'Bleckering 14', NULL, '22119', 'DE', 'Hamburg', NULL, 'elkehverhverpapertra@example.com'),
  ('Eltrans Plus GmbH', 'Manteuffelstrasse 21', NULL, '22587', 'DE', 'Hamburg', NULL, 'eltransplusgmbh@example.com'),
  ('Emerson', 'Heisenbergbogen 2', NULL, '85609', 'DE', 'Aschheim', '089 21547800', 'emerson@example.com'),
  ('Emil Frey Exklusive Cars GmbH', 'Moosacher Straße 56', NULL, '80809', 'DE', 'München', NULL, 'emilfreyexklusivecar@example.com'),
  ('Emons Spedition GmbH & Co. KG', 'Lindberghstraße 6', NULL, '85399', 'DE', 'Hallbergmoos', NULL, 'emonsspeditiongmbhco@example.com'),
  ('Emsdettener Eisenhandlung GmbH', 'Wilmersstraße 34', NULL, '48282', 'DE', 'Emsdetten', NULL, 'emsdettenereisenhand@example.com'),
  ('Enercon GmbH', 'Dreekamp 5', NULL, '26605', 'DE', 'Aurich', NULL, 'thomas.endelmann@enercon.de'),
  ('Engelmann Turf Care GmbH', 'Keltenring 11', NULL, '82041', 'DE', 'Oberhaching', NULL, 'engelmannturfcaregmb@example.com'),
  ('Erdem Aktar Transporte', 'Kysostr. 1', NULL, '85301', 'DE', 'Schweitenkirchen', NULL, 'erdemaktartransporte@example.com'),
  ('Erich Czulkowski GmbH', 'Kreuzerwiese 3', NULL, '56290', 'DE', 'Dommershausen', NULL, 'erichczulkowskigmbh@example.com'),
  ('Erich Czulkowski GmbH Zweigniederlassung Düsseldorf', 'Henkelstraße 67', NULL, '40589', 'DE', 'Düsseldorf', NULL, 'erichczulkowskigmbhz@example.com'),
  ('Ernst Weinzierl', 'Brückenstr.5', NULL, '84137', 'DE', 'Vilsbiburg', NULL, 'ernstweinzierl@example.com'),
  ('Essendorfer Genussschmelzerei GmbH', 'Bayrischzeller Straße 11', NULL, '83727', 'DE', 'Schliersee', NULL, 'essendorfergenusssch@example.com'),
  ('EuTech Europa Technology', 'An der Riede 5', NULL, '38110', 'DE', 'Braunschweig', NULL, 'eutecheuropatechnolo@example.com'),
  ('Exponex s.r.o.', 'Janou?kova 2015/1a', NULL, '613 00', 'CZ', 'Brno ? ?erná Pole', NULL, 'exponexsro@example.com'),
  ('Express Group, a.s.', 'Plynárenská 7/B', NULL, '82109', 'SK', 'Bratislava', NULL, 'expressgroupas@example.com'),
  ('F.H. Bertling Logistics Aberdeen Ltd.', 'Ground Floor, 166 College Road', NULL, 'HA1 1BH', 'UK', 'Harrow, Middlesex', NULL, 'fhbertlinglogisticsa@example.com'),
  ('F.H. Bertling Logistics Georgia LLC', 'Room 4, 8th Floor, Green Office, 154 Agmashenebeli Avenue', NULL, '112', 'GE', 'Tbilisi', NULL, 'fhbertlinglogisticsg@example.com'),
  ('FAME Logistics & Trade GmbH', 'Gebrüder-Wright-Str. 4', NULL, '60486', 'DE', 'Frankfurt am Main', NULL, 'famelogisticstradegm@example.com'),
  ('FLIESEN MAUZ GMBH', 'Dekan-Laist-Str. 48', NULL, '55129', 'DE', 'Mainz', NULL, 'fliesenmauzgmbh@example.com'),
  ('FMCG Nederland B.V.', 'Maasstraat 24', NULL, '6049', 'NL', 'CC Herten', NULL, 'fmcgnederlandbv@example.com'),
  ('FREO Financial & Real Estate Operations GmbH', 'Jungfernturmstrasse 2', NULL, '80333', 'DE', 'München', NULL, 'freofinancialrealest@example.com');

-- Batch 5/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('FSO GmbH & Co.KG', 'Friedrich-Wöhler-Str. 8', NULL, '64579', 'DE', 'Gernsheim', NULL, 'fsogmbhcokg@example.com'),
  ('FUCHS Bau GmbH', 'Dorstener Straße 1', NULL, '9661', 'DE', 'Hainichen', NULL, 'fuchsbaugmbh@example.com'),
  ('Fagioli S.p.A.', 'Via Ferraris 13', NULL, '42049', 'IT', 'S. Ilario D''Enza (RE)', NULL, 'fagiolispa@example.com'),
  ('Fantastiqu Trade GmbH', 'Hagenmüllergasse 22/35', NULL, '1030', 'AT', 'Wien', NULL, 'fantastiqutradegmbh@example.com'),
  ('Fast truck solution UG (haftungsbeschränkt)', 'Langer Kornweg 34 D', NULL, '65451', 'DE', 'Kelsterbach', NULL, 'fasttrucksolutionugh@example.com'),
  ('Fast''n Easy GmbH', 'Am Sommerfeld 1', NULL, '85646', 'DE', 'Anzing', NULL, 'fastneasygmbh@example.com'),
  ('Ferntrans internationale Speditions-GmbH', 'Frankenwaldstr. 27 ? 29', NULL, '95152', 'DE', 'Selbitz', '+49 9280 98 300', 'info@spedition-ferntrans.de'),
  ('Filgertshofer Alois', 'Marktstraße 55', NULL, '83646', 'DE', 'Bad Tölz', '+49 172 72 31 31 6', 'Alois.Filgertshofer@fimax.de'),
  ('Finow Rohrsysteme GmbH', 'Angermünder str. 101', NULL, '16225', 'DE', 'Eberswalde', NULL, 'finowrohrsystemegmbh@example.com'),
  ('Florian Haller - Pawpawschule', 'Mühlweg 6', NULL, '82544', 'DE', 'Egling', NULL, 'florianhallerpawpaws@example.com'),
  ('Formlos GmbH', 'Siebengebirgsallee 188', NULL, '50939', 'DE', 'Köln', NULL, 'wachsmann@formlos.com'),
  ('Formteilbau Schmitt GmbH & Co. KG', 'Schönauer Weg 20', NULL, '97783', 'DE', 'Karsbach', NULL, 'formteilbauschmittgm@example.com'),
  ('Forstner Glass+ GmbH', 'Franz-Kollmann-Str. 4', NULL, '33000', 'AT', 'Amstetten', NULL, 'forstnerglassgmbh@example.com'),
  ('Frank Vermögensverwaltungsgesellschaft mbH', 'Kurfürstendamm 124', NULL, '10711', 'DE', 'Berlin', NULL, 'frankvermgensverwalt@example.com'),
  ('Franka Emika GmbH', 'Frei-Otto-Straße 20', NULL, '80797', 'DE', 'München', NULL, 'frankaemikagmbh@example.com'),
  ('Fraunhofer IWES', 'Am Seedeich 45', NULL, '27572', 'DE', 'Bremerhaven', NULL, 'fraunhoferiwes@example.com'),
  ('Freiburger Hochbau Nord GmbH', 'Berta-Ottenstein-Straße 11', NULL, '79106', 'DE', 'Freiburg im Breisgau', NULL, 'freiburgerhochbaunor@example.com'),
  ('Friedrich Köster GmbH & Co. KG Maschinenfabrik + Gießerei', 'Friedrichswerk 1 - 7', NULL, '25746', 'DE', 'Heide', '0481-797 225', 'friedrichkstergmbhco@example.com'),
  ('Fructus sp. z o.o', 'Maszewska 15', NULL, '72-100', 'PL', 'Goleniów', NULL, 'fructusspzoo@example.com'),
  ('Fürmetz Logistik GmbH', 'Kirchlern 4', NULL, '84416', 'DE', 'Taufkirchen (Vils)', NULL, 'frmetzlogistikgmbh@example.com'),
  ('G. Eichenwald GmbH & Co. KG', 'Ruhrstraße 60', NULL, '41469', 'DE', 'Neuss', '02137 / 91787-0', 'ideal@eichenwald.de'),
  ('GARDA METAL WORKS POLSKA Sp. z o.o.', 'ulica Miedziana 16B', NULL, '59-100', 'PL', 'Polkowice', NULL, 'gardametalworkspolsk@example.com'),
  ('GBM GLEISSBAUMECHANIK BRANDENBURG/H.', 'Adlerstraße 2', NULL, '14774', 'DE', 'Brandenburg an der Havel', '+49033818044110', 'gbmgleissbaumechanik@example.com'),
  ('GEBAS GmbH', 'Glescher Straße 126', NULL, '50126', 'DE', 'Bergheim', NULL, 'gebasgmbh@example.com'),
  ('GEODIS CL Germany GmbH', 'Colmarer Str. 11', NULL, '60528', 'DE', 'Frankfurt am Main', '+49 6106 2680 5310', 'rechnungseingang1-glde@geodis.com'),
  ('GHH Fahrzeuge GmbH', 'Emscherstr. 53', NULL, '45891', 'DE', 'Gelsenkirchen', NULL, 'ghhfahrzeugegmbh@example.com'),
  ('GKDS', 'Hansastraße 12-16', NULL, '80686', 'DE', 'München', NULL, 'gkds@example.com'),
  ('GKM Services GmbH', 'Felix Wankel Str. 11', NULL, '74915', 'DE', 'Waibstadt', '+49 (7263) 40972-0', 'info@gkm-group.com'),
  ('GKM Siebtechnik GmbH', 'Felix Wankel Straße 11', NULL, '74915', 'DE', 'Waibstadt', '+49 (7263) 40972-0', 'info@gkm-group.com'),
  ('GLEAM Technologies GmbH', 'Markhofgasse 19/1.OG', NULL, '1030', 'AT', 'Wien', NULL, 'gleamtechnologiesgmb@example.com'),
  ('GNS Georgia LTD.', '12 Merab Aleksidze Street, 6th Floor', NULL, '171', 'GE', 'Tbilisi', NULL, 'gnsgeorgialtd@example.com'),
  ('GOLDBECK Süd GmbH', 'Anna-Sigmund-Straße 2-4', NULL, '82061', 'DE', 'Neuried', NULL, 'goldbecksdgmbh@example.com'),
  ('GOP Entertainment Group GmbH & Co. KG', 'Im Kurgarten 8', NULL, '32545', 'DE', 'Bad Oeynhausen', NULL, 'gopentertainmentgrou@example.com'),
  ('GOP Showconcept GmbH & Co. KG', 'Georgstraße 36', NULL, '30159', 'DE', 'Hannover', '+ 49 (0) 521 3299 250', 'info@variete.de'),
  ('GTH Green-Stores Handels UG & Co. KG', 'Thyssenstraße 6', NULL, '32312', 'DE', 'Lübbecke', NULL, 'gthgreenstoreshandel@example.com'),
  ('Gallafilz GmbH', 'Residenzstraße 27', NULL, '80333', 'DE', 'München', NULL, 'gallafilzgmbh@example.com'),
  ('Gebert & Gebert Sanitär und Heizungsbau GmbH', 'Josefsstrasse 2', NULL, '51789', 'DE', 'Lindlar', NULL, 'gebertgebertsanitrun@example.com'),
  ('Gebrüder Schneller GmbH & Co. KG', 'Im Kreuz 11', NULL, '97076', 'DE', 'Würzburg', '+49 931 27988-11', 'B.Zimmer@gebrueder-schneller.de'),
  ('Geis Air + Sea GmbH', 'Mattentwiete 8', NULL, '20457', 'DE', 'Hamburg', NULL, 'geisairseagmbh@example.com'),
  ('Gemeinde Eichenau', 'Hauptplatz 2', NULL, '82223', 'DE', 'Eichenau', NULL, 'gemeindeeichenau@example.com'),
  ('Generator Produkcja Opole Sp.z.o.o', 'ul. O?wi?cimska 102E', NULL, '45641', 'PL', 'Opole', NULL, 'generatorprodukcjaop@example.com'),
  ('Gerish GmbH', 'Konstantinstraße 16', NULL, '41238', 'DE', 'Mönchengladbach', NULL, 'gerishgmbh@example.com'),
  ('Gertzen Transportlogistik GmbH & Co.KG', 'Pollertstraße 44', NULL, '26892', 'DE', 'Kluse / Ahlen', NULL, 'gertzentransportlogi@example.com'),
  ('Gharieni Group GmbH', 'Am Schürmannshütt 24', NULL, '47441', 'DE', 'Moers', '+49 (0) 2841 – 88 300-50', 'info@gharieni.com'),
  ('Gianti logistics LTD', 'Gulia Square 4/2', NULL, '114', 'GE', 'Tbilisi', NULL, 'giantilogisticsltd@example.com'),
  ('Glaß & Wolff Metalltechnik GmbH & Co. KG', 'Böttcherstraße 4', NULL, '27404', 'DE', 'Zeven', NULL, 'e.ehmke@glass-wolff.de'),
  ('Global Treats GmbH', 'St.-Antonius-Straße 1', NULL, '79793', 'DE', 'Wutöschingen', NULL, 'info@vernaschediewelt.com'),
  ('Globalsped GmbH', 'Pendelhagen 1', NULL, '83416', 'DE', 'Saaldorf-Surheim', NULL, 'globalspedgmbh@example.com'),
  ('Gorges tent...event GmbH & Co. KG', 'Eifelstrasse 34', NULL, '56759', 'DE', 'Laubach', NULL, 'gorgestenteventgmbhc@example.com'),
  ('Gorilla Deutschland GmbH', 'Sauerlacher Straße 54A', NULL, '82515', 'DE', 'Wolfratshausen', NULL, 'tasso@letsgogorilla.de');

-- Batch 6/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Granar GmbH', 'Lindenallee 25a', NULL, '42899', 'DE', 'Remscheid', '02191 460 56 60', 'info@granar.de'),
  ('Green City e. V.', 'Lindwurmstr. 88', NULL, '80337', 'DE', 'München', NULL, 'greencityev@example.com'),
  ('Greenwood Group Ltd - Greenwood Nursery', 'Church Road, Aldingbourne', NULL, 'PO2 3TU', 'UK', 'Chichester', NULL, 'greenwoodgroupltdgre@example.com'),
  ('GridParity AG', 'Ohmstr. 7', NULL, '85757', 'DE', 'Karlsfeld', NULL, 'gridparityag@example.com'),
  ('Güray Karabacak Sicherheit und Service', 'Melchiorstr. 48', NULL, '81479', 'DE', 'München', NULL, 'graykarabacaksicherh@example.com'),
  ('Güttler Logistik GmbH', 'Dieselstraße 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'herbert.brunner@guettlerlogistik.de'),
  ('Güttler Logistik GmbH', 'Fuhrmannstraße 8', NULL, '95013', 'DE', 'Hof/Saale', NULL, 'gttlerlogistikgmbh@example.com'),
  ('HAROSYSTEM, Inh. Samy Hadj Amor', 'Röntgenstraße 8', NULL, '40699', 'DE', 'Erkrath', NULL, 'info@haro-system.com'),
  ('HAUBNER Systembau GmbH', 'Am Kornfeld 5', NULL, '92318', 'DE', 'Neumarkt in der Oberpfalz', NULL, 'haubnersystembaugmbh@example.com'),
  ('HBB Centermanagement GmbH & Co. KG', 'Theresienhöhe 5', NULL, '80339', 'DE', 'München', NULL, 'hbbcentermanagementg@example.com'),
  ('HBB Gewerbebau Projektgesellschaft Forum Hanau mbH & Co. KG', 'Brooktorkai 22', NULL, '20457', 'DE', 'Hamburg', '+49 (6181) 91 95 7 23', 'invoice@hbb.de'),
  ('HL HAMBURGER LEISTUNGSFUTTER GmbH', 'Konsul-Ritter-Str. 3', NULL, '21079', 'DE', 'Hamburg', '+49 (0)40/76692-0', 'allgemein@ibeka.com'),
  ('HPF Energy Services', '3 Kinwarton Farm Road, Arden Forest Industrial Estate, Alcester', NULL, 'B49 6EH', 'UK', 'Warwickshire', NULL, 'hpfenergyservices@example.com'),
  ('Haka Trans Spedition und Handels GmbH', 'Dieselstrasse 21', NULL, '85748', 'DE', 'Garching bei München', NULL, 'hakatransspeditionun@example.com'),
  ('Hamm AG', 'Hammstr. 1', NULL, '95643', 'DE', 'Tirschenreuth', '+49 9631 800', 'info@hamm.eu'),
  ('Hans-Jürgen Müller', 'Lecherwiese 10', NULL, '83620', 'DE', 'Feldkirchen-Westerham', NULL, 'hansjrgenmller@example.com'),
  ('Harsco Rail Europe GMBH', 'Lütticher Straße 130', NULL, '40547', 'DE', 'Dusseldorf', NULL, 'harscoraileuropegmbh@example.com'),
  ('Hasslacher Drauland Holzindustrie GmbH', 'Feistritz 1', NULL, '9751', 'AT', 'Sachsenburg', '+43 4769 22 49 - 0', 'info@hasslacher.com'),
  ('Hatice Schmidt GmbH', 'Schönstedtstraße 7', NULL, '12043', 'DE', 'Berlin', NULL, 'haticeschmidtgmbh@example.com'),
  ('Haubner Holding GmbH', 'Am Kornfeld 5', NULL, '92318', 'DE', 'Neumarkt in der Oberpfalz', NULL, 'haubnerholdinggmbh@example.com'),
  ('Haus Flammberg Seniorenresidenz GmbH', 'Karolinenstraße 1-3', NULL, '59759', 'DE', 'Arnsberg', '+49 (0) 2932/484-3114', 'hausflammbergseniore@example.com'),
  ('Haus Linde Senioren- und Pflegeheim GmbH', 'Heinrich-Steinweg-Straße 17', NULL, '38685', 'DE', 'Langelsheim', NULL, 'hauslindeseniorenund@example.com'),
  ('HeGo Biotec GmbH', 'Goerzallee 305 b', NULL, '14167', 'DE', 'Berlin', NULL, 'hegobiotecgmbh@example.com'),
  ('Heathrow Express', 'The Compass Centre, Nelson Road', NULL, 'TW6 2GW', 'UK', 'Hounslow, Middlesex.', NULL, 'heathrowexpress@example.com'),
  ('Hegelmann Transporte Sp. z o.o.', 'Kucelinska 22', NULL, '42-200', 'PL', 'Czestochowa', NULL, 'hegelmanntransportes@example.com'),
  ('Heimatlicht GmbH & Co. KG', 'Seiboldsdorfer Mühle 9', NULL, '83278', 'DE', 'Traunstein', NULL, 'heimatlichtgmbhcokg@example.com'),
  ('Heinrich Glaeser Nachf. GmbH', 'Blaubeurer Str. 263', NULL, '89081', 'DE', 'Ulm', NULL, 'heinrichglaesernachf@example.com'),
  ('Heinrich Salm KG', 'Printzstraße 5', NULL, '76139', 'DE', 'Karlsruhe', NULL, 'Poersel@salm-karlsruhe.de'),
  ('Heizomat GmbH', 'Maicha 21', NULL, '91710', 'DE', 'Gunzenhausen', NULL, 'heizomatgmbh@example.com'),
  ('Heldenstern*UG', 'Herrengut 15', NULL, '76530', 'DE', 'Baden-Baden', NULL, 'heldensternug@example.com'),
  ('Hellmann Worldwide Logistics Road & Rail GmbH & Co. KG', 'Ludwig- Erhard- Strasse 7', NULL, '28197', 'DE', 'Bremen', NULL, 'hellmannworldwidelog@example.com'),
  ('Helmut Müller GmbH | Internationale Spedition', 'Adam-Geisler-Str. 1', NULL, '82140', 'DE', 'Olching', NULL, 'helmutmllergmbhinter@example.com'),
  ('Henan Aotie International Freight Forwarding Co.,Ltd.', 'Room 2012, Expo Center, 28 Dongfeng Road, Jinshui District,', NULL, NULL, 'CN', 'City ,Henan Province,China', NULL, 'henanaotieinternatio@example.com'),
  ('Henke Marc', 'Dessauerstr. 60', NULL, '45472', 'DE', 'Mülheim an der Ruhr', NULL, 'Marc.Henke@pet-logistics.com'),
  ('Hesse GmbH & Co. KG', 'Warendorfer Str. 21', NULL, '59075', 'DE', 'Hamm', NULL, 'hessegmbhcokg@example.com'),
  ('Hessischer Leichtathletik-Verband', 'Otto-Fleck-Schneise 4', NULL, '60528', 'DE', 'Frankfurt am Main', NULL, 'hessischerleichtathl@example.com'),
  ('Het beste van de Kweker', 'Lange Broekweg', NULL, '2671DT', 'NL', 'Naaldwijk', NULL, 'hetbestevandekweker@example.com'),
  ('Hierl & Müller', 'Gustav-Hertz-Str. 10', NULL, '94315', 'DE', 'Straubing', NULL, 'hierlmller@example.com'),
  ('Highleigh Nurseries', 'Highleigh Road, Sidlesham,', NULL, 'PO20 7NR', 'UK', 'Chichester, West Sussex', NULL, 'highleighnurseries@example.com'),
  ('Hoever-Papertrade UG (haftungsbeschränkt)', 'Bleckering 14', NULL, '22119', 'DE', 'Hamburg', NULL, 'hoeverpapertradeugha@example.com'),
  ('Hope Tree International GmbH', 'Ostergartenstr. 10', NULL, '82538', 'DE', 'Geretsried', NULL, 'hopetreeinternationa@example.com'),
  ('Hubert Plenter GmbH', 'Amelunxenstaße 1', NULL, '48167', 'DE', 'Münster', NULL, 'hubertplentergmbh@example.com'),
  ('I.Q.Courier e.K.', 'Carl-Zeiss-Ring 15a', NULL, '85737', 'DE', 'Ismaning', NULL, 'iqcourierek@example.com'),
  ('IEM GmbH', 'Sreitelsfingerstraße 45E', NULL, '88131', 'DE', 'Lindau', '+49 (0) 151232 09767', 'iemgmbh@example.com'),
  ('IIC AG', 'Breisacher Strasse 86', NULL, '79110', 'DE', 'Freiburg im Breisgau', NULL, 'iicag@example.com'),
  ('IKAU INVEST s.r.o.', 'Rehorova 1004/32', NULL, 'CZ', 'CZ', 'Praha 3', NULL, 'ikauinvestsro@example.com'),
  ('IKRA UK Limited', 'Mulberry Way, Belvedere', NULL, 'DA17 6AN', 'UK', 'Kent', NULL, 'ikrauklimited@example.com'),
  ('IMEDCO AG', 'Industriestrasse West 14', NULL, '4614', 'CH', 'Hägendorf', '+41 62 209 40 20', 'imedcoag@example.com'),
  ('IMF Modell- u. Formenbau Illertal GmbH', 'Gassenäcker 45', NULL, '89195', 'DE', 'Staig', NULL, 'imfmodelluformenbaui@example.com'),
  ('INOTEC GmbH', 'Dieselstraße 1', NULL, '72770', 'DE', 'Reutlingen', NULL, 'inotecgmbh@example.com');

-- Batch 7/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('INOX Schleiftechnik GmbH & Co. KG', 'Otto-Stoelcker-Str. 31', NULL, '35066', 'DE', 'Frankenberg', '06451 210060', 'info@inox-schleiftechnik.de'),
  ('INTER-PAPIER Handelsgesellschaft mbH', 'Friedenstraße 2', NULL, '25421', 'DE', 'Pinneberg', NULL, 'interpapierhandelsge@example.com'),
  ('INTERMODAL SOLUTIONS LTD', 'Sredets area, street Lyuben Karavelov, bl 28, ap. 7', NULL, NULL, 'BG', 'Sofia', NULL, 'intermodalsolutionsl@example.com'),
  ('IPS – Intelligente Prozesslösungen GmbH', 'Dr.-Gustav-Adolph-Str. 2', NULL, '82049', 'DE', 'Pullach', '+49 89 4161 4885-0', 'info@ips-energy.com'),
  ('IVECO Poland SP. Z.O.O', 'Al. Wyscigowa', NULL, '2681', 'PL', 'Warsawa', NULL, 'ivecopolandspzoo@example.com'),
  ('IVECO SPA', 'Via Puglia 35', NULL, '10156', 'IT', 'Torino (TO)', NULL, 'ivecospa@example.com'),
  ('InXpress Bonn', 'Merianstraße 43', NULL, '53177', 'DE', 'Bonn', '+49 (0)228 5349 438', 'inxpressbonn@example.com'),
  ('InXpress Frankfurt', 'Niedernhausener Straße 53', NULL, '60326', 'DE', 'Frankfurt am Main', NULL, 'inxpressfrankfurt@example.com'),
  ('InXpress Lindau/Kempten', 'Ellgasser Straße 9c', NULL, '88161', 'DE', 'Lindenberg im Allgäu', '+49 (0)8383 92 96 055', 'info.nusser@inxpress.com'),
  ('InXpress München', 'Schwanseestr. 71b', NULL, '81549', 'DE', 'München', NULL, 'serdar.buyar@inxpress.com'),
  ('InXpress Riviera', '10 Avenue du Docteur Fabre', NULL, '6160', 'FR', 'Juan Les Pins', NULL, 'inxpressriviera@example.com'),
  ('Indeed Ireland Opetations Ltd', '80 Sir John Rogersom´s Quay, Gran canal Dock, Block B, Capital Dock', NULL, NULL, 'IE', 'Dublin DO2 HE36', NULL, 'indeedirelandopetati@example.com'),
  ('Infraserv Vakuumservice GmbH', 'Gleiwitzer Straße 8', NULL, '85386', 'DE', 'Eching', NULL, 'wieland@infraservgmbh.com'),
  ('Ingenieurbüro RT', 'Auguste-Wittig-Str. 10', NULL, '83646', 'DE', 'Bad Tölz', NULL, 'ingenieurbrort@example.com'),
  ('Innotech GmbH', 'Lengloher Strasse 8', NULL, '83342', 'DE', 'Tacherting', NULL, 'innotechgmbh@example.com'),
  ('InternationalSpeedTransport Marta Kujda', 'Wojska Polskiego 25', NULL, 'PL69110', 'PL', 'Rzepin', NULL, 'internationalspeedtr@example.com'),
  ('Interteam Speditionsgesellschaft mbH', 'Kattjahren 8', NULL, '22359', 'DE', 'Hamburg', NULL, 'interteamspeditionsg@example.com'),
  ('Inxpress Freiburg', 'Breisgaustr. 18', NULL, '79312', 'DE', 'Emmerdingen', NULL, 'inxpressfreiburg@example.com'),
  ('Inxpress Germany GmbH', 'Curiestrasse 11', NULL, '55129', 'DE', 'Mainz', NULL, 'klaus-dieter.krost@inxpress.com'),
  ('Iveco Deutschland AG', 'Nicolaus-Otto-Straße 27', NULL, '89079', 'DE', 'Ulm', '+49 89 31771 0', 'ivecodeutschlandag@example.com'),
  ('Iveco France SAS', 'Rue Des Combats Du 24 Aout 44', NULL, '69200', 'FR', 'Venissieux', NULL, 'ivecofrancesas@example.com'),
  ('Iveco Schouten Almkerk', 'Postbus 61', NULL, '4286ZH', 'NL', 'Almkerk', NULL, 'eric.simons@ivecogroup.com'),
  ('J. DAHMEN & CO. KG, SOLINGEN', 'Dellenfeld 35', NULL, '42653', 'DE', 'Solingen', NULL, 'jdahmencokgsolingen@example.com'),
  ('J.B. Metal Vision GmbH', 'Dernekamp 74', NULL, '48249', 'DE', 'Dülmen', '+49 (0) 2594 – 78310', 'info@metalvision.de'),
  ('JELL GmbH & Co. KG', 'Am Anger 38', NULL, '83233', 'DE', 'Bernau am Chiemsee', NULL, 'jellgmbhcokg@example.com'),
  ('JIT Sp. z o.o.', 'Karmazynowa 32 K,', NULL, '02-887', 'PL', 'Warszawa', NULL, 'jitspzoo@example.com'),
  ('Jerzy Kakolewski Transport Miedzynarodowy Krajowy i Spediycja', 'ul. Podgorna 15 (DEBNO)', NULL, '62-060', 'PL', 'Stęszew', '+48 618 134 436', 'jkakolewski@wp.pl'),
  ('Johannes Michael Koch', 'Rudolf-Breitscheid-Str. 27', NULL, '90762', 'DE', 'Fürth', NULL, 'johannesmichaelkoch@example.com'),
  ('Jorns AG', 'Kirchgasse 12', NULL, '4932', 'CH', 'Lotzwil', '+41 62 919 80 50', 'jornsag@example.com'),
  ('Josef Wiegand GmbH & Co. KG', 'Landstraße 12', NULL, '36169', 'DE', 'Rasdorf', NULL, 'josefwiegandgmbhcokg@example.com'),
  ('Jörg Schwab Transport', 'Kreuzkirchstrasse 14', NULL, '93437', 'DE', 'Furth im Wald', NULL, 'jrgschwabtransport@example.com'),
  ('KAISER Process and Belt Technology GmbH / Member of the KICK Group', 'Siemensring 54 ? 56', NULL, '47877', 'DE', 'Willich', '+49 (0) 2154 89107 - 0', 'info@kaiser-pbt.de'),
  ('KAYAK SP. Z O.O.', 'UL. LEDÓCHOWSKIEGO 34', NULL, '63-400', 'PL', 'OSTRÓW WIELKOPOLSKI', NULL, 'kayakspzoo@example.com'),
  ('KLAFS GmbH', 'Erich-Klafs-Straße 3', NULL, '74523', 'DE', 'Schwäbisch Hall', NULL, 'klafsgmbh@example.com'),
  ('KNS Internationale Speditions GmbH', 'Liebigstrasse 2 - 20', NULL, '22113', 'DE', 'Hamburg', NULL, 'knsinternationalespe@example.com'),
  ('KS Tools Werkzeuge-Maschinen GmbH', 'Seligenstädter Grund 10-12', NULL, '63150', 'DE', 'Heusenstamm', '+49 6104 4974 11', 'kstoolswerkzeugemasc@example.com'),
  ('KST Georg Triebel', 'Zeithstraße 70A', NULL, '53819', 'DE', 'Neunkirchen-Seelscheid', NULL, 'kstgeorgtriebel@example.com'),
  ('Kajana Ltd.', 'Aphrodite 21', NULL, '8577', 'CY', 'Tala, Paphos, Cyprus', '01719122036', 'kai@kajana.eu'),
  ('Karl Pedross S.p.A.', 'Zona Industriale 1/c', NULL, '39021', 'IT', 'Laces (BZ)', NULL, 'karlpedrossspa@example.com'),
  ('Kassen- und Waagencenter Wägesystem WSM GmbH', 'Friedenstr. 18', NULL, '81671', 'DE', 'München', '089 450624-0', 'technik@wsm-gmbh.com'),
  ('Keco Module GmbH', 'Bruchstraße 8', NULL, '55263', 'DE', 'Ingelheim am Rhein', '(0176) 245 982 36', 'frachten@keco-module.de'),
  ('Keil Transport- und Logistik GmbH', 'Nikolaistr. 16', NULL, '30159', 'DE', 'Hannover', '+491633111260', 'keil.w@arcor.de'),
  ('Kempf & Seifried GmbH', 'Talweg 10', NULL, '72505', 'DE', 'Krauchenwies-Göggingen', NULL, 'seifried@kempf-seifried.de'),
  ('Kiesel Used GmbH', 'Baindter Straße 21', NULL, '88255', 'DE', 'Baienfurt', '49 751 50 04 859', 'h.denzel@kiesel.net'),
  ('Kirtur Turizm Insaat Taahhüt Elektrik San. Tic. Ltd. STİ', 'Bulgurlu mah. Alemdag cad. no: 60', 'Masaldan is merkezi E Blok, No: 4 Camlıca,', NULL, 'TR', 'Istanbul', '902164126010', 'info@kirtur.comtr'),
  ('Klöpfer Holzhandel GmbH & Co. KG', 'Schleißheimer Straße 104', NULL, '85748', 'DE', 'Garching bei München', NULL, 'klpferholzhandelgmbh@example.com'),
  ('Kometer Grabmale Steinmetzbetrieb', 'Georg-Meisenbach-Str. 4', NULL, '81549', 'DE', 'München', NULL, 'kometergrabmalestein@example.com'),
  ('Kraftwerk Living Technologies', 'Maria-Theresia-Strasse 49', NULL, '4600', 'AT', 'Wels', NULL, 'kraftwerklivingtechn@example.com'),
  ('Krakau & Söhne Gewürze GmbH', 'Thüringerstraße 43', NULL, '46286', 'DE', 'Dorsten', NULL, 'b.raedel@krakau-gewuerze.de'),
  ('Krones AG', 'Böhmerwaldstraße 5', NULL, '93073', 'DE', 'Neutraubling', NULL, 'kronesag@example.com');

-- Batch 8/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Ktec-Service GmbH', 'Am Gewerbepark 12', NULL, '9431', 'AT', 'St. Stefan im Lavanttal', '+43 (0) 676 – 897 153 300', 'spareparts@ktec-service.at'),
  ('Kuehne + Nagel Ltd', 'Unit 1 , Heathrow South Cargo Centre', NULL, 'TW14 0PH', 'UK', 'Girling Way, Feltham', NULL, 'kuehnenagelltd@example.com'),
  ('Kugler Feinkost GmbH', 'Taxetstraße 5', NULL, '85599', 'DE', 'Vaterstetten', NULL, 'kuglerfeinkostgmbh@example.com'),
  ('KÜHNE+NAGEL (AG & Co.) KG', 'Hansastraße 10', NULL, '35708', 'DE', 'Haiger', NULL, 'khnenagelagcokg@example.com'),
  ('L.I.T. Air & Sea GmbH', 'Franz-Stickan-Straße 4', NULL, '28197', 'DE', 'Bremen', NULL, 'speed@lit.de'),
  ('L.I.T. Speed GmbH', 'Mottmannstraße 1-3', NULL, '53842', 'DE', 'Troisdorf', '+49 4401920303', 'speed@lit.de'),
  ('LB-Olympia GmbH', 'Rasmussengasse 4', NULL, '1210', 'AT', 'Wien', NULL, 'lbolympiagmbh@example.com'),
  ('LEWA Attendorn GmbH', 'Am Wassertor 5', NULL, '57439', 'DE', 'Attendorn', NULL, 'lewaattendorngmbh@example.com'),
  ('LGL Haushaltswaren GmbH', 'Helferner Weg 14b', NULL, '49214', 'DE', 'Bad Rothenfelde', NULL, 'rechnung@lgl.eu'),
  ('LIECO GmbH & Co KG', 'Diesseits 73', NULL, '4973', 'AT', 'Sankt Martin im Innkreis', NULL, 'liecogmbhcokg@example.com'),
  ('LMB Stahl- & Metallbau GmbH', 'Musenbergstraße 42', NULL, '81929', 'DE', 'München', NULL, 'lmbstahlmetallbaugmb@example.com'),
  ('LSP', 'Dachauer Str. 65', NULL, '80335', 'DE', 'München', NULL, 'lsp@example.com'),
  ('LUPİ LOJİSTİK ANONİM ŞİRKETİ', 'MEVLANA MAH.YILDIRIM BEYAZIT CAD.MORMENEKŞE SİTESİ NO:14 C  İC KAPİ NO', NULL, '4 ESEN', 'TR', 'Yurt Istabul', '6091229268', 'yildiz@lupilojistik.com'),
  ('La Nuova Casa GmbH & Co. KG', 'Landsberger Straße 374', NULL, '80687', 'DE', 'München', NULL, 'lanuovacasagmbhcokg@example.com'),
  ('Lacoste Austria GmbH', 'Söllheimerstrasse 16', NULL, '5020', 'AT', 'Salzburg', NULL, 'accounting-de@lacoste.com'),
  ('Lacoste Denmark ApS', 'Lindgreens Alle 12, 2.tv.', NULL, '2300', 'DK', 'Københagn S', NULL, 'lacostedenmarkaps@example.com'),
  ('Lacoste Germany GmbH', 'Leopoldstrasse 158', NULL, '80804', 'DE', 'München', '+49 06 98 679 80 90', 'info@lacoste.com'),
  ('Lacoste Germany GmbH c/o KPMG Tax AS', 'Postboks 7000', NULL, '306', 'NO', 'Oslo', NULL, 'lacostegermanygmbhco@example.com'),
  ('Lacoste Sweden AB', 'Sank Eriksgatan 119', NULL, '131 43', 'SE', 'Stockholm', NULL, 'lacosteswedenab@example.com'),
  ('Lacoste Switzerland AG', 'Wright-Strasse 9', NULL, '8152', 'CH', 'Opfikon', NULL, 'accounting-ch@lacoste.com'),
  ('Lacoste UK Ltd', '4th Floor - Holborn Gate – 326-330 High Holborn', NULL, 'WC1V 7PP', 'UK', 'London', NULL, 'skegel@lacoste.com'),
  ('Landeshauptstadt München', 'Schäflarnstr.10', NULL, '81371', 'DE', 'München', NULL, 'landeshauptstadtmnch@example.com'),
  ('Landeshauptstadt München Referat für Bildung und Sport', 'Bayerstr. 28', NULL, '80335', 'DE', 'München', NULL, 'landeshauptstadtmnch@example.com'),
  ('Landi Sp. z o.o.', 'Nowogrodzka 50/515', NULL, '00-695', 'PL', 'Warszawa', NULL, 'office@landilogistics.com'),
  ('Lectra Deutschland GmbH', 'Adalperostr. 80', NULL, '85737', 'DE', 'Ismaning', NULL, 'lectradeutschlandgmb@example.com'),
  ('Liebherr-Werk Nenzing GmbH', 'Dr. Hans Liebherr Str. 1', NULL, '6710', 'AT', 'Nenzing', '+43 50809 44934', 'lwn-disposition@liebherr.com'),
  ('Life is good GmbH', 'Reichenbachstraße 33', NULL, '80469', 'DE', 'München', NULL, 'lifeisgoodgmbh@example.com'),
  ('Ligural Sp. z o.o.', 'Adam Mickiewicza 36A', NULL, '01-616', 'PL', 'Warszawa', NULL, 'liguralspzoo@example.com'),
  ('Limexo Europe s.r.o.', 'Ricni 456/10', NULL, '11800', 'CZ', 'Praha', NULL, 'invoice@limexo.eu'),
  ('Lini''s Bites GmbH', 'Gärtnerplatz 1', NULL, '80469', 'DE', 'Munich', NULL, 'linisbitesgmbh@example.com'),
  ('Ludwig Schleicher Anlagenbau GmbH & Co. KG', 'Neu-Weiher-Str. 4', NULL, '92690', 'DE', 'Pressath', NULL, 'ludwigschleicheranla@example.com'),
  ('M.J Global Logistic Co.,Ltd.', '240, Jungang-daero, Dong-gu, 6F, Hyundai Insurance Building', NULL, NULL, 'KR', 'Busan', NULL, 'mjgloballogisticcolt@example.com'),
  ('MAGNA Projektentwicklung West GmbH', 'Limbecker Platz 1', NULL, '45127', 'DE', 'Essen', NULL, 'magnaprojektentwickl@example.com'),
  ('MAKO TSL sp. z o.o.', 'ulica Leona Droszyńskiego 24', NULL, '80-381', 'PL', 'Gdansk', '+48585003434', 'info@makotsl.com'),
  ('MARTIN BRAUN KG', 'Tillystraße 17', NULL, '30459', 'DE', 'Hannover', NULL, 'martinbraunkg@example.com'),
  ('MASCHINENHANDEL Heinz Singler', 'Elbestraße 51', NULL, '82538', 'DE', 'Geretsried', '08171 6838', 'singler@t-online.de'),
  ('MBS Logistics GmbH', 'Hansestrasse 57', NULL, '51149', 'DE', 'Köln', NULL, 'mbslogisticsgmbh@example.com'),
  ('ME-Pressen GmbH', 'Hertener Straße 108', NULL, '45892', 'DE', 'Gelsenkirchen', NULL, 'mepressengmbh@example.com'),
  ('MEDIA 6 AGENCEMENT SHOP FITTINGS', '5, avenue des Berthaudières', NULL, '44680', 'FR', 'Sainte Pazanne', NULL, 'media6agencementshop@example.com'),
  ('MEP S.R.L.', 'zona ind.le S.Maria a Terme', NULL, '63087', 'IT', 'Comunanza', '+39 0736 845076', 'info@mep-snc.com'),
  ('MGZ München', 'Bayerstr. 3-5', NULL, '80335', 'DE', 'München', '+49 (0)89 30 90 886-0', 'rechnungen@mgz-muenchen.de'),
  ('MIDDLE EAST AIRLINES – AIRLIBAN S.A.L', 'Hugo-Eckener-Ring 161', 'Frankfurt Airport Center 1 Geb. 234', '60549', 'DE', 'Frankfurt am Main', NULL, 'AridiMo@mea.aero'),
  ('MIKI - TRANS Lukasz Kaliszewski', 'Brzozie Lubawskie 73', NULL, '13-306', 'PL', 'Kurzetnik', NULL, 'mikitranslukaszkalis@example.com'),
  ('MKS Maschinen Handels GmbH', 'Lothforster Str. 46', NULL, '41849', 'DE', 'Wassenberg', NULL, 'mksmaschinenhandelsg@example.com'),
  ('MM Stahlbau GmbH', 'Dorfstraße 24', NULL, '86676', 'DE', 'Ehekirchen', NULL, 'mmstahlbaugmbh@example.com'),
  ('MONTRASIO Werkzeugmaschinen GmbH', 'Lanzstraße 6', NULL, '68789', 'DE', 'Sankt Leon-Rot', '+49-6227-8651-0', 'carlo.montrasio@montrasio-gmbh.de'),
  ('MPIPZ Köln', 'Carl von Linne Weg 10', NULL, '50829', 'DE', 'Köln', NULL, 'mpipzkln@example.com'),
  ('MPM GmbH', 'Lengloher Str. 8', NULL, '83342', 'DE', 'Tacherting', NULL, 'mpmgmbh@example.com'),
  ('MS Marine GmbH', 'Gewerbegebiet Ost 31', NULL, '92353', 'DE', 'Postbauer-Heng', '+49 9188 3079896', 'post@ms-marine.de'),
  ('MSD Express GmbH', 'Dieselstr. 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'msdexpressgmbh@example.com');

-- Batch 9/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('MSD Transporte - Dejan Gavrilovic', 'Dieselstr. 28', NULL, '85748', 'DE', 'Garching', NULL, 'msdtransportedejanga@example.com'),
  ('Mack Rides GmbH & Co KG', 'Mauermattenstrasse 4', NULL, '79183', 'DE', 'Waldkirch', '+49 7681 2000-0', 'info@mack-rides.com'),
  ('Maier Pharma Vertrieb GmbH', 'Gewerbering 5', NULL, '85777', 'DE', 'Fahrenzhausen', NULL, 'corina.flamensbeck@maierpharma.de'),
  ('Mallorca Real Estate GmbH & Co. KG', 'Isarwinkel 8', NULL, '81379', 'DE', 'München', NULL, 'mallorcarealestategm@example.com'),
  ('Mamarella GmbH', 'Geisenhausenerstr. 17', NULL, '81379', 'DE', 'München', NULL, 'mamarellagmbh@example.com'),
  ('MankeTech GmbH', 'Stahlstr. 27', NULL, '33415', 'DE', 'Verl', NULL, 'manketechgmbh@example.com'),
  ('Manolya Electronics GmbH & Co KG', 'Kurfürstendamm 59', NULL, '10707', 'DE', 'Berlin', '+49 30 397 444 60', 'y.shatalinskyi@manolya.de'),
  ('Maschinen Stockert Großhandels- Gesellschaft mit beschränkter Haftung', 'Friedrich-Bergius-Straße 17+1', NULL, '85662', 'DE', 'Hohenbrunn', NULL, 'sa.stockert@maschinen-stockert.de'),
  ('MedAdvance GmbH & Co. KG', 'Reisertstr. 24', NULL, '53773', 'DE', 'Hennef (Sieg)', NULL, 'medadvancegmbhcokg@example.com'),
  ('MediaRange GmbH', 'Zum Quellenpark 29', NULL, '65812', 'DE', 'Bad Soden am Taunus', '+49 6196 523 81 85', 'kontakt@mediarange.de'),
  ('Medien-Dienstleistungen Knoblich GmbH', 'Senftlstraße 1', NULL, '81541', 'DE', 'München', NULL, 'mediendienstleistung@example.com'),
  ('MegaSauna GmbH', 'Otto-Hahn-Str. 4', NULL, '27283', 'DE', 'Verden (Aller)', NULL, 'megasaunagmbh@example.com'),
  ('Meil Keramik & Natursteinbau GmbH', 'Karl-Benz-Str. 18', NULL, '85221', 'DE', 'Dachau', NULL, 'meilkeramiknaturstei@example.com'),
  ('Meissner Bolte Patentanwälte Rechtsanwälte Partnerschaft mbB', 'Widenmayerstr. 47', NULL, '80538', 'DE', 'München', NULL, 'meissnerboltepatenta@example.com'),
  ('Michael Ages', 'Pfaffenpfädchen 15', NULL, '51145', 'DE', 'Köln', NULL, 'michaelages@example.com'),
  ('Michael Pendry mixed media art', 'Nymphenburger Str. 108a', NULL, '80636', 'DE', 'München', NULL, 'michaelpendrymixedme@example.com'),
  ('Michael Szing', 'Voldering 6', NULL, '84405', 'DE', 'Dorfen', NULL, 'baukraftevent@gmx.de'),
  ('Milan Martinec', 'Kounicova 681/10', NULL, '60200', 'CZ', 'Brno', NULL, 'milanmartinec@example.com'),
  ('Misnak International (UK) Ltd', '22-24 Red Lion Court', NULL, 'EC4A 3EB', 'UK', 'London', NULL, 'misnakinternationalu@example.com'),
  ('Mitsch Gottfried', 'Am Richteranger 6', NULL, '83623', 'DE', 'Dietramszell', NULL, 'mitschgottfried@example.com'),
  ('MobilHybrid GmbH', 'Bürgermeister Wegele Straße 12', NULL, '86167', 'DE', 'Augsburg', '+49 157 83503438', 'info@mobilhybrid.de'),
  ('Mobilia Transport Sp. z o.o.', 'Ul. Spacerowa 1/5', NULL, '62-811', 'PL', 'Koscielna Wies', NULL, 'mobiliatransportspzo@example.com'),
  ('Mohiyadin Zada Rehabilitation & Construction Organisation', 'Charahi Qala e Nagara', NULL, NULL, 'AF', 'Kabul', NULL, 'mohiyadinzadarehabil@example.com'),
  ('Monsun GmbH', 'Olschewskibogen 4', NULL, '80935', 'DE', 'München', NULL, 'monsungmbh@example.com'),
  ('Montefish D.O.O.', 'Dumidran', NULL, '85320', 'ME', 'Tivat', NULL, 'nabavka@montefish.me'),
  ('Mortensen', 'Spaldingstrasse 64', NULL, '20097', 'DE', 'Hamburg', NULL, 'mortensen@example.com'),
  ('Mountain Sports Outlet GmbH', 'Reichenberger Str. 1', NULL, '84130', 'DE', 'Dingolfing', NULL, 'mountainsportsoutlet@example.com'),
  ('MulTim Consulting', 'Oktomvriska Revolucija 1/11', NULL, '1300', 'MK', 'Kumanovo', NULL, 'multimconsulting@example.com'),
  ('Multigear GmbH', 'Am Flugplatz 34', NULL, '56743', 'DE', 'Mendig', '+49 (0) 2652 93605 16', 'multigeargmbh@example.com'),
  ('Mursall GmbH & Co. KG', 'Lohwiese 9', NULL, '86937', 'DE', 'Scheuring', NULL, 'mursallgmbhcokg@example.com'),
  ('Mychecker24.de', 'Siemensstr. 3', NULL, '82178', 'DE', 'Puchheim', NULL, 'mychecker24de@example.com'),
  ('Märkische Faser GmbH', 'Grisuten Strasse 13', NULL, '14727', 'DE', 'Premnitz', '+49 3386 24 3155', 'marketing@maerkische-faser.com'),
  ('NATCO GmbH Internationale Spedition', 'Diepenau 2', NULL, '28195', 'DE', 'Bremen', NULL, 'natcogmbhinternation@example.com'),
  ('NEUE WOHNKULTUR classic + design GmbH', 'Königstrasse 20 + 22', NULL, '83022', 'DE', 'Rosenheim', NULL, 'neuewohnkulturclassi@example.com'),
  ('NEWFLOW Logistics sp. z o.o.', 'ulica Łużycka 2', NULL, '81-300', 'PL', 'Gdynia', NULL, 'newflowlogisticsspzo@example.com'),
  ('NLG (New Logistic Group)', 'Ana polytkovskaya Street #10, APT 32', NULL, '131', 'GE', 'Tiflis', NULL, 'nlgnewlogisticgroup@example.com'),
  ('NORDICA COFFEE GmbH', 'Rütersbarg 52', NULL, '22529', 'DE', 'Hamburg', '+49 040571 99893 0', 'info@nordica.coffee'),
  ('NOSTA Logistics GmbH', 'Akexander-Fleming-Str. 3', NULL, '68519', 'DE', 'Viernheim', '+49 (0) 6204 98685-44', 'dburst@nosta.de'),
  ('Nagel GmbH', 'Redcarstrasse 46b', NULL, '53842', 'DE', 'Troisdorf', '+49 (0) 22 41 – 973 53 43', 'info@nagel-manufaktur.com'),
  ('Nasa Telekommunikation GmbH', 'Vogelsanger Weg 39', NULL, '40470', 'DE', 'Düsseldorf', NULL, 'nasatelekommunikatio@example.com'),
  ('National Instruments Germany GmbH', 'Landsberger Straße 346', NULL, '80687', 'DE', 'München', NULL, 'info@ni.com'),
  ('Natur Faktor GmbH', 'Danziger Str. 62', NULL, '33605', 'DE', 'Bielefeld', NULL, 'naturfaktorgmbh@example.com'),
  ('Noerpel SE', 'Wilhelm-Kentner-Straße 1', NULL, '89520', 'DE', 'Heidenheim an der Brenz', '+49 7321 3508 2514', 'export-hdh@noerpel.de'),
  ('Nordic Logistics GmbH', 'Rotenhäuser Straße 19', NULL, '21109', 'DE', 'Hamburg', '+49 40 89723860', 'nils.bastar@nordiclogistics.de'),
  ('North South Logistics', 'Building 9, Irving street Causeway bay, Suite 2405, Progress commercial', NULL, NULL, 'HK', 'Hong Kong Island', NULL, 'northsouthlogistics@example.com'),
  ('OPERADOR LOGÌSTICO REYCO, S.L.', 'C/Uruguay, 11-3. A puerta 302', NULL, '46007', 'ES', 'Valencia', NULL, 'operadorlogsticoreyc@example.com'),
  ('OQEMA UAB', 'Veiveri? g. 139-301', NULL, '46360', 'LT', 'Kaunas', NULL, 'oqemauab@example.com'),
  ('OTS-Oberlausitzer Transportservice UG', 'Berlinerstr. 111', NULL, '2943', 'DE', 'Weißwasser', NULL, 'otsoberlausitzertran@example.com'),
  ('Oertli Ophthalmedic Deutschland GmbH', 'Otto-Wagner-Straße 1', NULL, '82110', 'DE', 'Germering', '+41 71747 42 00', 'info@oertli-instruments.com'),
  ('Olympiapark München GmbH', 'Spiridon-Louis-Ring 21', NULL, '80809', 'DE', 'München', NULL, 'olympiaparkmnchengmb@example.com');

-- Batch 10/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Orango Creative', 'Am Steintor 52', NULL, '48167', 'DE', 'Münster', NULL, 'orangocreative@example.com'),
  ('Organifarms GmbH', 'Bücklestraße 3', NULL, '78467', 'DE', 'Konstanz', NULL, 'organifarmsgmbh@example.com'),
  ('Original BTC', 'Gärtnerplatz 1', NULL, '80469', 'DE', 'Munich', NULL, 'originalbtc@example.com'),
  ('Orion Express Sp. z o.o.', 'Jana Henryka Dabrowskiego 77A', NULL, '60-529', 'PL', 'Poznan', NULL, 'h.judkowiak@orionexpress.eu'),
  ('Oskar Frech GmbH + Co. KG', 'Schorndorfer Straße 32', NULL, '73614', 'DE', 'Schorndorf', NULL, 'oskarfrechgmbhcokg@example.com'),
  ('OuTao GmbH', 'Egglkofenstr. 8', NULL, '84453', 'DE', 'Mühldorf a. Inn', NULL, 'outaogmbh@example.com'),
  ('P.E.T. LOGISTICS GmbH', 'Dessauerstr. 60', NULL, '45472', 'DE', 'Mülheim an der Ruhr', NULL, 'petlogisticsgmbh@example.com'),
  ('PAAG TRANSPORT & LOGISTIC Spolka z o.o.,Sp.K.', 'ul. Czestochowska 2', NULL, '62-800', 'PL', 'Kalisz', NULL, 'paagtransportlogisti@example.com'),
  ('PENTA GmbH', 'Hans-Fischer-Str. 10-12', NULL, '80339', 'DE', 'München', NULL, 'pentagmbh@example.com'),
  ('PIA Pontis Institutional Advisors GmbH', 'Erika-Mann-Straße 7', NULL, '80636', 'DE', 'München', NULL, 'piapontisinstitution@example.com'),
  ('PREMIER FOODS GROUP LTD', 'PREMIER HOUSE, CENTRIUM BUSINESS  PARK', NULL, 'AL1 2RE', 'UK', 'ST ALBANS, HERTFORDSHIRE', NULL, 'premierfoodsgroupltd@example.com'),
  ('PRP Profile GmbH', 'Rahlstedter Str. 128', NULL, '22143', 'DE', 'Hamburg', NULL, 'prpprofilegmbh@example.com'),
  ('PUTZMEISTER Concrete Pumps GmbH', 'Max-Eyth-Str. 10', NULL, '72631', 'DE', 'Aichtal', NULL, 'putzmeisterconcretep@example.com'),
  ('Parkstrom GmbH', 'Karl-Marx-Allee 71', NULL, '10243', 'DE', 'Berlin', NULL, 'parkstromgmbh@example.com'),
  ('Patir Design GmbH', 'Dieselstrasse 18', NULL, '85386', 'DE', 'Eching b. München', NULL, 'patirdesigngmbh@example.com'),
  ('Permanent Entertainment GmbH', 'Reichenbachstraße 33', NULL, '80469', 'DE', 'München', NULL, 'permanententertainme@example.com'),
  ('Perzl-Systems', 'Alpenstr. 9', NULL, '81541', 'DE', 'München', NULL, 'perzlsystems@example.com'),
  ('Pfaff International GmbH', 'Schussentalstraße 15', NULL, '88255', 'DE', 'Baienfurt', NULL, 'pfaffinternationalgm@example.com'),
  ('Pflanzenhandel Lappen', 'Herrenpfad 14', NULL, '41334', 'DE', 'Nettetal', NULL, 'pflanzenhandellappen@example.com'),
  ('Pflegeheim Dresden Am Elbufer GmbH', 'Käthe-Kollwitz-Ufer 4', NULL, '01307', 'DE', 'Dresden', '+49 (0)351/652 86 81-22', 'pflegeheimdresdename@example.com'),
  ('Pflegeheim Pulsnitz GmbH', 'Bahnhofstraße 5', NULL, '01896', 'DE', 'Pulsnitz', NULL, 'pflegeheimpulsnitzgm@example.com'),
  ('Pharmact GmbH', 'Theodor-Kutzer-Ufer 1-3', NULL, '68167', 'DE', 'Mannheim', NULL, 'pharmactgmbh@example.com'),
  ('Planttech Engineering GmbH', 'Louis-Berger-Weg 7', NULL, '59379', 'DE', 'Selm', '+49 (0) 25 92 / 91 505-0', 'Rechnungen@planttech.de'),
  ('Plus Construction GmbH', 'Schmielenfeldstr. 46', NULL, '45772', 'DE', 'Marl', NULL, 'plusconstructiongmbh@example.com'),
  ('Pnt Expo GmbH', 'Promenadenweg 5', NULL, '47809', 'DE', 'Krefeld', NULL, 'pntexpogmbh@example.com'),
  ('Polaris Handelsgesellschaft m.b.H.', 'Landstraßer Hauptstraße 146-148/16/B2', NULL, '1030', 'AT', 'Wien', NULL, 'dhuehne@polarisfamily.com'),
  ('Polwama sp. z o.o.', 'W?. Andersa 22/202', NULL, '75016', 'PL', 'Koszalin', NULL, 'polwamaspzoo@example.com'),
  ('President Dental GmbH', 'Kesselbodenstraße 5', NULL, '85391', 'DE', 'Allershausen', NULL, 'presidentdentalgmbh@example.com'),
  ('PrimoCargo GmbH', 'Rossweg 20', NULL, '20457', 'DE', 'Hamburg', NULL, 'primocargogmbh@example.com'),
  ('Prof. Dr. Gudrun Kadereit', 'Menzinger Str. 67', NULL, '80638', 'DE', 'München', NULL, 'profdrgudrunkadereit@example.com'),
  ('Prof. Michael Bohnet', 'Leibnizstr. 59', NULL, '53177', 'DE', 'Bonn', NULL, 'profmichaelbohnet@example.com'),
  ('Proje Kargo Taşımacılık Ltd. Şti.', 'Ertuğrul Gazi Sokak', NULL, '34758', 'TR', 'Ataşehir', NULL, 'projekargotamaclkltd@example.com'),
  ('Projekt Dagobah', 'Eichhornstr. 17', NULL, '50735', 'DE', 'Köln', NULL, 'projektdagobah@example.com'),
  ('Q&D Services und Handels GmbH', 'Sankt-Peter-Straße 5', NULL, '72760', 'DE', 'Reutlingen', NULL, 'qdservicesundhandels@example.com'),
  ('Q-railing Central Europe GmbH', 'Marie-Curie-Str. 8-14', NULL, '46446', 'DE', 'Emmerich am Rhein', NULL, 'qrailingcentraleurop@example.com'),
  ('QEMETICA S.A.', 'Wspólna 62', NULL, '00-684', 'PL', 'Warszawa', '+48 22 639 11 00', 'IOD@qemetica.com'),
  ('QRC Management Consulting GmbH', 'Brahmsstr. 24a', NULL, '81677', 'DE', 'München', NULL, 'qrcmanagementconsult@example.com'),
  ('RENK GmbH', 'Rodder Damm 170', NULL, '48432', 'DE', 'Rheine', '+49 821 5700-0', 'info@renk.com'),
  ('ROIMEX', 'Robert-Koch-Str. 2', NULL, '82152', 'DE', 'Planegg', NULL, 'roimex@example.com'),
  ('ROTT Industrie GmbH & Co.KG', 'Kalkgrub 1-2', NULL, '84427', 'DE', 'Sankt Wolfgang', '+49 (0)8085 - 93 88 - 0', 'info@rott-group.com'),
  ('RUBBLE MASTER HMH GmbH', 'Im Südpark 196', NULL, '4030', 'AT', 'Linz', NULL, 'rubblemasterhmhgmbh@example.com'),
  ('RUKU Sauna-Manufaktur GmbH & Co. KG', 'Dietenheimer Str. 39', NULL, '89257', 'DE', 'Illertissen', NULL, 'rukusaunamanufakturg@example.com'),
  ('RWE Power AG', 'Zum Gut Bohlendorf', NULL, '50126', 'DE', 'Bergheim', NULL, 'rwepowerag@example.com'),
  ('RWE Power Aktiengesellschaft', 'RWE-Platz 2', NULL, '45141', 'DE', 'Essen', NULL, 'rwepoweraktiengesell@example.com'),
  ('Radsatz089 GmbH', 'Situlistraße 24', NULL, '80939', 'DE', 'München', NULL, 'info-radsatz089@gmx.de'),
  ('Rainer Butzmann', 'Fuggerstrasse 6', NULL, '81373', 'DE', 'München', NULL, 'rainerbutzmann@example.com'),
  ('Ralf Pfeffer', 'Liebigstraße 255', NULL, '50739', 'DE', 'Köln', NULL, 'ralfpfeffer@example.com'),
  ('Rangel Transitarios, S.A.', 'Rua da Serra, 654 Folgosa (Maia) - Aprtado 1192', NULL, '4446-909', 'PT', 'Ermesinde', NULL, 'rangeltransitariossa@example.com'),
  ('Refratechnik Steel GmbH', 'Am Seestern 5', NULL, '40547', 'DE', 'Düsseldorf', NULL, 'refratechniksteelgmb@example.com'),
  ('Regalsystem GmbH', 'Gyuru str 12/a', NULL, '4033', 'HU', 'Debrecen', NULL, 'regalsystemgmbh@example.com');

-- Batch 11/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Regatta GmbH', 'Reichenberger Str. 1', NULL, '84130', 'DE', 'Dingolfing', NULL, 'regattagmbh@example.com'),
  ('Rhenus Freight East GmbH', 'Messenhäuser Straße 18', NULL, '63128', 'DE', 'Dietzenbach', '+49 40 280 044 921', 'rhenusfreighteastgmb@example.com'),
  ('Rhenus Freight Logistics GmbH & Co. KG', 'Dieselstrasse 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'rhenusfreightlogisti@example.com'),
  ('Richard Wagner GmbH & Co. KG Spedition', 'Heinrich-Hertz-Str. 8', NULL, '92224', 'DE', 'Amberg', '+49 (0)9621 7720-0', 'info@wagner-spedition.de'),
  ('Riedel Filtertechnik GmbH', 'Westring 83', NULL, '33818', 'DE', 'Leopoldshöhr', NULL, 'riedelfiltertechnikg@example.com'),
  ('Riedl Aufzugbau GmbH & Co. KG', 'Sonnenstraße 24', NULL, '85622', 'DE', 'Feldkirchen', '+49 89 90001 0', 'info@riedl-aufzuege.de'),
  ('Riekewald Niels', 'Rütersbarg 52', NULL, '22529', 'DE', 'Hamburg', NULL, 'edgaras.murnikas@sirum.de'),
  ('RoMiro GmbH', 'Seumestrasse 8', NULL, '22089', 'DE', 'Hamburg', NULL, 'romirogmbh@example.com'),
  ('Robert Krebs GmbH', 'Buschwerder Hauptdeich 5-9', NULL, '21107', 'DE', 'Hamburg', NULL, 'robertkrebsgmbh@example.com'),
  ('Robert Kukla GmbH', 'Kochelseestraße 8-10', NULL, '81371', 'DE', 'München', NULL, 'robertkuklagmbh@example.com'),
  ('Rollo Solar Melichar GmbH', 'Josef-Janker-Ring 18', NULL, '83646', 'DE', 'Bad Tölz', '+49 8041 792650', 'info@rollo-solar.de'),
  ('Rondo Food GmbH & Co. KG', 'Magdeburger Straße 65', NULL, '47800', 'DE', 'Krefeld', '+49 2151 44 12-0', 'contact@rondo-food.de'),
  ('Rowema AG', 'Im Schörli 17', NULL, '8600', 'CH', 'Dübendorf', NULL, 'rowemaag@example.com'),
  ('Ruoheng Dong', 'Egglkofenstr.8', NULL, '84453', 'DE', 'Mühldorf', NULL, 'ruohengdong@example.com'),
  ('S.C. ROUTIER European Transport S.R.L.', 'Gil?u 1334', NULL, '407310', 'RO', 'Gil?u', NULL, 'scroutiereuropeantra@example.com'),
  ('S2 GmbH', 'Am Heiligenberg 2b', NULL, '69488', 'DE', 'Birkenau', NULL, 'bauen@s2-architektur.com'),
  ('SC PROCONEX SRL', 'Str. Calea Adevarului  nr. 111A', NULL, NULL, 'RO', 'Oradea jud.Bihor', NULL, 'scproconexsrl@example.com'),
  ('SCHMIDT-HOFMANN GmbH & Co. KG', 'Industriestraße 5', NULL, NULL, 'DE', 'Rugendorf', NULL, 'schmidthofmanngmbhco@example.com'),
  ('SEATRADER Speditionsgesellschaft mbH', 'Mittelwendung 27', NULL, '28844', 'DE', 'Weyhe', '+49 (0) 4218 84 96 20', 'office@seatrader.de'),
  ('SEELING TRANSPORTLOGISTIK', 'Gothaerstr. 4', NULL, '40880', 'DE', 'Ratingen', NULL, 'seelingtransportlogi@example.com'),
  ('SENATOR INTERNATIONAL Spedition GmbH', 'Obenhauptstraße 13', NULL, '22335', 'DE', 'Hamburg', NULL, 'senatorinternational@example.com'),
  ('SENATOR INTERNATIONAL Spedition GmbH', 'Marienbergstr. 94', NULL, '90411', 'DE', 'Nürnberg', NULL, 'senatorinternational@example.com'),
  ('SENSO Süd GmbH', 'Industriering Ost 72', NULL, '47906', 'DE', 'Kempen', NULL, 'sensosdgmbh@example.com'),
  ('SFBAAM, LLC', 'Adams Ave 2130', NULL, '94577-1010', 'US', 'San Leandro', NULL, 'sfbaamllc@example.com'),
  ('SMS Spedition Management Service GmbH', 'Luftfrachtzentrum 610/2', NULL, '70629', 'DE', 'Stuttgart', NULL, 'smsspeditionmanageme@example.com'),
  ('SOKO Tierschutz e.V', 'Bodenehrstr. 20', NULL, '813737', 'DE', 'München', NULL, 'sokotierschutzev@example.com'),
  ('SPEDICAM & LOGISTIK GMBH', 'Hamburger Str. 70', NULL, '90451', 'DE', 'Nürnberg', NULL, 'spedicamlogistikgmbh@example.com'),
  ('SPS Schwimmbad & Pool Service GmbH', 'Eike-Kerstein-Straße 4', NULL, '31789', 'DE', 'Hameln', NULL, 'Marie.Dannat@binder24.com'),
  ('SPSC GmbH', 'Neumarkter Strasße 34', NULL, '81673', 'DE', 'München', NULL, 'spscgmbh@example.com'),
  ('STL Logistik GmbH', 'Lütticher Straße 12', NULL, '53842', 'DE', 'Troisdorf', '+49 2241 493 00 15', 'info@stl-logistik.com'),
  ('STRABAG Großprojekte GmbH', 'Leopoldstr. 250c', NULL, '80807', 'DE', 'München', NULL, 'strabaggroprojektegm@example.com'),
  ('STRABAG Großprojekte GmbH', 'Auftrag: IFORU DE / Rechnungen', NULL, '69966', 'DE', 'Mannheim', NULL, 'strabaggroprojektegm@example.com'),
  ('SWM Versorgungs GmbH', 'Emmy-Noether-Str. 2', NULL, '80992', 'DE', 'München', NULL, 'swmversorgungsgmbh@example.com'),
  ('Sabbagh & Hejjazi Gbr', 'Im Neubruch 13', NULL, '82211', 'DE', 'Herrsching am Ammersee', NULL, 'sabbaghhejjazigbr@example.com'),
  ('Sachsenland Transport & Logistik GmbH Dresden', 'Mülheimer Strasse 58', NULL, '47057', 'DE', 'Duisburg', NULL, 'sachsenlandtransport@example.com'),
  ('Sadarak', 'Qaradaq dstr, Lokbatan STV, Bilal Niftaliyev str. 45/60', NULL, '1063', 'AZ', 'Baku', NULL, 'sadarak@example.com'),
  ('Sandra Feldmann Ltd.', 'Flat #3 Gloria Place, Konstantinou Kalogera 137', NULL, '6021', 'CZ', 'Skala Larnaca', NULL, 'sandrafeldmannltd@example.com'),
  ('Sankurt Bau-und Tragwerksplanung GmbH', 'Hagener Str. 339', NULL, '44229', 'DE', 'Dortmund', NULL, 'sankurtbauundtragwer@example.com'),
  ('SanumTec GmbH', 'Georg-Knorr-Str. 1', NULL, '85662', 'DE', 'Hohenbrunn', '+49 (0) 4251 9352-0', 'info@sanum.com'),
  ('Sanyborn Hygiene Produkte', 'Brudermühlstr 46b', NULL, '81371', 'DE', 'München', NULL, 'sanybornhygieneprodu@example.com'),
  ('Sauna One GmbH', 'Große Schneede 8b', NULL, '29664', 'DE', 'Walsrode', '05161784340', 'megasauna@sauna-one.de'),
  ('Sawade GmbH', 'Wittestr. 26e', NULL, '13509', 'DE', 'Berlin', NULL, 'sawadegmbh@example.com'),
  ('Scantrans ApS', 'Håndværkervej 6', NULL, '6710', 'DK', 'Esbjerg', NULL, 'scantransaps@example.com'),
  ('Schach zu Dritt | Gesellschaft für Kommunikation mbH', 'Schinkestraße 9', NULL, '12047', 'DE', 'Berlin', NULL, 'schachzudrittgesells@example.com'),
  ('Schrauben-Bauer GmbH', 'Mittlerer Weg 3', NULL, '74080', 'DE', 'Heilbronn', NULL, 'schraubenbauergmbh@example.com'),
  ('Schreinerei Sigrüner', 'Am Gries 3', NULL, '84543', 'DE', 'Winhöring', '+49 176 28768842', 'Michlbauer.sara@sigruener.de'),
  ('Schub Global Logistik GmbH', 'Am Pestalozziring 14', NULL, '91058', 'DE', 'Erlangen', NULL, 'schubgloballogistikg@example.com'),
  ('SeaCurity GmbH', 'Walhallastraße 38', NULL, '80639', 'DE', 'München', '+49 89 12711526', 'info@seacurity.de'),
  ('Senic GmbH', 'Pfuelstraße 5', NULL, '10997', 'DE', 'Berlin', NULL, 'senicgmbh@example.com'),
  ('Seniorenresidenz Fortweg GmbH', 'Fortweg 3', NULL, '35415', 'DE', 'Pohlheim', '+49 (0) 6403/9797-510', 'seniorenresidenzfort@example.com');

-- Batch 12/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Seniorenresidenz zur Weißen Dame GmbH', 'An der Weißen Dame 5', NULL, '48599', 'DE', 'Gronau', NULL, 'seniorenresidenzzurw@example.com'),
  ('Seniorenzentrum Brakel GmbH', 'Lütkerlinde 21', NULL, '33034', 'DE', 'Brakel', '+49 (0) 2924/802-445', 'seniorenzentrumbrake@example.com'),
  ('Seniorenzentrum Cäcilienhof Garbsen GmbH', 'Bruno-Rappel-Weg 1', NULL, '30827', 'DE', 'Garbsen', NULL, 'seniorenzentrumccili@example.com'),
  ('Seniorenzentrum Haus Kettwig GmbH', 'Akademiestr. 2', NULL, '45219', 'DE', 'Essen', '02054-9320', 'info@haus-kettwig.de'),
  ('Seniorenzentrum Nidda GmbH', 'Kurstraße 28', NULL, '63667', 'DE', 'Nidda - Bad Salzhausen', NULL, 'seniorenzentrumnidda@example.com'),
  ('Seniorenzentrum Sophienhof GmbH', 'Hauptstraße 61', NULL, '32457', 'DE', 'Porta Westfalica', NULL, 'seniorenzentrumsophi@example.com'),
  ('Seven.One AdFactory GmbH', 'Medienallee 4', NULL, '85774', 'DE', 'Unterföhring', NULL, 'sevenoneadfactorygmb@example.com'),
  ('Shoepassion GmbH', 'Wolfener Str. 32/34', NULL, '12681', 'DE', 'Berlin', NULL, 'shoepassiongmbh@example.com'),
  ('ShopLine Ladenbau GmbH', 'Im Taubental 9-11', NULL, '41468', 'DE', 'Neuss', NULL, 'shoplineladenbaugmbh@example.com'),
  ('Simon Hegele Gesellschaft für Logistik & Service mbH', 'Standort Raunheim', NULL, '76095', 'DE', 'Karlsruhe', NULL, 'simonhegelegesellsch@example.com'),
  ('SkyTechSport Club Foundation', 'Riesenfeldstrasse 18', NULL, '80809', 'DE', 'München', NULL, 'skytechsportclubfoun@example.com'),
  ('Smilike GmbH', 'Dr.-Ulrich-Weg 1', NULL, '85435', 'DE', 'Erding', NULL, 'smilikegmbh@example.com'),
  ('Social Ninja GmbH', 'Weidenweg 52', NULL, '10247', 'DE', 'Berlin', NULL, 'socialninjagmbh@example.com'),
  ('Solida Holz GmbH', 'Teichweg 5', NULL, '35396', 'DE', 'Gießen', '+49 (0) 641 984437', 'solidaholzgmbh@example.com'),
  ('Sommer International Retailservice GmbH', 'Wierlings Esch 35', NULL, '48249', 'DE', 'Dülmen', NULL, 'sommerinternationalr@example.com'),
  ('Sonderbetriebsvermögen Jürgen Schmid', 'Birkenleiten 41', NULL, '81543', 'DE', 'München', NULL, 'sonderbetriebsvermge@example.com'),
  ('Sondermann Profile GmbH', 'Bergstraße 2', NULL, '57489', 'DE', 'Drolshagen', '+49 2761 / 83 93 - 771', 'export@sondro.de'),
  ('Sono Motors GmbH', 'Waldmeisterstraße 76', NULL, '80935', 'DE', 'München', NULL, 'sonomotorsgmbh@example.com'),
  ('Soraya Rahmati', 'Johannes-Timm-Str. 11', NULL, '81373', 'DE', 'München', NULL, 'sorayarahmati@example.com'),
  ('Space-Eye e. V.', 'Wiener Str. 14', NULL, '93055', 'DE', 'Regensburg', NULL, 'kontakt@space-eye.org'),
  ('Spectra GmbH', 'Lorenzstraße 11', NULL, '76297', 'DE', 'Stutensee', 'Tel: +49 (0) 7244 20 50 30 0', 'spectragmbh@example.com'),
  ('Spedition Bohnet GmbH', 'Erolzheimer Straße 1', NULL, '88457', 'DE', 'Kirchdorf an der Iller', NULL, 'speditionbohnetgmbh@example.com'),
  ('Spezialitäten Restaurant Makassar GmbH', 'Geyerstrasse 52', NULL, '80469', 'DE', 'München', NULL, 'spezialittenrestaura@example.com'),
  ('Spinner Werkzeugmaschinenfabrik GmbH', 'Rudolf-Diesel-Ring 24', NULL, '82054', 'DE', 'Sauerlach', NULL, 'spinnerwerkzeugmasch@example.com'),
  ('Spokebase GmbH', 'Rosenthalerstr. 13', NULL, '10119', 'DE', 'Berlin', NULL, 'spokebasegmbh@example.com'),
  ('Sport Hauser Kaibling - Frühwirth Outlet GmbH', 'Innstraße 3', NULL, '6063', 'AT', 'Rum', '+43 368620044', 'office@sport-hauser-kaibling.com'),
  ('Stappenbacher Putz- und Maler GmbH', 'Conrad-Vetter-Straße 52, Trossenfurt', NULL, '97514', 'DE', 'Oberaurach', NULL, 'stappenbacherputzund@example.com'),
  ('Stefan Altmeier', 'Waldshuterstr. 21', NULL, '79805', 'DE', 'Eggingen', NULL, 'stefanaltmeier@example.com'),
  ('Stiftung Insel Hombroich', 'Raketenstation Hombroich 4', NULL, '41472', 'DE', 'Neuss', '+49 2182 887-4003', 'klinkhamer@inselhombroich.de'),
  ('Streifeneder Ortho. Production GmbH', 'Moosfeldstr. 10', NULL, '82275', 'DE', 'Emmering', NULL, 'empfang@streifeneder.de'),
  ('Studio Westend', 'Gollierstraße 78', NULL, '80339', 'DE', 'München', NULL, 'info@studio-westend.com'),
  ('Städtische Galerie im Lenbachhaus und Kunstbau München', 'Luisenstraße 33', NULL, '80333', 'DE', 'München', NULL, 'stdtischegalerieimle@example.com'),
  ('Städtische Rainer-Werner-Fassbinder-Fachoberschule für Sozialwesen', 'Schlierseestraße 47', NULL, '81539', 'DE', 'Munich', NULL, 'stdtischerainerwerne@example.com'),
  ('Suso Transporte y Logistica Internacional, S.L.', 'C/ Landatxu, 2 - Parcela C-2', NULL, '48160', 'ES', 'Derio ( Bizkaia )', NULL, 'susotransporteylogis@example.com'),
  ('TECNICAS REUNIDAS S.A.', 'Arapiles 13, 11th floor', NULL, '28015', 'ES', 'Madrid', NULL, 'tecnicasreunidassa@example.com'),
  ('TGP Azerbaijan MMC', 'VOEN: 1406601881   Marine Plaza Premium Offices', 'Uzeyir Hajibeyli Str. 62', 'AZ1010', 'AZ', 'Baku', NULL, 'tgpazerbaijanmmc@example.com'),
  ('TOOL-TEMP AG', 'Industriestrasse 30', NULL, '8583', 'CH', 'Sulgen', NULL, 'tooltempag@example.com'),
  ('TOP SWEETS GMBH', 'Aspastraße 24', NULL, '59394', 'DE', 'Nordkirchen', NULL, 'topsweetsgmbh@example.com'),
  ('TPS Rental Systems GmbH & Co.KG', 'Hollefeldstraße 24 - 24A', NULL, '48282', 'DE', 'Emsdetten', NULL, 'rh@tpsrentalsystems.de'),
  ('TRW Thüringer Reinigungs- und Waschmittelprodukte GmbH', 'Markt 33', NULL, '4600', 'DE', 'Altenburg', NULL, 'trwthringerreinigung@example.com'),
  ('TRiooo Building Systems GmbH', 'Ziegelbreite 8', NULL, '84166', 'DE', 'Adlkofen', NULL, 'triooobuildingsystem@example.com'),
  ('Tec-quipment GmbH', 'Kronacher Str. 1 B', NULL, '96364', 'DE', 'Marktrodach', NULL, 'tecquipmentgmbh@example.com'),
  ('Technische Universität München', 'Arcisstraße 21', NULL, '80333', 'DE', 'München', NULL, 'technischeuniversitt@example.com'),
  ('Teppich Comfort GmbH', 'Kleine Stuebenstr. 11', NULL, '45139', 'DE', 'Essen', NULL, 'teppichcomfortgmbh@example.com'),
  ('Terrawerk', 'Jennerstr. 3a', NULL, '80999', 'DE', 'München', NULL, 'terrawerk@example.com'),
  ('Textilmacher GmbH', 'Lindberghstrasse 7', NULL, '80939', 'DE', 'München', NULL, 'textilmachergmbh@example.com'),
  ('Theurl Leimholzbau GmbH', 'Thal-Wilfern 35', NULL, '9911', 'AT', 'Assling', NULL, 'theurlleimholzbaugmb@example.com'),
  ('Timm & Wilken OHG', 'Hauptstraße 11', NULL, '22869', 'DE', 'Schenefeld', NULL, 'timmwilkenohg@example.com'),
  ('Trane Klima- und Kältetechnisches Büro GmbH', 'Pionierstrasse 3', NULL, '82152', 'DE', 'Krailling', NULL, 'traneklimaundkltetec@example.com'),
  ('Trans Global Projects GmbH', 'Diepenau 2', NULL, '28195', 'DE', 'Bremen', NULL, 'transglobalprojectsg@example.com');

-- Batch 13/14 (50 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Trans Global Projects LLC', 'U. Hajibeyli str. 62', NULL, 'AZ-1010', 'AZ', 'Baku', NULL, 'transglobalprojectsl@example.com'),
  ('Trans Global Projects Ltd', '1-7 Commercial Road, Paddock Wood', NULL, 'TN12 6EN', 'UK', 'Kent', '+44 1732 744 400', 'cwardale@tglobal.com'),
  ('Trans Global Projects Ltd 10166', 'Willow House, Newhouse Business Park, Newhouse Road,', NULL, 'FK3 8LL', 'UK', 'Grangemouth', NULL, 'cwardale@tglobal.com'),
  ('Transport-Service / Stroh-und Heuspedition', 'Berlinerstraße 111', NULL, '2943', 'DE', 'Weißwasser', NULL, 'transportservicestro@example.com'),
  ('Trinkwassersysteme Bauer', 'Unterfeldring 4', NULL, '85256', 'DE', 'Vierkirchen', '08139/802101', 'info@trinkwassersysteme-bauer.de'),
  ('Tunguska Transport- und Logistik GmbH', 'An den Gärten 7', NULL, '51491', 'DE', 'Overath', NULL, 'tunguskatransportund@example.com'),
  ('Tur Transit GmbH', 'Bischofstraße 94', NULL, '47809', 'DE', 'Krefeld', NULL, 'turtransitgmbh@example.com'),
  ('Turk Transport Worldwide Freight Services', 'Unit A11, Bell Lane Office Village, Bell Lane, Little Chalfont, Amersham', NULL, 'HP6 6FA', 'UK', 'Buckinghamshire', NULL, 'turktransportworldwi@example.com'),
  ('TÜV SÜD Industrie Service GmbH', 'Westendstraße 199', NULL, '80686', 'DE', 'München', NULL, 'tvsdindustrieservice@example.com'),
  ('Türkisch-Islamische Gemeinde e.V', 'Manisastraße 1', 'Ditib-Moschee-Ingolstadt', '85057', 'DE', 'Ingolstadt', NULL, 'guerkanbahce@gmail.com'),
  ('UAB Jumbo Transport', 'Graiciuno 38', NULL, '2241', 'LT', 'Vilnius', NULL, 'uabjumbotransport@example.com'),
  ('USC Mainz', 'Dalheimer Weg 2', NULL, '55128', 'DE', 'Mainz', NULL, 'uscmainz@example.com'),
  ('UTE TR FADHILI PROJECT', 'C/Maria de Portugal 9-11', NULL, '28050', 'ES', 'Madrid', NULL, 'utetrfadhiliproject@example.com'),
  ('VGG Handels AG', 'August-Thyssen-Str. 8', NULL, '41564', 'DE', 'Kaarst', NULL, 'vgghandelsag@example.com'),
  ('VGL SP. Z O.O.', 'ul. Spokojna 22', NULL, '81-549', 'PL', 'Gdynia', NULL, 'vglspzoo@example.com'),
  ('Vanclaes BV', 'Gnephoek 18', NULL, '2401LP', 'NL', 'Alphen aan den Rijn', NULL, 'vanclaesbv@example.com'),
  ('Verein Kollekitivs E.V. München', 'Rupprechtstrasse 29', NULL, '80636', 'DE', 'München', NULL, 'vereinkollekitivsevm@example.com'),
  ('Vestner Aufzüge GmbH', 'Humboldtstr. 10', NULL, '85609', 'DE', 'Dornach', '+49 3 20 88-0', 'info@vestner.de'),
  ('Viki-Gabi EOOD', 'zh.k. Druzhba, bl. 134 et. 1, ap. 2', NULL, '5800', 'BG', 'Pleven', NULL, 'vikigabieood@example.com'),
  ('Voipango EOD European Online Distribution GmbH', 'Bötzinger Strasse 31', NULL, '79111', 'DE', 'Freiburg', NULL, 'voipangoeodeuropeano@example.com'),
  ('WAGU Gummitechnik GmbH', 'Friedrich-Harkort-Str. 17', NULL, '59581', 'DE', 'Warstein', '+ 49 2902-9739-0', 'info@wagu-rubber.com'),
  ('WAREMA Renkhoff SE', 'Hymerring 6', NULL, '97877', 'DE', 'Wertheim', NULL, 'waremarenkhoffse@example.com'),
  ('WISAG Gebäudetechnik Bayern GmbH & Co. KG', 'Inselkammerstraße 4', NULL, '82008', 'DE', 'Unterhaching', NULL, 'wisaggebudetechnikba@example.com'),
  ('Wahl GmbH & Co. KG Spedition und Logistik', 'Gildemeisterstraße 150', NULL, '33689', 'DE', 'Bielefeld', NULL, 'wahlgmbhcokgspeditio@example.com'),
  ('Waräger GmbH', 'Kaiserstraße 137', NULL, '72764', 'DE', 'Reutlingen', NULL, 'wargergmbh@example.com'),
  ('WaterBeck GmbH', 'Reichardstraße 18', NULL, '31789', 'DE', 'Hameln', '+49 (0) 800 000 8403', 'info@waterbeck-gmbh.de'),
  ('Weldex Euro GmbH', 'Gewerbering 3A', NULL, '82140', 'DE', 'Olching', NULL, 'weldexeurogmbh@example.com'),
  ('Welmaet Handels GmbH', 'Ramsauerstrasse 11', NULL, '81379', 'DE', 'München', NULL, 'welmaethandelsgmbh@example.com'),
  ('Wenzel Marine GmbH & Co. KG', 'Rodendamm 25', NULL, '28816', 'DE', 'Stuhr', '+49  421 959250', 'mail@wenzelmarine.com'),
  ('Wermil Handels GmbH', 'Schäftlarnstr. 10', NULL, '81371', 'DE', 'München', NULL, 'wermilhandelsgmbh@example.com'),
  ('Werner Graf Holding GmbH', 'Gymnasiumstraße 67', NULL, '1190', 'AT', 'Vienna', NULL, 'wernergrafholdinggmb@example.com'),
  ('Weserra GmbH', 'Hermann-Oberth-Straße 9', NULL, '85640', 'DE', 'Putzbrunn', NULL, 'benau1@web.de'),
  ('Westfälische Handels GmbH', 'Niedersachsenweg 6', NULL, '44143', 'DE', 'Dortmund', NULL, 'isa.ozlemis@gmail.com'),
  ('Wever & Ducre GmbH', 'Riederstraße 1', NULL, '85229', 'DE', 'Markt Indersdorf', NULL, 'weverducregmbh@example.com'),
  ('Wever & Ducré BV', 'Spinnerijstraat 99/21', NULL, '8500', 'BE', 'Kortrijk', NULL, 'invoices@weverducre.com'),
  ('Wild Brain CPLG', 'Thalkirchner Straße 2', NULL, '80337', 'DE', 'Munich', '49 89 541999208', 'wildbraincplg@example.com'),
  ('Wild-Berghof Buchet - Thomas Gstettenbauer', 'Buchet 2', NULL, '94505', 'DE', 'Bernried-Buchet', '09905 - 248', 'info@wildberghof-buchet.de'),
  ('Wilhelm Kentner Kraftwagen-Spedition GmbH & Co. KG', 'Wilhelm-Kentner-Str. 1', NULL, '89520', 'DE', 'Heidenheim', NULL, 'wilhelmkentnerkraftw@example.com'),
  ('Wissenschaftliche Elektronik GmbH', 'Am Eichberg 5', NULL, '66440', 'DE', 'Blieskastel', NULL, 'info@wissel.eu'),
  ('Wittmann Battenfeld Deutschland GmbH', 'Werner-Battenfeld-Str. 1', NULL, '58540', 'DE', 'Meinerzhagen', NULL, 'wittmannbattenfeldde@example.com'),
  ('Wohnmoderne OHG', 'Klenzestraße 59', NULL, '80469', 'DE', 'München', NULL, 'wohnmoderneohg@example.com'),
  ('Wohnungs- und Siedlungsbau Bayern GmbH & Co. oHG', 'Hansastrasse 27f', NULL, '81373', 'DE', 'München', NULL, 'wohnungsundsiedlungs@example.com'),
  ('World of Less - Logistic Trading GmbH', 'Am Lenghardt 11', NULL, '84174', 'DE', 'Eching', '08709 / 943 298-0', 'anfrage@world-of-less.de'),
  ('Worldplast Sp. z o.o.', 'Irysowa 9', NULL, '55-040', 'PL', 'Bielany Wroc?awskie', NULL, 'worldplastspzoo@example.com'),
  ('Worldplast Sp. z o.o. 10457', 'Irysowa 9', NULL, '55-040', 'PL', 'Bielany Wroc?awskie', NULL, 'worldplastspzoo10457@example.com'),
  ('XAL GmbH', 'Riederstraße 1', NULL, '85229', 'DE', 'Markt Indersdorf', '+49 89 32373830', 'LV.DE@xal.com'),
  ('YCCP GmbH', 'Römerstraße 14', NULL, '80801', 'DE', 'München', NULL, 'yccpgmbh@example.com'),
  ('Z GLOBAL LOGISTICS S.R.L.', 'Sat Bascov, Comuna Bascov , Strada Pinilor nr 12, Camera C4', NULL, NULL, 'RO', 'Judet Arge?', NULL, 'zgloballogisticssrl@example.com'),
  ('ZEISST GmbH', 'Hofbrunnstrasse 45c', NULL, '81479', 'DE', 'München', NULL, 'zeisstgmbh@example.com'),
  ('Zambelli Dach + Fassadentechnik GmbH', 'Hans-Sachs-Straße 3+5', NULL, '94569', 'DE', 'Stephansposching', NULL, 'zambellidachfassaden@example.com');

-- Batch 14/14 (31 customers)
INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Zambelli RIB-ROOF GmbH & Co. KG', 'Hans-Sachs-Straße 3+5', NULL, '94569', 'DE', 'Stephansposching', NULL, 'Juergen.Renner@zambelli.com'),
  ('Zeman & Co GmbH', 'Clemens-Holzmeister-Straße 6', NULL, '1100', 'AT', 'Wien', NULL, 'zemancogmbh@example.com'),
  ('acargo GmbH', 'Ellerholzdamm 9', NULL, '20457', 'DE', 'Hamburg', NULL, 'acargogmbh@example.com'),
  ('adamicus GmbH', 'Blumenstrasse 28', NULL, '80331', 'DE', 'München', NULL, 'adamicusgmbh@example.com'),
  ('albertZWEI media GmbH', 'Oettingenstraße 25', NULL, '80538', 'DE', 'München', NULL, 'albertzweimediagmbh@example.com'),
  ('aqua-vogt.de Gmbh', 'Fichtenweg 10', NULL, '75449', 'DE', 'Wurmberg', '07044-909786', 'info@aqua-vogt.de'),
  ('bernhard rüsing gmbh + co. kg', 'Mittelstrasse 5', NULL, '41469', 'DE', 'Neuss', NULL, 'bernhardrsinggmbhcok@example.com'),
  ('bikmed -Bildungsinstitut für Kompetenz in der Medizin GmbH', 'Wilhelm-Hale-Straße 46 B', NULL, '80639', 'DE', 'München', NULL, 'bikmedbildungsinstit@example.com'),
  ('boschen & oetting Automatisierungs-Bau GmbH', 'Wohlrabedamm 11', NULL, '13629', 'DE', 'Berlin', NULL, 'boschenoettingautoma@example.com'),
  ('e+p films GmbH', 'Heßstr. 48b', NULL, '80798', 'DE', 'München', NULL, 'epfilmsgmbh@example.com'),
  ('eVehicle for you GmbH', 'Maria-Theresia-Straße 1a', NULL, '81675', 'DE', 'München', NULL, 'evehicleforyougmbh@example.com'),
  ('german paper solutions GmbH & Co. KG', 'Wupperstr. 38', 'L. Nr. 8609', '58332', 'DE', 'Schwelm', NULL, 'info@erfurtspezialpapiere.com'),
  ('gül koc GmbH interior design + construction services', 'Reichenbachstraße 35', NULL, '80469', 'DE', 'München', NULL, 'glkocgmbhinteriordes@example.com'),
  ('i-log logistics solutions GmbH', 'Industriezeile 1, Objekt 5', NULL, '8401', 'AT', 'Kalsdorf', NULL, 'iloglogisticssolutio@example.com'),
  ('innovIT AG', 'Schloss Heiligenberg', NULL, '64342', 'DE', 'Seeheim-Jugenheim', NULL, 'innovitag@example.com'),
  ('inside', 'Wienerbergstrasse 11', NULL, '1100', 'AT', 'Wien', NULL, 'inside@example.com'),
  ('kg-pharma AB', 'Björnholmsvägen 4', NULL, '184 92', 'SE', 'Åkersberga/Stockholm län', NULL, 'kgpharmaab@example.com'),
  ('kg-pharma GmbH & Co. KG', 'Pestalozzistr. 25', NULL, '22305', 'DE', 'Hamburg', NULL, 'kgpharmagmbhcokg@example.com'),
  ('klarx GmbH', 'Koppstraße 16', NULL, '81379', 'DE', 'München', NULL, 'info@klarx.com'),
  ('koziol »ideas for friends GmbH', 'Werner-von-Siemens-Straße 90', NULL, '64711', 'DE', 'Erbach / Odenwald', '+49 6062 6040', 'info@koziol.de'),
  ('matten-zuschnitt.de', 'Gottlieb-Daimler-Str. 14', NULL, '68165', 'DE', 'Mannheim', NULL, 'mattenzuschnittde@example.com'),
  ('mefro Metallwarenfabrik Fischbacher GmbH', 'Ludwig-Thoma-Straße 29', NULL, '83101', 'DE', 'Rohrdorf', NULL, 'mefrometallwarenfabr@example.com'),
  ('mundotec GmbH', 'Hannöversche Straße 20A', NULL, '44143', 'DE', 'Dortmund', NULL, 'umran.coskun@mundotec.de'),
  ('qqq team', 'Fraunhoferstraße 5', NULL, '80469', 'DE', 'Munich', NULL, 'team@yarres-logistics.com'),
  ('re-fer GmbH', 'Neuenburger Straße 37', NULL, '79379', 'DE', 'Müllheim', NULL, 'refergmbh@example.com'),
  ('roko project & consulting GmbH', 'Sudetenstraße 2', NULL, '92259', 'DE', 'Neukirchen bei Sulzbach-Rosenberg', NULL, 'rokoprojectconsultin@example.com'),
  ('steintex GmbH', 'Industriestr. 12-16', NULL, '42929', 'DE', 'Wermelskirchen', NULL, 'hetze@steintex.de'),
  ('stela Laxhuber GmbH', 'Laxhuberplatz 1', NULL, '84323', 'DE', 'Massing', NULL, 'stelalaxhubergmbh@example.com'),
  ('transmaritim international GmbH', 'Willy-Brandt-Straße 23-25', NULL, '20457', 'DE', 'Hamburg', NULL, 'transmaritiminternat@example.com'),
  ('wisefood GmbH', 'Dieselstr. 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'wisefoodgmbh@example.com'),
  ('Ötztal Tourismus Congress GmbH', 'Gurglerstrasse 118', NULL, '6456', 'AT', 'Obergurgl', NULL, 'tztaltourismuscongre@example.com');

