-- Part 2/5
-- Customers 138 to 274 (137 total)

INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('DYWIDAG Systems International GmbH', 'Neuhofweg 5', NULL, '85716', 'DE', 'Unterschleißheim', '+49-89-30 90 50-100', 'dsihv@dywidag.com'),
  ('DYWIDAG-Systems International B.V.', 'Veilingweg 2', NULL, '5301KM', 'NL', 'Zaltbommel', NULL, 'dywidagsystemsintern@example.com'),
  ('DYWIDAG-Systems International GmbH', 'Germanenstraße 8', NULL, '86343', 'DE', 'Königsbrunn', NULL, 'Joachim.Truetsch@dywidag.com'),
  ('Deniz Caliskan', 'Am Bleichbach 9', NULL, '85452', 'DE', 'Moosinning', NULL, 'denizcaliskan@example.com'),
  ('Deutsche Post AG', 'Franz-Zebisch-Str. 15', NULL, '92637', 'DE', 'Weiden', NULL, 'deutschepostag@example.com'),
  ('Deutsche Rettungsdiensthilfe e.V.', 'Baubergerstraße 61', NULL, '80992', 'DE', 'München', NULL, 'info@deutsche-rettungsdiensthilfe.de'),
  ('Dietz Kältetechnik GmbH & Co. KG', 'Steindamm 48', NULL, '28719', 'DE', 'Bremen', '0421 / 63 26 29', 'buchhaltung@dietz-kaelte.de'),
  ('Dipol GmbH', 'Dillenburger Weg 50', NULL, '40229', 'DE', 'Düsseldorf', NULL, 'dipolgmbh@example.com'),
  ('Direct-Route Sarl', '1, rue de Stockholm', NULL, '75008', 'FR', 'Paris', NULL, 'directroutesarl@example.com'),
  ('Dispo', 'Gewerbegebiet Ost 31', NULL, '92353', 'DE', 'Postbauer-Heng', NULL, 'dispo@ms-marine.de'),
  ('Dominic Laufenberg', 'Dorotheenstraße 12', NULL, '22301', 'DE', 'Hamburg', NULL, 'dominiclaufenberg@example.com'),
  ('Dr. Ingrid Th.Schwerzel-Schoer', 'Mauerkircherstraße 1/b', NULL, '81679', 'DE', 'München', NULL, 'dringridthschwerzels@example.com'),
  ('Dr. Ljubomir Petkov', 'Albert-Rosshaupter Str.67', NULL, '81369', 'DE', 'München', NULL, 'drljubomirpetkov@example.com'),
  ('DrGreen GmbH', 'Schnelldorf 64', NULL, '4975', 'AT', 'Suben', NULL, 'team@drgreen.at'),
  ('Drahtseilwerk GmbH', 'Auf der Bult 14 - 16', NULL, '27574', 'DE', 'Bremerhaven', NULL, 'drahtseilwerkgmbh@example.com'),
  ('Druckerei Vogl GmbH & Co.KG', 'Georg-Wimmer-Ring 9', NULL, '85604', 'DE', 'Zorneding', '+49 (0) 8106-23081-70', 'versand@druckerei-vogl.de'),
  ('Dunkermotoren GmbH', 'Allmendstr. 11', NULL, '79848', 'DE', 'Bonndorf/Schwarzwald', '+49 7703 930 - 0', 'info.dunkermotoren@ametek.com'),
  ('Duotec Medical GmbH', 'Dr.-Kurt-Huber-Str. 6', NULL, '82031', 'DE', 'Grünwald', NULL, 'duotecmedicalgmbh@example.com'),
  ('Dwuzet Fassadentechnik GmbH', 'Bredowstrasse 10', NULL, '22113', 'DE', 'Hamburg', NULL, 'dwuzetfassadentechni@example.com'),
  ('Düllberg Konzentra GmbH & Co. KG', 'Obenhauptstrasse 3', NULL, '22335', 'DE', 'Hamburg', NULL, 'dllbergkonzentragmbh@example.com'),
  ('E-proPLAST GmbH', 'An der Asbacher Str. 38', NULL, '98574', 'DE', 'Schmalkalden', NULL, 'eproplastgmbh@example.com'),
  ('ED-TRANS', '6 bis rue Deneb', NULL, '72230', 'FR', 'MONCE EN BELIN', NULL, 'edtrans@example.com'),
  ('EGLI AG Process Technology', 'Wilerstrasse 7', NULL, '9606', 'CH', 'Bütschwil', '+41 71 982 88 00', 'info@egliag.com'),
  ('ELH Waggonbau Niesky GmbH', 'Am Waggonbau 11', NULL, '2906', 'DE', 'Niesky', NULL, 'elhwaggonbaunieskygm@example.com'),
  ('ELOS Speditions GmbH - Projektspedition Berlin', 'Storkower Straße 113', NULL, '10407', 'DE', 'Berlin', NULL, 'elosspeditionsgmbhpr@example.com'),
  ('EM Golfplatz/Management GmbH', 'Renkenstr. 12', NULL, '82266', 'DE', 'Inning am Ammersee', NULL, 'emgolfplatzmanagemen@example.com'),
  ('EMEF-Energie', 'Hauptstraße 371', NULL, '53639', 'DE', 'Königswinter', '02223/7922070', 'info@emef-energie.de'),
  ('EMINIA TRADING GmbH', 'Gernotstrasse 16', NULL, '44319', 'DE', 'Dortmund', NULL, 'eminiatradinggmbh@example.com'),
  ('EMO-TRANS GmbH', 'Raiffeisenstr. 30', NULL, '70794', 'DE', 'Filderstadt', NULL, 'emotransgmbh@example.com'),
  ('EMO-TRANS GmbH', 'Huettruper Heide 88', NULL, '48268', 'DE', 'Greven', '+49 (0) 2571-916616', 'info@emo.de'),
  ('ENEOP 3', 'Avenida Cabo Verde No 36', NULL, '4900-568', 'PT', 'Viana do Castelo', NULL, 'eneop3@example.com'),
  ('ENERCON GMBH', 'Via Carlo Veneziani N 58', NULL, '148', 'IT', 'Roma RM', NULL, 'enercongmbh@example.com'),
  ('ENERCON GmbH Greek Branch', '49A L. Doukissis Plakentias', NULL, '152 34', 'GR', 'Chalandri-Athens', '+30 210 683 84 90', 'enercongmbhgreekbran@example.com'),
  ('ENERCON GmbH Sucursal PT', 'Avenida de Cabo Verde 36', NULL, '4900-568', 'PT', 'Viana do Castelo', NULL, 'enercongmbhsucursalp@example.com'),
  ('ENERCON Logistic GmbH', 'Holzweg 87', NULL, '26605', 'DE', 'Aurich', '+49 49 41 927-0', 'info@enercon.de'),
  ('ENERCON WindEnergy Pvt.Ltd.', 'Bellary Road', NULL, '560092', 'IN', 'Bengaluru', NULL, 'enerconwindenergypvt@example.com'),
  ('ERFURT & Sohn KG', 'Hugo-Erfurt-Straße 1', NULL, '42399', 'DE', 'Wuppertal', '+49 202 6110 353', 'G.Ensabella@erfurt.com'),
  ('EURO-Masten GmbH', 'Spenglerstraße 89', NULL, '23556', 'DE', 'Lübeck', '0451 79 10 75', 'k.zielke@euromasten.de'),
  ('EVG Edelstahlvertriebsgesellschaft mbH', 'Otto-Stoelcker-Str. 37', NULL, '35066', 'DE', 'Frankenberg', NULL, 'evgedelstahlvertrieb@example.com'),
  ('Eesti Kultuuriministeerium', 'Suur-Karja 23', NULL, '10148', 'EE', 'Tallinn', NULL, 'eestikultuuriministe@example.com'),
  ('Elis München GmbH', 'Stahlgruberring 19', NULL, '81829', 'DE', 'München', NULL, 'elismnchengmbh@example.com'),
  ('Elke Höver - Höver-Papertrade', 'Bleckering 14', NULL, '22119', 'DE', 'Hamburg', NULL, 'elkehverhverpapertra@example.com'),
  ('Eltrans Plus GmbH', 'Manteuffelstrasse 21', NULL, '22587', 'DE', 'Hamburg', NULL, 'eltransplusgmbh@example.com'),
  ('Emerson', 'Heisenbergbogen 2', NULL, '85609', 'DE', 'Aschheim', '089 21547800', 'emerson@example.com'),
  ('Emil Frey Exklusive Cars GmbH', 'Moosacher Straße 56', NULL, '80809', 'DE', 'München', NULL, 'emilfreyexklusivecar@example.com'),
  ('Emons Spedition GmbH & Co. KG', 'Lindberghstraße 6', NULL, '85399', 'DE', 'Hallbergmoos', NULL, 'emonsspeditiongmbhco@example.com'),
  ('Emsdettener Eisenhandlung GmbH', 'Wilmersstraße 34', NULL, '48282', 'DE', 'Emsdetten', NULL, 'emsdettenereisenhand@example.com'),
  ('Enercon GmbH', 'Dreekamp 5', NULL, '26605', 'DE', 'Aurich', NULL, 'thomas.endelmann@enercon.de'),
  ('Engelmann Turf Care GmbH', 'Keltenring 11', NULL, '82041', 'DE', 'Oberhaching', NULL, 'engelmannturfcaregmb@example.com'),
  ('Erdem Aktar Transporte', 'Kysostr. 1', NULL, '85301', 'DE', 'Schweitenkirchen', NULL, 'erdemaktartransporte@example.com'),
  ('Erich Czulkowski GmbH', 'Kreuzerwiese 3', NULL, '56290', 'DE', 'Dommershausen', NULL, 'erichczulkowskigmbh@example.com'),
  ('Erich Czulkowski GmbH Zweigniederlassung Düsseldorf', 'Henkelstraße 67', NULL, '40589', 'DE', 'Düsseldorf', NULL, 'erichczulkowskigmbhz@example.com'),
  ('Ernst Weinzierl', 'Brückenstr.5', NULL, '84137', 'DE', 'Vilsbiburg', NULL, 'ernstweinzierl@example.com'),
  ('Essendorfer Genussschmelzerei GmbH', 'Bayrischzeller Straße 11', NULL, '83727', 'DE', 'Schliersee', NULL, 'essendorfergenusssch@example.com'),
  ('EuTech Europa Technology', 'An der Riede 5', NULL, '38110', 'DE', 'Braunschweig', NULL, 'eutecheuropatechnolo@example.com'),
  ('Exponex s.r.o.', 'Janou?kova 2015/1a', NULL, '613 00', 'CZ', 'Brno ? ?erná Pole', NULL, 'exponexsro@example.com'),
  ('Express Group, a.s.', 'Plynárenská 7/B', NULL, '82109', 'SK', 'Bratislava', NULL, 'expressgroupas@example.com'),
  ('F.H. Bertling Logistics Aberdeen Ltd.', 'Ground Floor, 166 College Road', NULL, 'HA1 1BH', 'UK', 'Harrow, Middlesex', NULL, 'fhbertlinglogisticsa@example.com'),
  ('F.H. Bertling Logistics Georgia LLC', 'Room 4, 8th Floor, Green Office, 154 Agmashenebeli Avenue', NULL, '112', 'GE', 'Tbilisi', NULL, 'fhbertlinglogisticsg@example.com'),
  ('FAME Logistics & Trade GmbH', 'Gebrüder-Wright-Str. 4', NULL, '60486', 'DE', 'Frankfurt am Main', NULL, 'famelogisticstradegm@example.com'),
  ('FLIESEN MAUZ GMBH', 'Dekan-Laist-Str. 48', NULL, '55129', 'DE', 'Mainz', NULL, 'fliesenmauzgmbh@example.com'),
  ('FMCG Nederland B.V.', 'Maasstraat 24', NULL, '6049', 'NL', 'CC Herten', NULL, 'fmcgnederlandbv@example.com'),
  ('FREO Financial & Real Estate Operations GmbH', 'Jungfernturmstrasse 2', NULL, '80333', 'DE', 'München', NULL, 'freofinancialrealest@example.com'),
  ('FSO GmbH & Co.KG', 'Friedrich-Wöhler-Str. 8', NULL, '64579', 'DE', 'Gernsheim', NULL, 'fsogmbhcokg@example.com'),
  ('FUCHS Bau GmbH', 'Dorstener Straße 1', NULL, '9661', 'DE', 'Hainichen', NULL, 'fuchsbaugmbh@example.com'),
  ('Fagioli S.p.A.', 'Via Ferraris 13', NULL, '42049', 'IT', 'S. Ilario D''Enza (RE)', NULL, 'fagiolispa@example.com'),
  ('Fantastiqu Trade GmbH', 'Hagenmüllergasse 22/35', NULL, '1030', 'AT', 'Wien', NULL, 'fantastiqutradegmbh@example.com'),
  ('Fast truck solution UG (haftungsbeschränkt)', 'Langer Kornweg 34 D', NULL, '65451', 'DE', 'Kelsterbach', NULL, 'fasttrucksolutionugh@example.com'),
  ('Fast''n Easy GmbH', 'Am Sommerfeld 1', NULL, '85646', 'DE', 'Anzing', NULL, 'fastneasygmbh@example.com'),
  ('Ferntrans internationale Speditions-GmbH', 'Frankenwaldstr. 27 ? 29', NULL, '95152', 'DE', 'Selbitz', '+49 9280 98 300', 'info@spedition-ferntrans.de'),
  ('Filgertshofer Alois', 'Marktstraße 55', NULL, '83646', 'DE', 'Bad Tölz', '+49 172 72 31 31 6', 'Alois.Filgertshofer@fimax.de'),
  ('Finow Rohrsysteme GmbH', 'Angermünder str. 101', NULL, '16225', 'DE', 'Eberswalde', NULL, 'finowrohrsystemegmbh@example.com'),
  ('Florian Haller - Pawpawschule', 'Mühlweg 6', NULL, '82544', 'DE', 'Egling', NULL, 'florianhallerpawpaws@example.com'),
  ('Formlos GmbH', 'Siebengebirgsallee 188', NULL, '50939', 'DE', 'Köln', NULL, 'wachsmann@formlos.com'),
  ('Formteilbau Schmitt GmbH & Co. KG', 'Schönauer Weg 20', NULL, '97783', 'DE', 'Karsbach', NULL, 'formteilbauschmittgm@example.com'),
  ('Forstner Glass+ GmbH', 'Franz-Kollmann-Str. 4', NULL, '33000', 'AT', 'Amstetten', NULL, 'forstnerglassgmbh@example.com'),
  ('Frank Vermögensverwaltungsgesellschaft mbH', 'Kurfürstendamm 124', NULL, '10711', 'DE', 'Berlin', NULL, 'frankvermgensverwalt@example.com'),
  ('Franka Emika GmbH', 'Frei-Otto-Straße 20', NULL, '80797', 'DE', 'München', NULL, 'frankaemikagmbh@example.com'),
  ('Fraunhofer IWES', 'Am Seedeich 45', NULL, '27572', 'DE', 'Bremerhaven', NULL, 'fraunhoferiwes@example.com'),
  ('Freiburger Hochbau Nord GmbH', 'Berta-Ottenstein-Straße 11', NULL, '79106', 'DE', 'Freiburg im Breisgau', NULL, 'freiburgerhochbaunor@example.com'),
  ('Friedrich Köster GmbH & Co. KG Maschinenfabrik + Gießerei', 'Friedrichswerk 1 - 7', NULL, '25746', 'DE', 'Heide', '0481-797 225', 'friedrichkstergmbhco@example.com'),
  ('Fructus sp. z o.o', 'Maszewska 15', NULL, '72-100', 'PL', 'Goleniów', NULL, 'fructusspzoo@example.com'),
  ('Fürmetz Logistik GmbH', 'Kirchlern 4', NULL, '84416', 'DE', 'Taufkirchen (Vils)', NULL, 'frmetzlogistikgmbh@example.com'),
  ('G. Eichenwald GmbH & Co. KG', 'Ruhrstraße 60', NULL, '41469', 'DE', 'Neuss', '02137 / 91787-0', 'ideal@eichenwald.de'),
  ('GARDA METAL WORKS POLSKA Sp. z o.o.', 'ulica Miedziana 16B', NULL, '59-100', 'PL', 'Polkowice', NULL, 'gardametalworkspolsk@example.com'),
  ('GBM GLEISSBAUMECHANIK BRANDENBURG/H.', 'Adlerstraße 2', NULL, '14774', 'DE', 'Brandenburg an der Havel', '+49033818044110', 'gbmgleissbaumechanik@example.com'),
  ('GEBAS GmbH', 'Glescher Straße 126', NULL, '50126', 'DE', 'Bergheim', NULL, 'gebasgmbh@example.com'),
  ('GEODIS CL Germany GmbH', 'Colmarer Str. 11', NULL, '60528', 'DE', 'Frankfurt am Main', '+49 6106 2680 5310', 'rechnungseingang1-glde@geodis.com'),
  ('GHH Fahrzeuge GmbH', 'Emscherstr. 53', NULL, '45891', 'DE', 'Gelsenkirchen', NULL, 'ghhfahrzeugegmbh@example.com'),
  ('GKDS', 'Hansastraße 12-16', NULL, '80686', 'DE', 'München', NULL, 'gkds@example.com'),
  ('GKM Services GmbH', 'Felix Wankel Str. 11', NULL, '74915', 'DE', 'Waibstadt', '+49 (7263) 40972-0', 'info@gkm-group.com'),
  ('GKM Siebtechnik GmbH', 'Felix Wankel Straße 11', NULL, '74915', 'DE', 'Waibstadt', '+49 (7263) 40972-0', 'info@gkm-group.com'),
  ('GLEAM Technologies GmbH', 'Markhofgasse 19/1.OG', NULL, '1030', 'AT', 'Wien', NULL, 'gleamtechnologiesgmb@example.com'),
  ('GNS Georgia LTD.', '12 Merab Aleksidze Street, 6th Floor', NULL, '171', 'GE', 'Tbilisi', NULL, 'gnsgeorgialtd@example.com'),
  ('GOLDBECK Süd GmbH', 'Anna-Sigmund-Straße 2-4', NULL, '82061', 'DE', 'Neuried', NULL, 'goldbecksdgmbh@example.com'),
  ('GOP Entertainment Group GmbH & Co. KG', 'Im Kurgarten 8', NULL, '32545', 'DE', 'Bad Oeynhausen', NULL, 'gopentertainmentgrou@example.com'),
  ('GOP Showconcept GmbH & Co. KG', 'Georgstraße 36', NULL, '30159', 'DE', 'Hannover', '+ 49 (0) 521 3299 250', 'info@variete.de'),
  ('GTH Green-Stores Handels UG & Co. KG', 'Thyssenstraße 6', NULL, '32312', 'DE', 'Lübbecke', NULL, 'gthgreenstoreshandel@example.com'),
  ('Gallafilz GmbH', 'Residenzstraße 27', NULL, '80333', 'DE', 'München', NULL, 'gallafilzgmbh@example.com'),
  ('Gebert & Gebert Sanitär und Heizungsbau GmbH', 'Josefsstrasse 2', NULL, '51789', 'DE', 'Lindlar', NULL, 'gebertgebertsanitrun@example.com'),
  ('Gebrüder Schneller GmbH & Co. KG', 'Im Kreuz 11', NULL, '97076', 'DE', 'Würzburg', '+49 931 27988-11', 'B.Zimmer@gebrueder-schneller.de'),
  ('Geis Air + Sea GmbH', 'Mattentwiete 8', NULL, '20457', 'DE', 'Hamburg', NULL, 'geisairseagmbh@example.com'),
  ('Gemeinde Eichenau', 'Hauptplatz 2', NULL, '82223', 'DE', 'Eichenau', NULL, 'gemeindeeichenau@example.com'),
  ('Generator Produkcja Opole Sp.z.o.o', 'ul. O?wi?cimska 102E', NULL, '45641', 'PL', 'Opole', NULL, 'generatorprodukcjaop@example.com'),
  ('Gerish GmbH', 'Konstantinstraße 16', NULL, '41238', 'DE', 'Mönchengladbach', NULL, 'gerishgmbh@example.com'),
  ('Gertzen Transportlogistik GmbH & Co.KG', 'Pollertstraße 44', NULL, '26892', 'DE', 'Kluse / Ahlen', NULL, 'gertzentransportlogi@example.com'),
  ('Gharieni Group GmbH', 'Am Schürmannshütt 24', NULL, '47441', 'DE', 'Moers', '+49 (0) 2841 – 88 300-50', 'info@gharieni.com'),
  ('Gianti logistics LTD', 'Gulia Square 4/2', NULL, '114', 'GE', 'Tbilisi', NULL, 'giantilogisticsltd@example.com'),
  ('Glaß & Wolff Metalltechnik GmbH & Co. KG', 'Böttcherstraße 4', NULL, '27404', 'DE', 'Zeven', NULL, 'e.ehmke@glass-wolff.de'),
  ('Global Treats GmbH', 'St.-Antonius-Straße 1', NULL, '79793', 'DE', 'Wutöschingen', NULL, 'info@vernaschediewelt.com'),
  ('Globalsped GmbH', 'Pendelhagen 1', NULL, '83416', 'DE', 'Saaldorf-Surheim', NULL, 'globalspedgmbh@example.com'),
  ('Gorges tent...event GmbH & Co. KG', 'Eifelstrasse 34', NULL, '56759', 'DE', 'Laubach', NULL, 'gorgestenteventgmbhc@example.com'),
  ('Gorilla Deutschland GmbH', 'Sauerlacher Straße 54A', NULL, '82515', 'DE', 'Wolfratshausen', NULL, 'tasso@letsgogorilla.de'),
  ('Granar GmbH', 'Lindenallee 25a', NULL, '42899', 'DE', 'Remscheid', '02191 460 56 60', 'info@granar.de'),
  ('Green City e. V.', 'Lindwurmstr. 88', NULL, '80337', 'DE', 'München', NULL, 'greencityev@example.com'),
  ('Greenwood Group Ltd - Greenwood Nursery', 'Church Road, Aldingbourne', NULL, 'PO2 3TU', 'UK', 'Chichester', NULL, 'greenwoodgroupltdgre@example.com'),
  ('GridParity AG', 'Ohmstr. 7', NULL, '85757', 'DE', 'Karlsfeld', NULL, 'gridparityag@example.com'),
  ('Güray Karabacak Sicherheit und Service', 'Melchiorstr. 48', NULL, '81479', 'DE', 'München', NULL, 'graykarabacaksicherh@example.com'),
  ('Güttler Logistik GmbH', 'Dieselstraße 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'herbert.brunner@guettlerlogistik.de'),
  ('Güttler Logistik GmbH', 'Fuhrmannstraße 8', NULL, '95013', 'DE', 'Hof/Saale', NULL, 'gttlerlogistikgmbh@example.com'),
  ('HAROSYSTEM, Inh. Samy Hadj Amor', 'Röntgenstraße 8', NULL, '40699', 'DE', 'Erkrath', NULL, 'info@haro-system.com'),
  ('HAUBNER Systembau GmbH', 'Am Kornfeld 5', NULL, '92318', 'DE', 'Neumarkt in der Oberpfalz', NULL, 'haubnersystembaugmbh@example.com'),
  ('HBB Centermanagement GmbH & Co. KG', 'Theresienhöhe 5', NULL, '80339', 'DE', 'München', NULL, 'hbbcentermanagementg@example.com'),
  ('HBB Gewerbebau Projektgesellschaft Forum Hanau mbH & Co. KG', 'Brooktorkai 22', NULL, '20457', 'DE', 'Hamburg', '+49 (6181) 91 95 7 23', 'invoice@hbb.de'),
  ('HL HAMBURGER LEISTUNGSFUTTER GmbH', 'Konsul-Ritter-Str. 3', NULL, '21079', 'DE', 'Hamburg', '+49 (0)40/76692-0', 'allgemein@ibeka.com'),
  ('HPF Energy Services', '3 Kinwarton Farm Road, Arden Forest Industrial Estate, Alcester', NULL, 'B49 6EH', 'UK', 'Warwickshire', NULL, 'hpfenergyservices@example.com'),
  ('Haka Trans Spedition und Handels GmbH', 'Dieselstrasse 21', NULL, '85748', 'DE', 'Garching bei München', NULL, 'hakatransspeditionun@example.com'),
  ('Hamm AG', 'Hammstr. 1', NULL, '95643', 'DE', 'Tirschenreuth', '+49 9631 800', 'info@hamm.eu'),
  ('Hans-Jürgen Müller', 'Lecherwiese 10', NULL, '83620', 'DE', 'Feldkirchen-Westerham', NULL, 'hansjrgenmller@example.com'),
  ('Harsco Rail Europe GMBH', 'Lütticher Straße 130', NULL, '40547', 'DE', 'Dusseldorf', NULL, 'harscoraileuropegmbh@example.com'),
  ('Hasslacher Drauland Holzindustrie GmbH', 'Feistritz 1', NULL, '9751', 'AT', 'Sachsenburg', '+43 4769 22 49 - 0', 'info@hasslacher.com'),
  ('Hatice Schmidt GmbH', 'Schönstedtstraße 7', NULL, '12043', 'DE', 'Berlin', NULL, 'haticeschmidtgmbh@example.com'),
  ('Haubner Holding GmbH', 'Am Kornfeld 5', NULL, '92318', 'DE', 'Neumarkt in der Oberpfalz', NULL, 'haubnerholdinggmbh@example.com'),
  ('Haus Flammberg Seniorenresidenz GmbH', 'Karolinenstraße 1-3', NULL, '59759', 'DE', 'Arnsberg', '+49 (0) 2932/484-3114', 'hausflammbergseniore@example.com'),
  ('Haus Linde Senioren- und Pflegeheim GmbH', 'Heinrich-Steinweg-Straße 17', NULL, '38685', 'DE', 'Langelsheim', NULL, 'hauslindeseniorenund@example.com'),
  ('HeGo Biotec GmbH', 'Goerzallee 305 b', NULL, '14167', 'DE', 'Berlin', NULL, 'hegobiotecgmbh@example.com'),
  ('Heathrow Express', 'The Compass Centre, Nelson Road', NULL, 'TW6 2GW', 'UK', 'Hounslow, Middlesex.', NULL, 'heathrowexpress@example.com');