-- Part 4/5
-- Customers 412 to 548 (137 total)

INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('MegaSauna GmbH', 'Otto-Hahn-Str. 4', NULL, '27283', 'DE', 'Verden (Aller)', NULL, 'megasaunagmbh@example.com'),
  ('Meil Keramik & Natursteinbau GmbH', 'Karl-Benz-Str. 18', NULL, '85221', 'DE', 'Dachau', NULL, 'meilkeramiknaturstei@example.com'),
  ('Meissner Bolte Patentanwälte Rechtsanwälte Partnerschaft mbB', 'Widenmayerstr. 47', NULL, '80538', 'DE', 'München', NULL, 'meissnerboltepatenta@example.com'),
  ('Michael Ages', 'Pfaffenpfädchen 15', NULL, '51145', 'DE', 'Köln', NULL, 'michaelages@example.com'),
  ('Michael Pendry mixed media art', 'Nymphenburger Str. 108a', NULL, '80636', 'DE', 'München', NULL, 'michaelpendrymixedme@example.com'),
  ('Michael Szing', 'Voldering 6', NULL, '84405', 'DE', 'Dorfen', NULL, 'baukraftevent@gmx.de'),
  ('Milan Martinec', 'Kounicova 681/10', NULL, '60200', 'CZ', 'Brno', NULL, 'milanmartinec@example.com'),
  ('Misnak International (UK) Ltd', '22-24 Red Lion Court', NULL, 'EC4A 3EB', 'UK', 'London', NULL, 'misnakinternationalu@example.com'),
  ('Mitsch Gottfried', 'Am Richteranger 6', NULL, '83623', 'DE', 'Dietramszell', NULL, 'mitschgottfried@example.com'),
  ('MobilHybrid GmbH', 'Bürgermeister Wegele Straße 12', NULL, '86167', 'DE', 'Augsburg', '+49 157 83503438', 'info@mobilhybrid.de'),
  ('Mobilia Transport Sp. z o.o.', 'Ul. Spacerowa 1/5', NULL, '62-811', 'PL', 'Koscielna Wies', NULL, 'mobiliatransportspzo@example.com'),
  ('Mohiyadin Zada Rehabilitation & Construction Organisation', 'Charahi Qala e Nagara', NULL, NULL, 'AF', 'Kabul', NULL, 'mohiyadinzadarehabil@example.com'),
  ('Monsun GmbH', 'Olschewskibogen 4', NULL, '80935', 'DE', 'München', NULL, 'monsungmbh@example.com'),
  ('Montefish D.O.O.', 'Dumidran', NULL, '85320', 'ME', 'Tivat', NULL, 'nabavka@montefish.me'),
  ('Mortensen', 'Spaldingstrasse 64', NULL, '20097', 'DE', 'Hamburg', NULL, 'mortensen@example.com'),
  ('Mountain Sports Outlet GmbH', 'Reichenberger Str. 1', NULL, '84130', 'DE', 'Dingolfing', NULL, 'mountainsportsoutlet@example.com'),
  ('MulTim Consulting', 'Oktomvriska Revolucija 1/11', NULL, '1300', 'MK', 'Kumanovo', NULL, 'multimconsulting@example.com'),
  ('Multigear GmbH', 'Am Flugplatz 34', NULL, '56743', 'DE', 'Mendig', '+49 (0) 2652 93605 16', 'multigeargmbh@example.com'),
  ('Mursall GmbH & Co. KG', 'Lohwiese 9', NULL, '86937', 'DE', 'Scheuring', NULL, 'mursallgmbhcokg@example.com'),
  ('Mychecker24.de', 'Siemensstr. 3', NULL, '82178', 'DE', 'Puchheim', NULL, 'mychecker24de@example.com'),
  ('Märkische Faser GmbH', 'Grisuten Strasse 13', NULL, '14727', 'DE', 'Premnitz', '+49 3386 24 3155', 'marketing@maerkische-faser.com'),
  ('NATCO GmbH Internationale Spedition', 'Diepenau 2', NULL, '28195', 'DE', 'Bremen', NULL, 'natcogmbhinternation@example.com'),
  ('NEUE WOHNKULTUR classic + design GmbH', 'Königstrasse 20 + 22', NULL, '83022', 'DE', 'Rosenheim', NULL, 'neuewohnkulturclassi@example.com'),
  ('NEWFLOW Logistics sp. z o.o.', 'ulica Łużycka 2', NULL, '81-300', 'PL', 'Gdynia', NULL, 'newflowlogisticsspzo@example.com'),
  ('NLG (New Logistic Group)', 'Ana polytkovskaya Street #10, APT 32', NULL, '131', 'GE', 'Tiflis', NULL, 'nlgnewlogisticgroup@example.com'),
  ('NORDICA COFFEE GmbH', 'Rütersbarg 52', NULL, '22529', 'DE', 'Hamburg', '+49 040571 99893 0', 'info@nordica.coffee'),
  ('NOSTA Logistics GmbH', 'Akexander-Fleming-Str. 3', NULL, '68519', 'DE', 'Viernheim', '+49 (0) 6204 98685-44', 'dburst@nosta.de'),
  ('Nagel GmbH', 'Redcarstrasse 46b', NULL, '53842', 'DE', 'Troisdorf', '+49 (0) 22 41 – 973 53 43', 'info@nagel-manufaktur.com'),
  ('Nasa Telekommunikation GmbH', 'Vogelsanger Weg 39', NULL, '40470', 'DE', 'Düsseldorf', NULL, 'nasatelekommunikatio@example.com'),
  ('National Instruments Germany GmbH', 'Landsberger Straße 346', NULL, '80687', 'DE', 'München', NULL, 'info@ni.com'),
  ('Natur Faktor GmbH', 'Danziger Str. 62', NULL, '33605', 'DE', 'Bielefeld', NULL, 'naturfaktorgmbh@example.com'),
  ('Noerpel SE', 'Wilhelm-Kentner-Straße 1', NULL, '89520', 'DE', 'Heidenheim an der Brenz', '+49 7321 3508 2514', 'export-hdh@noerpel.de'),
  ('Nordic Logistics GmbH', 'Rotenhäuser Straße 19', NULL, '21109', 'DE', 'Hamburg', '+49 40 89723860', 'nils.bastar@nordiclogistics.de'),
  ('North South Logistics', 'Building 9, Irving street Causeway bay, Suite 2405, Progress commercial', NULL, NULL, 'HK', 'Hong Kong Island', NULL, 'northsouthlogistics@example.com'),
  ('OPERADOR LOGÌSTICO REYCO, S.L.', 'C/Uruguay, 11-3. A puerta 302', NULL, '46007', 'ES', 'Valencia', NULL, 'operadorlogsticoreyc@example.com'),
  ('OQEMA UAB', 'Veiveri? g. 139-301', NULL, '46360', 'LT', 'Kaunas', NULL, 'oqemauab@example.com'),
  ('OTS-Oberlausitzer Transportservice UG', 'Berlinerstr. 111', NULL, '2943', 'DE', 'Weißwasser', NULL, 'otsoberlausitzertran@example.com'),
  ('Oertli Ophthalmedic Deutschland GmbH', 'Otto-Wagner-Straße 1', NULL, '82110', 'DE', 'Germering', '+41 71747 42 00', 'info@oertli-instruments.com'),
  ('Olympiapark München GmbH', 'Spiridon-Louis-Ring 21', NULL, '80809', 'DE', 'München', NULL, 'olympiaparkmnchengmb@example.com'),
  ('Orango Creative', 'Am Steintor 52', NULL, '48167', 'DE', 'Münster', NULL, 'orangocreative@example.com'),
  ('Organifarms GmbH', 'Bücklestraße 3', NULL, '78467', 'DE', 'Konstanz', NULL, 'organifarmsgmbh@example.com'),
  ('Original BTC', 'Gärtnerplatz 1', NULL, '80469', 'DE', 'Munich', NULL, 'originalbtc@example.com'),
  ('Orion Express Sp. z o.o.', 'Jana Henryka Dabrowskiego 77A', NULL, '60-529', 'PL', 'Poznan', NULL, 'h.judkowiak@orionexpress.eu'),
  ('Oskar Frech GmbH + Co. KG', 'Schorndorfer Straße 32', NULL, '73614', 'DE', 'Schorndorf', NULL, 'oskarfrechgmbhcokg@example.com'),
  ('OuTao GmbH', 'Egglkofenstr. 8', NULL, '84453', 'DE', 'Mühldorf a. Inn', NULL, 'outaogmbh@example.com'),
  ('P.E.T. LOGISTICS GmbH', 'Dessauerstr. 60', NULL, '45472', 'DE', 'Mülheim an der Ruhr', NULL, 'petlogisticsgmbh@example.com'),
  ('PAAG TRANSPORT & LOGISTIC Spolka z o.o.,Sp.K.', 'ul. Czestochowska 2', NULL, '62-800', 'PL', 'Kalisz', NULL, 'paagtransportlogisti@example.com'),
  ('PENTA GmbH', 'Hans-Fischer-Str. 10-12', NULL, '80339', 'DE', 'München', NULL, 'pentagmbh@example.com'),
  ('PIA Pontis Institutional Advisors GmbH', 'Erika-Mann-Straße 7', NULL, '80636', 'DE', 'München', NULL, 'piapontisinstitution@example.com'),
  ('PREMIER FOODS GROUP LTD', 'PREMIER HOUSE, CENTRIUM BUSINESS  PARK', NULL, 'AL1 2RE', 'UK', 'ST ALBANS, HERTFORDSHIRE', NULL, 'premierfoodsgroupltd@example.com'),
  ('PRP Profile GmbH', 'Rahlstedter Str. 128', NULL, '22143', 'DE', 'Hamburg', NULL, 'prpprofilegmbh@example.com'),
  ('PUTZMEISTER Concrete Pumps GmbH', 'Max-Eyth-Str. 10', NULL, '72631', 'DE', 'Aichtal', NULL, 'putzmeisterconcretep@example.com'),
  ('Parkstrom GmbH', 'Karl-Marx-Allee 71', NULL, '10243', 'DE', 'Berlin', NULL, 'parkstromgmbh@example.com'),
  ('Patir Design GmbH', 'Dieselstrasse 18', NULL, '85386', 'DE', 'Eching b. München', NULL, 'patirdesigngmbh@example.com'),
  ('Permanent Entertainment GmbH', 'Reichenbachstraße 33', NULL, '80469', 'DE', 'München', NULL, 'permanententertainme@example.com'),
  ('Perzl-Systems', 'Alpenstr. 9', NULL, '81541', 'DE', 'München', NULL, 'perzlsystems@example.com'),
  ('Pfaff International GmbH', 'Schussentalstraße 15', NULL, '88255', 'DE', 'Baienfurt', NULL, 'pfaffinternationalgm@example.com'),
  ('Pflanzenhandel Lappen', 'Herrenpfad 14', NULL, '41334', 'DE', 'Nettetal', NULL, 'pflanzenhandellappen@example.com'),
  ('Pflegeheim Dresden Am Elbufer GmbH', 'Käthe-Kollwitz-Ufer 4', NULL, '01307', 'DE', 'Dresden', '+49 (0)351/652 86 81-22', 'pflegeheimdresdename@example.com'),
  ('Pflegeheim Pulsnitz GmbH', 'Bahnhofstraße 5', NULL, '01896', 'DE', 'Pulsnitz', NULL, 'pflegeheimpulsnitzgm@example.com'),
  ('Pharmact GmbH', 'Theodor-Kutzer-Ufer 1-3', NULL, '68167', 'DE', 'Mannheim', NULL, 'pharmactgmbh@example.com'),
  ('Planttech Engineering GmbH', 'Louis-Berger-Weg 7', NULL, '59379', 'DE', 'Selm', '+49 (0) 25 92 / 91 505-0', 'Rechnungen@planttech.de'),
  ('Plus Construction GmbH', 'Schmielenfeldstr. 46', NULL, '45772', 'DE', 'Marl', NULL, 'plusconstructiongmbh@example.com'),
  ('Pnt Expo GmbH', 'Promenadenweg 5', NULL, '47809', 'DE', 'Krefeld', NULL, 'pntexpogmbh@example.com'),
  ('Polaris Handelsgesellschaft m.b.H.', 'Landstraßer Hauptstraße 146-148/16/B2', NULL, '1030', 'AT', 'Wien', NULL, 'dhuehne@polarisfamily.com'),
  ('Polwama sp. z o.o.', 'W?. Andersa 22/202', NULL, '75016', 'PL', 'Koszalin', NULL, 'polwamaspzoo@example.com'),
  ('President Dental GmbH', 'Kesselbodenstraße 5', NULL, '85391', 'DE', 'Allershausen', NULL, 'presidentdentalgmbh@example.com'),
  ('PrimoCargo GmbH', 'Rossweg 20', NULL, '20457', 'DE', 'Hamburg', NULL, 'primocargogmbh@example.com'),
  ('Prof. Dr. Gudrun Kadereit', 'Menzinger Str. 67', NULL, '80638', 'DE', 'München', NULL, 'profdrgudrunkadereit@example.com'),
  ('Prof. Michael Bohnet', 'Leibnizstr. 59', NULL, '53177', 'DE', 'Bonn', NULL, 'profmichaelbohnet@example.com'),
  ('Proje Kargo Taşımacılık Ltd. Şti.', 'Ertuğrul Gazi Sokak', NULL, '34758', 'TR', 'Ataşehir', NULL, 'projekargotamaclkltd@example.com'),
  ('Projekt Dagobah', 'Eichhornstr. 17', NULL, '50735', 'DE', 'Köln', NULL, 'projektdagobah@example.com'),
  ('Q&D Services und Handels GmbH', 'Sankt-Peter-Straße 5', NULL, '72760', 'DE', 'Reutlingen', NULL, 'qdservicesundhandels@example.com'),
  ('Q-railing Central Europe GmbH', 'Marie-Curie-Str. 8-14', NULL, '46446', 'DE', 'Emmerich am Rhein', NULL, 'qrailingcentraleurop@example.com'),
  ('QEMETICA S.A.', 'Wspólna 62', NULL, '00-684', 'PL', 'Warszawa', '+48 22 639 11 00', 'IOD@qemetica.com'),
  ('QRC Management Consulting GmbH', 'Brahmsstr. 24a', NULL, '81677', 'DE', 'München', NULL, 'qrcmanagementconsult@example.com'),
  ('RENK GmbH', 'Rodder Damm 170', NULL, '48432', 'DE', 'Rheine', '+49 821 5700-0', 'info@renk.com'),
  ('ROIMEX', 'Robert-Koch-Str. 2', NULL, '82152', 'DE', 'Planegg', NULL, 'roimex@example.com'),
  ('ROTT Industrie GmbH & Co.KG', 'Kalkgrub 1-2', NULL, '84427', 'DE', 'Sankt Wolfgang', '+49 (0)8085 - 93 88 - 0', 'info@rott-group.com'),
  ('RUBBLE MASTER HMH GmbH', 'Im Südpark 196', NULL, '4030', 'AT', 'Linz', NULL, 'rubblemasterhmhgmbh@example.com'),
  ('RUKU Sauna-Manufaktur GmbH & Co. KG', 'Dietenheimer Str. 39', NULL, '89257', 'DE', 'Illertissen', NULL, 'rukusaunamanufakturg@example.com'),
  ('RWE Power AG', 'Zum Gut Bohlendorf', NULL, '50126', 'DE', 'Bergheim', NULL, 'rwepowerag@example.com'),
  ('RWE Power Aktiengesellschaft', 'RWE-Platz 2', NULL, '45141', 'DE', 'Essen', NULL, 'rwepoweraktiengesell@example.com'),
  ('Radsatz089 GmbH', 'Situlistraße 24', NULL, '80939', 'DE', 'München', NULL, 'info-radsatz089@gmx.de'),
  ('Rainer Butzmann', 'Fuggerstrasse 6', NULL, '81373', 'DE', 'München', NULL, 'rainerbutzmann@example.com'),
  ('Ralf Pfeffer', 'Liebigstraße 255', NULL, '50739', 'DE', 'Köln', NULL, 'ralfpfeffer@example.com'),
  ('Rangel Transitarios, S.A.', 'Rua da Serra, 654 Folgosa (Maia) - Aprtado 1192', NULL, '4446-909', 'PT', 'Ermesinde', NULL, 'rangeltransitariossa@example.com'),
  ('Refratechnik Steel GmbH', 'Am Seestern 5', NULL, '40547', 'DE', 'Düsseldorf', NULL, 'refratechniksteelgmb@example.com'),
  ('Regalsystem GmbH', 'Gyuru str 12/a', NULL, '4033', 'HU', 'Debrecen', NULL, 'regalsystemgmbh@example.com'),
  ('Regatta GmbH', 'Reichenberger Str. 1', NULL, '84130', 'DE', 'Dingolfing', NULL, 'regattagmbh@example.com'),
  ('Rhenus Freight East GmbH', 'Messenhäuser Straße 18', NULL, '63128', 'DE', 'Dietzenbach', '+49 40 280 044 921', 'rhenusfreighteastgmb@example.com'),
  ('Rhenus Freight Logistics GmbH & Co. KG', 'Dieselstrasse 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'rhenusfreightlogisti@example.com'),
  ('Richard Wagner GmbH & Co. KG Spedition', 'Heinrich-Hertz-Str. 8', NULL, '92224', 'DE', 'Amberg', '+49 (0)9621 7720-0', 'info@wagner-spedition.de'),
  ('Riedel Filtertechnik GmbH', 'Westring 83', NULL, '33818', 'DE', 'Leopoldshöhr', NULL, 'riedelfiltertechnikg@example.com'),
  ('Riedl Aufzugbau GmbH & Co. KG', 'Sonnenstraße 24', NULL, '85622', 'DE', 'Feldkirchen', '+49 89 90001 0', 'info@riedl-aufzuege.de'),
  ('Riekewald Niels', 'Rütersbarg 52', NULL, '22529', 'DE', 'Hamburg', NULL, 'edgaras.murnikas@sirum.de'),
  ('RoMiro GmbH', 'Seumestrasse 8', NULL, '22089', 'DE', 'Hamburg', NULL, 'romirogmbh@example.com'),
  ('Robert Krebs GmbH', 'Buschwerder Hauptdeich 5-9', NULL, '21107', 'DE', 'Hamburg', NULL, 'robertkrebsgmbh@example.com'),
  ('Robert Kukla GmbH', 'Kochelseestraße 8-10', NULL, '81371', 'DE', 'München', NULL, 'robertkuklagmbh@example.com'),
  ('Rollo Solar Melichar GmbH', 'Josef-Janker-Ring 18', NULL, '83646', 'DE', 'Bad Tölz', '+49 8041 792650', 'info@rollo-solar.de'),
  ('Rondo Food GmbH & Co. KG', 'Magdeburger Straße 65', NULL, '47800', 'DE', 'Krefeld', '+49 2151 44 12-0', 'contact@rondo-food.de'),
  ('Rowema AG', 'Im Schörli 17', NULL, '8600', 'CH', 'Dübendorf', NULL, 'rowemaag@example.com'),
  ('Ruoheng Dong', 'Egglkofenstr.8', NULL, '84453', 'DE', 'Mühldorf', NULL, 'ruohengdong@example.com'),
  ('S.C. ROUTIER European Transport S.R.L.', 'Gil?u 1334', NULL, '407310', 'RO', 'Gil?u', NULL, 'scroutiereuropeantra@example.com'),
  ('S2 GmbH', 'Am Heiligenberg 2b', NULL, '69488', 'DE', 'Birkenau', NULL, 'bauen@s2-architektur.com'),
  ('SC PROCONEX SRL', 'Str. Calea Adevarului  nr. 111A', NULL, NULL, 'RO', 'Oradea jud.Bihor', NULL, 'scproconexsrl@example.com'),
  ('SCHMIDT-HOFMANN GmbH & Co. KG', 'Industriestraße 5', NULL, NULL, 'DE', 'Rugendorf', NULL, 'schmidthofmanngmbhco@example.com'),
  ('SEATRADER Speditionsgesellschaft mbH', 'Mittelwendung 27', NULL, '28844', 'DE', 'Weyhe', '+49 (0) 4218 84 96 20', 'office@seatrader.de'),
  ('SEELING TRANSPORTLOGISTIK', 'Gothaerstr. 4', NULL, '40880', 'DE', 'Ratingen', NULL, 'seelingtransportlogi@example.com'),
  ('SENATOR INTERNATIONAL Spedition GmbH', 'Obenhauptstraße 13', NULL, '22335', 'DE', 'Hamburg', NULL, 'senatorinternational@example.com'),
  ('SENATOR INTERNATIONAL Spedition GmbH', 'Marienbergstr. 94', NULL, '90411', 'DE', 'Nürnberg', NULL, 'senatorinternational@example.com'),
  ('SENSO Süd GmbH', 'Industriering Ost 72', NULL, '47906', 'DE', 'Kempen', NULL, 'sensosdgmbh@example.com'),
  ('SFBAAM, LLC', 'Adams Ave 2130', NULL, '94577-1010', 'US', 'San Leandro', NULL, 'sfbaamllc@example.com'),
  ('SMS Spedition Management Service GmbH', 'Luftfrachtzentrum 610/2', NULL, '70629', 'DE', 'Stuttgart', NULL, 'smsspeditionmanageme@example.com'),
  ('SOKO Tierschutz e.V', 'Bodenehrstr. 20', NULL, '813737', 'DE', 'München', NULL, 'sokotierschutzev@example.com'),
  ('SPEDICAM & LOGISTIK GMBH', 'Hamburger Str. 70', NULL, '90451', 'DE', 'Nürnberg', NULL, 'spedicamlogistikgmbh@example.com'),
  ('SPS Schwimmbad & Pool Service GmbH', 'Eike-Kerstein-Straße 4', NULL, '31789', 'DE', 'Hameln', NULL, 'Marie.Dannat@binder24.com'),
  ('SPSC GmbH', 'Neumarkter Strasße 34', NULL, '81673', 'DE', 'München', NULL, 'spscgmbh@example.com'),
  ('STL Logistik GmbH', 'Lütticher Straße 12', NULL, '53842', 'DE', 'Troisdorf', '+49 2241 493 00 15', 'info@stl-logistik.com'),
  ('STRABAG Großprojekte GmbH', 'Leopoldstr. 250c', NULL, '80807', 'DE', 'München', NULL, 'strabaggroprojektegm@example.com'),
  ('STRABAG Großprojekte GmbH', 'Auftrag: IFORU DE / Rechnungen', NULL, '69966', 'DE', 'Mannheim', NULL, 'strabaggroprojektegm@example.com'),
  ('SWM Versorgungs GmbH', 'Emmy-Noether-Str. 2', NULL, '80992', 'DE', 'München', NULL, 'swmversorgungsgmbh@example.com'),
  ('Sabbagh & Hejjazi Gbr', 'Im Neubruch 13', NULL, '82211', 'DE', 'Herrsching am Ammersee', NULL, 'sabbaghhejjazigbr@example.com'),
  ('Sachsenland Transport & Logistik GmbH Dresden', 'Mülheimer Strasse 58', NULL, '47057', 'DE', 'Duisburg', NULL, 'sachsenlandtransport@example.com'),
  ('Sadarak', 'Qaradaq dstr, Lokbatan STV, Bilal Niftaliyev str. 45/60', NULL, '1063', 'AZ', 'Baku', NULL, 'sadarak@example.com'),
  ('Sandra Feldmann Ltd.', 'Flat #3 Gloria Place, Konstantinou Kalogera 137', NULL, '6021', 'CZ', 'Skala Larnaca', NULL, 'sandrafeldmannltd@example.com'),
  ('Sankurt Bau-und Tragwerksplanung GmbH', 'Hagener Str. 339', NULL, '44229', 'DE', 'Dortmund', NULL, 'sankurtbauundtragwer@example.com'),
  ('SanumTec GmbH', 'Georg-Knorr-Str. 1', NULL, '85662', 'DE', 'Hohenbrunn', '+49 (0) 4251 9352-0', 'info@sanum.com'),
  ('Sanyborn Hygiene Produkte', 'Brudermühlstr 46b', NULL, '81371', 'DE', 'München', NULL, 'sanybornhygieneprodu@example.com'),
  ('Sauna One GmbH', 'Große Schneede 8b', NULL, '29664', 'DE', 'Walsrode', '05161784340', 'megasauna@sauna-one.de'),
  ('Sawade GmbH', 'Wittestr. 26e', NULL, '13509', 'DE', 'Berlin', NULL, 'sawadegmbh@example.com'),
  ('Scantrans ApS', 'Håndværkervej 6', NULL, '6710', 'DK', 'Esbjerg', NULL, 'scantransaps@example.com'),
  ('Schach zu Dritt | Gesellschaft für Kommunikation mbH', 'Schinkestraße 9', NULL, '12047', 'DE', 'Berlin', NULL, 'schachzudrittgesells@example.com'),
  ('Schrauben-Bauer GmbH', 'Mittlerer Weg 3', NULL, '74080', 'DE', 'Heilbronn', NULL, 'schraubenbauergmbh@example.com'),
  ('Schreinerei Sigrüner', 'Am Gries 3', NULL, '84543', 'DE', 'Winhöring', '+49 176 28768842', 'Michlbauer.sara@sigruener.de'),
  ('Schub Global Logistik GmbH', 'Am Pestalozziring 14', NULL, '91058', 'DE', 'Erlangen', NULL, 'schubgloballogistikg@example.com'),
  ('SeaCurity GmbH', 'Walhallastraße 38', NULL, '80639', 'DE', 'München', '+49 89 12711526', 'info@seacurity.de');