-- Part 1/5
-- Customers 1 to 137 (137 total)

INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('089 Paletten - Paletten & Gitterboxen Handel', 'Hochmutting 1', NULL, '85764', 'DE', 'Oberschleißheim', NULL, '089palettenpaletteng@example.com'),
  ('270 Vision Ltd', 'Caxton Close, Unit 34 Basepoint Business Centre', NULL, 'SP10 3FG', 'UK', 'Andover', NULL, '270visionltd@example.com'),
  ('3ks profile gmbh', 'Asangstrasße 16', NULL, '94436', 'DE', 'Simbach', NULL, '3ksprofilegmbh@example.com'),
  ('ACTIV-IMMOBILIEN GmbH & Co. KG', 'Ferdinand-Dünkel-Straße 5', NULL, '88433', 'DE', 'Schemmerhofen', NULL, 'activimmobiliengmbhc@example.com'),
  ('ACUA Ocean Limited', '86-90 Paul Street, 3rd Floor', NULL, 'EC2A 4NE', 'UK', 'London', NULL, 'acuaoceanlimited@example.com'),
  ('ADRA Trans Adrian Swierczynski', 'Szpegawa Bukowa 17', NULL, '83-112', 'PL', 'Lubiszewo', NULL, 'adratransadrianswier@example.com'),
  ('AERIUS Marine GmbH', 'Lübecker Straße 128', NULL, '22087', 'DE', 'Hamburg', NULL, 'aeriusmarinegmbh@example.com'),
  ('AERVIDEO GmbH', 'Wolframstraße 24', NULL, '70191', 'DE', 'Stuttgart', NULL, 'aervideogmbh@example.com'),
  ('AGMG MUNICH GmbH', 'Hauptstraße 39', NULL, '85579', 'DE', 'Neubiberg', NULL, 'info@agmgmunich.com'),
  ('AGS Engineering Metalltechnik GmbH', 'Ernst-Wiss-Straße 18', NULL, '65933', 'DE', 'Frankfurt am Main', NULL, 'agsengineeringmetall@example.com'),
  ('AKDB', 'Hansastraße 12-16', NULL, '80686', 'DE', 'München', NULL, 'akdb@example.com'),
  ('AMBERGREEN FACILITIES SL', 'PLANTA 12-MOD.B, PASEO CASTELLANA 95 - EDIF.TORRE EUROPA', NULL, '28046', 'ES', 'Madrid', NULL, 'ambergreenfacilities@example.com'),
  ('AMBERGREEN SOLUTIONS SL.', 'C/ DELS FOGAINERS, 84', NULL, '46190', 'ES', 'Ribarroja del Turia, Valencia', NULL, 'ambergreensolutionss@example.com'),
  ('AMHAIMAR IT', 'Schäftlarnstr. 10 (Altes Kontorhaus)', NULL, '81371', 'DE', 'München', NULL, 'amhaimarit@example.com'),
  ('ANTS Logistic GmbH', 'Karl-Schmid-Ring 9', NULL, '07743', 'DE', 'Jena', '+49 3641 3279270', 'info@ants-log.de'),
  ('ARGE VisionBox', 'Fürstenrieder Straße 5', NULL, '80687', 'DE', 'München', NULL, 'argevisionbox@example.com'),
  ('AS Grundbesitz & Beteiligungen GmbH', 'Am Heidenknock 10', NULL, '95326', 'DE', 'Kulmbach', NULL, 'asgrundbesitzbeteili@example.com'),
  ('AS Stahlpartner GmbH', 'Frankfurter Straße  49', NULL, '61239', 'DE', 'Ober-Mörlen', NULL, 'asstahlpartnergmbh@example.com'),
  ('ASTRAN CARGO SERVICES', '519 New Hythe Lane. Larkfield', NULL, 'ME20 6SB', 'UK', 'Maidstone, Kent', NULL, 'astrancargoservices@example.com'),
  ('ASW Maschinenbau', 'Hasenäcker 13', NULL, '88142', 'DE', 'Wasserburg (Bodensee)', NULL, 'aswmaschinenbau@example.com'),
  ('AUC - Akademie der Unfallchirurgie GmbH', 'Wilhelm-Hale-Straße 46 B', NULL, '80639', 'DE', 'München', NULL, 'aucakademiederunfall@example.com'),
  ('AVANTGARDE Gesellschaft für Kommunikation mbH', 'Atelierstraße 10', NULL, '81671', 'DE', 'Munich', NULL, 'rechnungen.kom@avantgarde.de'),
  ('AZ Armaturen GmbH', 'Waldstrasse 7', NULL, '78087', 'DE', 'Mönchweiler', NULL, 'azarmaturengmbh@example.com'),
  ('Abrechnung', 'Rütersbarg 52', NULL, '22529', 'DE', 'Hamburg', NULL, 'abrechnung@example.com'),
  ('Adinotec AG', 'Hohenzollernstrasse 89', NULL, '80796', 'DE', 'München', NULL, 'adinotecag@example.com'),
  ('Adinotech GmbH', 'Salztorgasse 5/5/17', NULL, '1010', 'AT', 'Wien', NULL, 'adinotechgmbh@example.com'),
  ('AdlerTech GbR', 'An der Waldburg 15', NULL, '01816', 'DE', 'Bad Gottleuba-Berggießhübel', NULL, 'kontakt@adler-tech.de'),
  ('Aero Ruzgar End. A.S.', 'Ege Serbest Bölgesi', 'Zafer Sb Mah.Yalçın Yolu Cad.No.13', '35410', 'TR', 'Gaziemir', '+90 232 251 93 71', 'aeroruzgarendas@example.com'),
  ('Aktiv Assekuranz Makler GmbH', 'Hanauer Straße 67', NULL, '80993', 'DE', 'München', NULL, 'aktivassekuranzmakle@example.com'),
  ('Akudmedpharm GmbH', 'Kolpingstr. 9', NULL, '97332', 'DE', 'Volkach', NULL, 'norbert.seis@gmx.net'),
  ('Albert Kerbl GmbH', 'Felizenzell 9', NULL, '84428', 'DE', 'Buchbach', NULL, 'albertkerblgmbh@example.com'),
  ('Albert-Ludwigs-Universität Freiburg', 'Rempartstr. 15', NULL, '79085', 'DE', 'Freiburg im Breisgau', NULL, 'albertludwigsunivers@example.com'),
  ('Alfons Koester & Co. GmbH', 'Am Trippelsberg 43', NULL, '40589', 'DE', 'Düsseldorf', '+49/211/879646 – 36', 'alfonskoestercogmbh@example.com'),
  ('Ali Tuna', 'Hansestr. 63 A', NULL, '51149', 'DE', 'Köln', NULL, 'alituna@example.com'),
  ('Allgaier GmbH', 'Max-Eyth-Straße 20', NULL, '89231', 'DE', 'Neu-Ulm', '+49 (0) 731 97 44 0 707', 'allgaiergmbh@example.com'),
  ('Allsta Spedition GmbH', 'Industriestraße 37', NULL, '28199', 'DE', 'Bremen', NULL, 'allstaspeditiongmbh@example.com'),
  ('Alpha Industries GmbH & Co. KG, European Headquarters', 'Siemensstraße 11', NULL, '63263', 'DE', 'Neu-Isenburg', '+4915222659661', 'accounting@alphaindustries.eu'),
  ('Alphabet Fuhrparkmanagement GmbH', 'Lilienthalalle 26', NULL, '80786', 'DE', 'München', NULL, 'alphabetfuhrparkmana@example.com'),
  ('Alpinia Institute for Life Sciences AG', 'Bahnhofstrasse 34', NULL, '8880', 'CH', 'Walenstadt', NULL, 'alpiniainstituteforl@example.com'),
  ('Alpinia Laudanum GmbH', 'Wipplingerstraße 29/4', NULL, '1010', 'AT', 'Wien', NULL, 'alpinialaudanumgmbh@example.com'),
  ('Antiquariat Schneider-Henn', 'Mühlbachstr. 19', NULL, '82229', 'DE', 'Seefeld', NULL, 'antiquariatschneider@example.com'),
  ('Antiquitäten am Alten Hof', 'Sparkassenstraße 11', NULL, '80331', 'DE', 'München', NULL, 'antiquittenamaltenho@example.com'),
  ('ApfelKomm GmbH', 'Kaasgrabengasse 52/2/5', NULL, '1190', 'AT', 'Wien', NULL, 'apfelkommgmbh@example.com'),
  ('Aplus Steuerberater München Lyssoudis & Kugler PartGmbB', 'Im Regerhof, Welfenstr. 22', NULL, '81541', 'DE', 'München', NULL, 'can@aplus-steuerberater.de'),
  ('AquaSoli GmbH & CO. KG', 'Birkenleiten 41', NULL, '81543', 'DE', 'München', NULL, 'aquasoligmbhcokg@example.com'),
  ('Aritex Cading Deutschland GmbH', 'Edisonstrasse 23', NULL, '74076', 'DE', 'Heilbronn', NULL, 'aritexcadingdeutschl@example.com'),
  ('Arno Rosenlöcher GmbH & Co. KG', 'Dieselstraße 28', NULL, '85748', 'DE', 'Garching', NULL, 'arnorosenlchergmbhco@example.com'),
  ('AsstrA Forwarding AG', 'Staubstrasse 15', NULL, '8038', 'CH', 'Zürich', '+41 44 211 72 60', 'office@asstra.com'),
  ('Asstra UK LTD', '13 The Causeway, Teddington', NULL, 'TW11 0JR', 'UK', 'Teddington', '+44-203-908-5667', 'office@asstra.co.uk'),
  ('Atlant Transport', 'ulica Okólna 27', NULL, '66-400', 'PL', 'Gorzow Wielkopolski', NULL, 'atlanttransport@example.com'),
  ('Audio Reference GmbH', 'Alsterkrugchaussee 435', NULL, '22335', 'DE', 'Hamburg', NULL, 'audioreferencegmbh@example.com'),
  ('Auswärtiges Amt', 'Adenauerallee 99-103', NULL, '53113', 'DE', 'Bonn', NULL, 'auswrtigesamt@example.com'),
  ('Auto Magnus GmbH', 'Wasserbrugerlandstrasse 56', NULL, '81825', 'DE', 'München', NULL, 'automagnusgmbh@example.com'),
  ('Auvictum Erste Beteiligungs GmbH Seniorenresidenz Haus Seeufer', 'Bahnhofstraße 8-10', NULL, '59519', 'DE', 'Möhnesee', '+49 (0) 5272/391-415', 'auvictumerstebeteili@example.com'),
  ('Auvictum Zweite Beteiligungs GmbH', 'Kötztinger Straße 43', NULL, '94249', 'DE', 'Bodenmais', NULL, 'auvictumzweitebeteil@example.com'),
  ('B&E Internationale Logistik GmbH & Co. KG', 'Siemensstr. 4', NULL, '85716', 'DE', 'Unterschleißheim', NULL, 'beinternationalelogi@example.com'),
  ('B&L Property Management GmbH', 'Große Elbstraße 47', NULL, '22767', 'DE', 'Hamburg', NULL, 'blpropertymanagement@example.com'),
  ('BINDER GmbH & Co. KG', 'Eike-Kerstein-Straße 4', NULL, '31789', 'DE', 'Hameln', NULL, 'Paul.Alles@binder24.com'),
  ('BLG International Forwarding GmbH & Co. KG', 'Dieselstrasse 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'blginternationalforw@example.com'),
  ('BMW Group', 'Laaberstr. 7', NULL, '84130', 'DE', 'Dingolfing', '+49 8731 76-23803', 'stefan.wuerfel@bmw.de'),
  ('BOMAG GmbH', 'Hellerwald', NULL, '56154', 'DE', 'Boppard', NULL, 'bomaggmbh@example.com'),
  ('BOSPORUS Handelsgesellschaft mbH', 'Marktstr. 10 (AsmusHaus)', NULL, '50968', 'DE', 'Köln', NULL, 'bosporushandelsgesel@example.com'),
  ('BREB Schifffahrts GmbH & Co. KG MS Duhnen & c/o: Briese Schiffahrts Gmbh & Co. KG', 'Hafenstr. 12', NULL, '26789', 'DE', 'Leer', NULL, 'brebschifffahrtsgmbh@example.com'),
  ('BSH Hausgeräte GmbH', 'Carl-Wery-Straße 34', NULL, '81739', 'DE', 'Munich', NULL, 'bshhausgertegmbh@example.com'),
  ('BSP GmbH', 'Siebending 6', NULL, '9433', 'AT', 'Sankt Andrä', NULL, 'bspgmbh@example.com'),
  ('Barsan Global Logistik GmbH', 'Hertha-Sponer-Straße 1', NULL, '82216', 'DE', 'Maisach', NULL, 'barsangloballogistik@example.com'),
  ('Bartholet Maschinenbau AG', 'Lochriet', NULL, '8890', 'CH', 'Flums', NULL, 'bartholetmaschinenba@example.com'),
  ('BauKraftEvent', 'Bleichweg 5', NULL, '73485', 'DE', 'Unterschneidheim', NULL, 'baukraftevent@example.com'),
  ('Baumscheibenkontor', 'Agnes-Bernauer-Str. 1', NULL, '80687', 'DE', 'München', NULL, 'baumscheibenkontor@example.com'),
  ('Bavaria General Services GmbH', 'Bomhardstr. 7', NULL, '82031', 'DE', 'Grünwald', NULL, 'bavariageneralservic@example.com'),
  ('BayWa AG', 'Postfach 810106', NULL, '81901', 'DE', 'München', '+49 89 9222-0', 'baywaag@example.com'),
  ('Bayerische Landeszentrale für politische Bildungsarbeit', 'Englschalkinger Straße 12', NULL, '81925', 'DE', 'München', NULL, 'bayerischelandeszent@example.com'),
  ('Bayerisches Staatsministerium für Familie, Arbeit und Soziales', 'Winzererstr. 9', NULL, '80797', 'DE', 'München', NULL, 'bayerischesstaatsmin@example.com'),
  ('Bela Living GmbH', 'Wallstraße 9-13', NULL, '10179', 'DE', 'Berlin', '+4915566636411', 'service@bela-living.de'),
  ('Benediktuspark Am Stift GmbH', 'Stiftsplatz 2a', NULL, '37176', 'DE', 'Nörten-Hardenberg', '+49 (0) 5503 8085-0', 'noerten@auvictum.de'),
  ('Bertling Kazakh Logistics LLP', 'Building #9, Admiral Lev Vladimirsky street', NULL, 'E02A4H5', 'KZ', 'Atyrau', '+7 7122 763171/73/74/75', 'aigul.utepova@bertling.com'),
  ('Berylls Strategy Advisors GmbH', 'Maximilianstraße 34', NULL, '80539', 'DE', 'München', NULL, 'beryllsstrategyadvis@example.com'),
  ('Big Potato Limited', '1 Holywell Lane London', NULL, 'EC2A 3ET', 'UK', 'London', NULL, 'bigpotatolimited@example.com'),
  ('Blanke Briefhüllen GmbH', 'Allee 40', NULL, '74072', 'DE', 'Heilbronn', '07131 3899-500', 'info@brief-huellen.de'),
  ('Bosse Gartenbaubedarf e.K.', 'Gartenstr. 28', NULL, '75446', 'DE', 'Wiernsheim', NULL, 'bosse.mail@t-online.de'),
  ('Broszeit GmbH', 'Am Föhrenried 7', NULL, '88255', 'DE', 'Baindt-Schachen', NULL, 'broszeitgmbh@example.com'),
  ('Buchele Raumgestaltung GmbH', 'St.-Pauli Straße 10', NULL, '80336', 'DE', 'München', NULL, 'info@buchele-raumgestaltung.de'),
  ('Burak-Supermarkt GmbH', 'Eintrachtstr. 16', NULL, '81541', 'DE', 'München', NULL, 'buraksupermarktgmbh@example.com'),
  ('Burkart Dörrobst AG', 'Rüstenschwil 38', NULL, '5644', 'CH', 'Auw', NULL, 'burkartdrrobstag@example.com'),
  ('BÜNDNIS 90 / DIE GRÜNEN', 'Sendlinger Str. 47', NULL, '80331', 'DE', 'München', NULL, 'bndnis90diegrnen@example.com'),
  ('Bürkle Leisten & Profile GmbH', 'Siemensstraße 30', NULL, '67227', 'DE', 'Frankenthal (Pfalz)', NULL, 'brkleleistenprofileg@example.com'),
  ('C.E. Noerpel GmbH Zweigniederlassung Heidenheim', 'Wilhelm-Kentner-Str. 1', NULL, '89520', 'DE', 'Heidenheim an der Brenz', '+49 7314 0050', 'info@noerpel.de'),
  ('CAMP RAMPS', 'Wiesenstrasse 3', NULL, '52222', 'DE', 'Stolberg', NULL, 'campramps@example.com'),
  ('CAPRICE Schuhproduktion GmbH & Co. KG', 'Blocksbergstraße', NULL, '66955', 'DE', 'Pirmasens', '+49 (0) 63 31 / 27 33-0', 'ralf.koch@caprice.de'),
  ('CARGOBIZ MAGDALENA GO?AB', 'Nied?wiady 16/4', NULL, '62-800', 'PL', 'Kalisz', NULL, 'cargobizmagdalenagoa@example.com'),
  ('CBTS', 'Sulzbacher Straße 10', NULL, '71522', 'DE', 'Backnang', '+49(0) 7191 899 26 26', 'info@c-b-t-s.de'),
  ('CFG Hocholdinger INRES', 'Friedrich-Ebert-Allee 144', NULL, '53113', 'DE', 'Bonn', NULL, 'cfghocholdingerinres@example.com'),
  ('CHECK24 Vergleichsportal Möbel GmbH', 'Wallstr. 9-13', NULL, '10179', 'DE', 'Berlin', NULL, 'check24vergleichspor@example.com'),
  ('CHORAL GmbH', 'Machabäerstraße 28', NULL, '50668', 'DE', 'Köln', NULL, 'choralgmbh@example.com'),
  ('CHS Container Handel GmbH', 'Tillmannstraße 19', NULL, '28239', 'DE', 'Bremen', NULL, 'chscontainerhandelgm@example.com'),
  ('CLG - Consolidation & Logistics GmbH', 'Rossweg 20 - Gebäude C', NULL, '20457', 'DE', 'Hamburg', NULL, 'clgconsolidationlogi@example.com'),
  ('CLS Rimer', 'Bradley Str. 16', NULL, '89231', 'DE', 'Neu-Ulm', NULL, 'clsrimer@example.com'),
  ('COSRAU GmbH', 'Königstr. 22', NULL, '83022', 'DE', 'Rosenheim', '+49 8031 31029', 'info@cosrau.com'),
  ('CPI Vertex Antennentechnik GmbH', 'Baumstraße 50', NULL, '47198', 'DE', 'Duisburg', NULL, 'cpivertexantennentec@example.com'),
  ('CRAs Ausbau- & Montageservice', 'Schmiedestraße 14A', NULL, '14554', 'DE', 'Seddiner See', NULL, 'crasausbaumontageser@example.com'),
  ('CS Transitarios, LDA', 'Rua Dr. Joaquim Manuel da Costa 1086, 1o Esquerdo Sala 8', NULL, '4420-437', 'PT', 'Valbom - Gondomar', '+351 963 934 217', 'trafego@cstransitarios.pt'),
  ('CURT HENNE GmbH & Co.KG', 'Franz-Stickan-Straße 1', NULL, '28197', 'DE', 'Bremen', NULL, 'curthennegmbhcokg@example.com'),
  ('Cani Grup', 'Yalinayak Mah. Soda Bekire Caddesi Kapi No: 105', NULL, '33020', 'TR', 'Toroslar / Mersin', '+90 324 235 22 00', 'info@canigrup.com'),
  ('Caradvance', 'Kistlerhofstraße 170', NULL, '81379', 'DE', 'München', NULL, 'caradvance@example.com'),
  ('CargoCrew International GmbH', 'Poppenbütteler Bogen 39 (Haus B)', NULL, '22399', 'DE', 'Hamburg', '+49 (0)40 524 79 84 – 30', 'info@cargocrewInternational.de'),
  ('Cargosteer So. z.o.o.', 'ul.Slaska 17', NULL, '81-319', 'PL', 'Gdynia', NULL, 'cargosteersozoo@example.com'),
  ('Casa Fortunata GmbH', 'Maximiliansplatz 12', NULL, '80333', 'DE', 'München', NULL, 'casafortunatagmbh@example.com'),
  ('Cleansteel GmbH', 'Hutschenreutherstraße 4', NULL, '92637', 'DE', 'Weiden in der Oberpfalz', NULL, 'jan.filander@cleansteel.de'),
  ('Coach Stores Ltd t/a Coach, Stuart Weitzmann & Kate Spade', 'Seventh Floor Brunel Building 2 Canalside Walk', NULL, 'W2 1DG', 'UK', 'London', NULL, 'coachstoresltdtacoac@example.com'),
  ('Colt International GmbH', 'Max-Planck-Straße 5', NULL, '89340', 'DE', 'München', NULL, 'coltinternationalgmb@example.com'),
  ('Comarch AG', 'Riesstraße 16', NULL, '80992', 'DE', 'Munich', NULL, 'rechnungen-caag@comarch.de'),
  ('Comgistics GmbH', 'Rothenbaumchaussee 40', NULL, '20148', 'DE', 'Hamburg', NULL, 'comgisticsgmbh@example.com'),
  ('Compass Europe s. r. o.', 'Poľná 4', NULL, '903 01', 'SK', 'Senec', '+421 911 903 955', 'hricovec@compasspools.eu'),
  ('Compass Pools Deutschland GmbH', 'Am Lehmhügel 7', NULL, '94530', 'DE', 'Auerbach', '+49 (0)9901 90307 0', 'info@compasspools.de'),
  ('Concorde Home Entertainment GmbH', 'Luise-Ullrich-Straße 6', NULL, '82031', 'DE', 'Grünwald', NULL, 'concordehomeentertai@example.com'),
  ('Condrobs e.V.', 'Berg-am-Laim-Straße 47', NULL, '81673', 'DE', 'München', NULL, 'condrobsev@example.com'),
  ('Confiserie Marie Louise GmbH', 'Wittestrasse 26e', NULL, '13509', 'DE', 'Berlin', NULL, 'confiseriemarielouis@example.com'),
  ('Consors Finanz BNP Paribas S.A. Niederlassung Deutschland', 'Schwanthalerstraße 31', NULL, '80336', 'DE', 'München', NULL, 'consorsfinanzbnppari@example.com'),
  ('Constantia Pirk GmbH & Co. KG', 'Pirkmühle 14-16', NULL, '92712', 'DE', 'Pirk', '+49 961 87 0', 'office.pirk@cflex.com'),
  ('Constantin Film Produktion GmbH', 'Feilitzschstraße 6', NULL, '80802', 'DE', 'München', NULL, 'constantinfilmproduk@example.com'),
  ('Continental Building Services GmbH', 'Martinskirchweg 18', NULL, '67346', 'DE', 'Speyer', NULL, 'continentalbuildings@example.com'),
  ('Copyright Promotions Licensing Group GmbH', 'Thalkirchner Straße 2', NULL, '80337', 'DE', 'Munich', NULL, 'copyrightpromotionsl@example.com'),
  ('Crosspolimeri AG Schweiz', 'Hauptstrasse 300', NULL, '5064', 'CH', 'Wittenau', NULL, 'crosspolimeriagschwe@example.com'),
  ('Czarnecki Artur', 'Baakenallee 8', NULL, '20457', 'DE', 'Hamburg', NULL, 'Artur.Czarnecki@rwe.com'),
  ('DB Netz AG', 'Elisabeth-Schwarzhaupt-Platz 1', NULL, '10115', 'DE', 'Berlin', NULL, 'dbnetzag@example.com'),
  ('DESA Construction GmbH', 'Grafenberger Allee 277-287', NULL, '40237', 'DE', 'Düsseldorf', NULL, 'desaconstructiongmbh@example.com'),
  ('DFB EURO GmbH', 'Otto-Fleck-Schneise 6', NULL, '60528', 'DE', 'Frankfurt am Main', NULL, 'dfbeurogmbh@example.com'),
  ('DHL Freight GMbH', 'Postfach 20 03 62', NULL, '53133', 'DE', 'Bonn', NULL, 'dhlfreightgmbh@example.com'),
  ('DHL Global Forwarding (UK) Limited', 'Eastworth House, Eastworth Road,', NULL, 'KT16 8SH', 'UK', 'Chertsey, Surrey.', NULL, 'dhlglobalforwardingu@example.com'),
  ('DHL Global Forwarding GmbH', 'Flughafenallee 11', NULL, '28199', 'DE', 'Bremen', NULL, 'dhlglobalforwardingg@example.com'),
  ('DLS Land und Seespeditionsgesellschaft mbH', 'Jacorbsrade 1', NULL, '22962', 'DE', 'Siek', NULL, 'dlslandundseespediti@example.com'),
  ('DOK Kindersuesswaren GmbH', 'Aspastraße 24', NULL, '59394', 'DE', 'Nordkirchen', NULL, 'dokkindersuesswareng@example.com'),
  ('DREWS Fuhrgeschäft', 'Buchholzstr. 59', NULL, '49377', 'DE', 'Vechta', NULL, 'drewsfuhrgeschft@example.com'),
  ('DSS 24 UG', 'Ludwig-Erhard-Str. 11', NULL, '85375', 'DE', 'Neufahrn', NULL, 'dss24ug@example.com'),
  ('DTL Ulus. Tas. ve Loj. Hiz. Dis Tic. Ltd. Sti.', 'UNIVERSITE MAH. KAMP SK. İLCAN SITESI NO:1 KAPI NO: 6', NULL, NULL, 'TR', 'Istanbul', NULL, 'dtlulustasvelojhizdi@example.com'),
  ('DYCKHOFF GmbH', 'Hauenhorster Straße 131', NULL, '48431', 'DE', 'Rheine', NULL, 'f.viets@dyckhoff24.de'),
  ('DYWIDAG Sp. z o.o.', 'ul. Gen. Hallera 78', NULL, '41-709', 'PL', 'Ruda Śląska', NULL, 'Witold.Kierczak@dywidag.com');