-- Part 5/5
-- Customers 549 to 681 (133 total)

INSERT INTO customers (name, street, street2, zip, country, city, phone, email) VALUES
  ('Senic GmbH', 'Pfuelstraße 5', NULL, '10997', 'DE', 'Berlin', NULL, 'senicgmbh@example.com'),
  ('Seniorenresidenz Fortweg GmbH', 'Fortweg 3', NULL, '35415', 'DE', 'Pohlheim', '+49 (0) 6403/9797-510', 'seniorenresidenzfort@example.com'),
  ('Seniorenresidenz zur Weißen Dame GmbH', 'An der Weißen Dame 5', NULL, '48599', 'DE', 'Gronau', NULL, 'seniorenresidenzzurw@example.com'),
  ('Seniorenzentrum Brakel GmbH', 'Lütkerlinde 21', NULL, '33034', 'DE', 'Brakel', '+49 (0) 2924/802-445', 'seniorenzentrumbrake@example.com'),
  ('Seniorenzentrum Cäcilienhof Garbsen GmbH', 'Bruno-Rappel-Weg 1', NULL, '30827', 'DE', 'Garbsen', NULL, 'seniorenzentrumccili@example.com'),
  ('Seniorenzentrum Haus Kettwig GmbH', 'Akademiestr. 2', NULL, '45219', 'DE', 'Essen', '02054-9320', 'info@haus-kettwig.de'),
  ('Seniorenzentrum Nidda GmbH', 'Kurstraße 28', NULL, '63667', 'DE', 'Nidda - Bad Salzhausen', NULL, 'seniorenzentrumnidda@example.com'),
  ('Seniorenzentrum Sophienhof GmbH', 'Hauptstraße 61', NULL, '32457', 'DE', 'Porta Westfalica', NULL, 'seniorenzentrumsophi@example.com'),
  ('Seven.One AdFactory GmbH', 'Medienallee 4', NULL, '85774', 'DE', 'Unterföhring', NULL, 'sevenoneadfactorygmb@example.com'),
  ('Shoepassion GmbH', 'Wolfener Str. 32/34', NULL, '12681', 'DE', 'Berlin', NULL, 'shoepassiongmbh@example.com'),
  ('ShopLine Ladenbau GmbH', 'Im Taubental 9-11', NULL, '41468', 'DE', 'Neuss', NULL, 'shoplineladenbaugmbh@example.com'),
  ('Simon Hegele Gesellschaft für Logistik & Service mbH', 'Standort Raunheim', NULL, '76095', 'DE', 'Karlsruhe', NULL, 'simonhegelegesellsch@example.com'),
  ('SkyTechSport Club Foundation', 'Riesenfeldstrasse 18', NULL, '80809', 'DE', 'München', NULL, 'skytechsportclubfoun@example.com'),
  ('Smilike GmbH', 'Dr.-Ulrich-Weg 1', NULL, '85435', 'DE', 'Erding', NULL, 'smilikegmbh@example.com'),
  ('Social Ninja GmbH', 'Weidenweg 52', NULL, '10247', 'DE', 'Berlin', NULL, 'socialninjagmbh@example.com'),
  ('Solida Holz GmbH', 'Teichweg 5', NULL, '35396', 'DE', 'Gießen', '+49 (0) 641 984437', 'solidaholzgmbh@example.com'),
  ('Sommer International Retailservice GmbH', 'Wierlings Esch 35', NULL, '48249', 'DE', 'Dülmen', NULL, 'sommerinternationalr@example.com'),
  ('Sonderbetriebsvermögen Jürgen Schmid', 'Birkenleiten 41', NULL, '81543', 'DE', 'München', NULL, 'sonderbetriebsvermge@example.com'),
  ('Sondermann Profile GmbH', 'Bergstraße 2', NULL, '57489', 'DE', 'Drolshagen', '+49 2761 / 83 93 - 771', 'export@sondro.de'),
  ('Sono Motors GmbH', 'Waldmeisterstraße 76', NULL, '80935', 'DE', 'München', NULL, 'sonomotorsgmbh@example.com'),
  ('Soraya Rahmati', 'Johannes-Timm-Str. 11', NULL, '81373', 'DE', 'München', NULL, 'sorayarahmati@example.com'),
  ('Space-Eye e. V.', 'Wiener Str. 14', NULL, '93055', 'DE', 'Regensburg', NULL, 'kontakt@space-eye.org'),
  ('Spectra GmbH', 'Lorenzstraße 11', NULL, '76297', 'DE', 'Stutensee', 'Tel: +49 (0) 7244 20 50 30 0', 'spectragmbh@example.com'),
  ('Spedition Bohnet GmbH', 'Erolzheimer Straße 1', NULL, '88457', 'DE', 'Kirchdorf an der Iller', NULL, 'speditionbohnetgmbh@example.com'),
  ('Spezialitäten Restaurant Makassar GmbH', 'Geyerstrasse 52', NULL, '80469', 'DE', 'München', NULL, 'spezialittenrestaura@example.com'),
  ('Spinner Werkzeugmaschinenfabrik GmbH', 'Rudolf-Diesel-Ring 24', NULL, '82054', 'DE', 'Sauerlach', NULL, 'spinnerwerkzeugmasch@example.com'),
  ('Spokebase GmbH', 'Rosenthalerstr. 13', NULL, '10119', 'DE', 'Berlin', NULL, 'spokebasegmbh@example.com'),
  ('Sport Hauser Kaibling - Frühwirth Outlet GmbH', 'Innstraße 3', NULL, '6063', 'AT', 'Rum', '+43 368620044', 'office@sport-hauser-kaibling.com'),
  ('Stappenbacher Putz- und Maler GmbH', 'Conrad-Vetter-Straße 52, Trossenfurt', NULL, '97514', 'DE', 'Oberaurach', NULL, 'stappenbacherputzund@example.com'),
  ('Stefan Altmeier', 'Waldshuterstr. 21', NULL, '79805', 'DE', 'Eggingen', NULL, 'stefanaltmeier@example.com'),
  ('Stiftung Insel Hombroich', 'Raketenstation Hombroich 4', NULL, '41472', 'DE', 'Neuss', '+49 2182 887-4003', 'klinkhamer@inselhombroich.de'),
  ('Streifeneder Ortho. Production GmbH', 'Moosfeldstr. 10', NULL, '82275', 'DE', 'Emmering', NULL, 'empfang@streifeneder.de'),
  ('Studio Westend', 'Gollierstraße 78', NULL, '80339', 'DE', 'München', NULL, 'info@studio-westend.com'),
  ('Städtische Galerie im Lenbachhaus und Kunstbau München', 'Luisenstraße 33', NULL, '80333', 'DE', 'München', NULL, 'stdtischegalerieimle@example.com'),
  ('Städtische Rainer-Werner-Fassbinder-Fachoberschule für Sozialwesen', 'Schlierseestraße 47', NULL, '81539', 'DE', 'Munich', NULL, 'stdtischerainerwerne@example.com'),
  ('Suso Transporte y Logistica Internacional, S.L.', 'C/ Landatxu, 2 - Parcela C-2', NULL, '48160', 'ES', 'Derio ( Bizkaia )', NULL, 'susotransporteylogis@example.com'),
  ('TECNICAS REUNIDAS S.A.', 'Arapiles 13, 11th floor', NULL, '28015', 'ES', 'Madrid', NULL, 'tecnicasreunidassa@example.com'),
  ('TGP Azerbaijan MMC', 'VOEN: 1406601881   Marine Plaza Premium Offices', 'Uzeyir Hajibeyli Str. 62', 'AZ1010', 'AZ', 'Baku', NULL, 'tgpazerbaijanmmc@example.com'),
  ('TOOL-TEMP AG', 'Industriestrasse 30', NULL, '8583', 'CH', 'Sulgen', NULL, 'tooltempag@example.com'),
  ('TOP SWEETS GMBH', 'Aspastraße 24', NULL, '59394', 'DE', 'Nordkirchen', NULL, 'topsweetsgmbh@example.com'),
  ('TPS Rental Systems GmbH & Co.KG', 'Hollefeldstraße 24 - 24A', NULL, '48282', 'DE', 'Emsdetten', NULL, 'rh@tpsrentalsystems.de'),
  ('TRW Thüringer Reinigungs- und Waschmittelprodukte GmbH', 'Markt 33', NULL, '4600', 'DE', 'Altenburg', NULL, 'trwthringerreinigung@example.com'),
  ('TRiooo Building Systems GmbH', 'Ziegelbreite 8', NULL, '84166', 'DE', 'Adlkofen', NULL, 'triooobuildingsystem@example.com'),
  ('Tec-quipment GmbH', 'Kronacher Str. 1 B', NULL, '96364', 'DE', 'Marktrodach', NULL, 'tecquipmentgmbh@example.com'),
  ('Technische Universität München', 'Arcisstraße 21', NULL, '80333', 'DE', 'München', NULL, 'technischeuniversitt@example.com'),
  ('Teppich Comfort GmbH', 'Kleine Stuebenstr. 11', NULL, '45139', 'DE', 'Essen', NULL, 'teppichcomfortgmbh@example.com'),
  ('Terrawerk', 'Jennerstr. 3a', NULL, '80999', 'DE', 'München', NULL, 'terrawerk@example.com'),
  ('Textilmacher GmbH', 'Lindberghstrasse 7', NULL, '80939', 'DE', 'München', NULL, 'textilmachergmbh@example.com'),
  ('Theurl Leimholzbau GmbH', 'Thal-Wilfern 35', NULL, '9911', 'AT', 'Assling', NULL, 'theurlleimholzbaugmb@example.com'),
  ('Timm & Wilken OHG', 'Hauptstraße 11', NULL, '22869', 'DE', 'Schenefeld', NULL, 'timmwilkenohg@example.com'),
  ('Trane Klima- und Kältetechnisches Büro GmbH', 'Pionierstrasse 3', NULL, '82152', 'DE', 'Krailling', NULL, 'traneklimaundkltetec@example.com'),
  ('Trans Global Projects GmbH', 'Diepenau 2', NULL, '28195', 'DE', 'Bremen', NULL, 'transglobalprojectsg@example.com'),
  ('Trans Global Projects LLC', 'U. Hajibeyli str. 62', NULL, 'AZ-1010', 'AZ', 'Baku', NULL, 'transglobalprojectsl@example.com'),
  ('Trans Global Projects Ltd', '1-7 Commercial Road, Paddock Wood', NULL, 'TN12 6EN', 'UK', 'Kent', '+44 1732 744 400', 'cwardale@tglobal.com'),
  ('Trans Global Projects Ltd 10166', 'Willow House, Newhouse Business Park, Newhouse Road,', NULL, 'FK3 8LL', 'UK', 'Grangemouth', NULL, 'cwardale@tglobal.com'),
  ('Transport-Service / Stroh-und Heuspedition', 'Berlinerstraße 111', NULL, '2943', 'DE', 'Weißwasser', NULL, 'transportservicestro@example.com'),
  ('Trinkwassersysteme Bauer', 'Unterfeldring 4', NULL, '85256', 'DE', 'Vierkirchen', '08139/802101', 'info@trinkwassersysteme-bauer.de'),
  ('Tunguska Transport- und Logistik GmbH', 'An den Gärten 7', NULL, '51491', 'DE', 'Overath', NULL, 'tunguskatransportund@example.com'),
  ('Tur Transit GmbH', 'Bischofstraße 94', NULL, '47809', 'DE', 'Krefeld', NULL, 'turtransitgmbh@example.com'),
  ('Turk Transport Worldwide Freight Services', 'Unit A11, Bell Lane Office Village, Bell Lane, Little Chalfont, Amersham', NULL, 'HP6 6FA', 'UK', 'Buckinghamshire', NULL, 'turktransportworldwi@example.com'),
  ('TÜV SÜD Industrie Service GmbH', 'Westendstraße 199', NULL, '80686', 'DE', 'München', NULL, 'tvsdindustrieservice@example.com'),
  ('Türkisch-Islamische Gemeinde e.V', 'Manisastraße 1', 'Ditib-Moschee-Ingolstadt', '85057', 'DE', 'Ingolstadt', NULL, 'guerkanbahce@gmail.com'),
  ('UAB Jumbo Transport', 'Graiciuno 38', NULL, '2241', 'LT', 'Vilnius', NULL, 'uabjumbotransport@example.com'),
  ('USC Mainz', 'Dalheimer Weg 2', NULL, '55128', 'DE', 'Mainz', NULL, 'uscmainz@example.com'),
  ('UTE TR FADHILI PROJECT', 'C/Maria de Portugal 9-11', NULL, '28050', 'ES', 'Madrid', NULL, 'utetrfadhiliproject@example.com'),
  ('VGG Handels AG', 'August-Thyssen-Str. 8', NULL, '41564', 'DE', 'Kaarst', NULL, 'vgghandelsag@example.com'),
  ('VGL SP. Z O.O.', 'ul. Spokojna 22', NULL, '81-549', 'PL', 'Gdynia', NULL, 'vglspzoo@example.com'),
  ('Vanclaes BV', 'Gnephoek 18', NULL, '2401LP', 'NL', 'Alphen aan den Rijn', NULL, 'vanclaesbv@example.com'),
  ('Verein Kollekitivs E.V. München', 'Rupprechtstrasse 29', NULL, '80636', 'DE', 'München', NULL, 'vereinkollekitivsevm@example.com'),
  ('Vestner Aufzüge GmbH', 'Humboldtstr. 10', NULL, '85609', 'DE', 'Dornach', '+49 3 20 88-0', 'info@vestner.de'),
  ('Viki-Gabi EOOD', 'zh.k. Druzhba, bl. 134 et. 1, ap. 2', NULL, '5800', 'BG', 'Pleven', NULL, 'vikigabieood@example.com'),
  ('Voipango EOD European Online Distribution GmbH', 'Bötzinger Strasse 31', NULL, '79111', 'DE', 'Freiburg', NULL, 'voipangoeodeuropeano@example.com'),
  ('WAGU Gummitechnik GmbH', 'Friedrich-Harkort-Str. 17', NULL, '59581', 'DE', 'Warstein', '+ 49 2902-9739-0', 'info@wagu-rubber.com'),
  ('WAREMA Renkhoff SE', 'Hymerring 6', NULL, '97877', 'DE', 'Wertheim', NULL, 'waremarenkhoffse@example.com'),
  ('WISAG Gebäudetechnik Bayern GmbH & Co. KG', 'Inselkammerstraße 4', NULL, '82008', 'DE', 'Unterhaching', NULL, 'wisaggebudetechnikba@example.com'),
  ('Wahl GmbH & Co. KG Spedition und Logistik', 'Gildemeisterstraße 150', NULL, '33689', 'DE', 'Bielefeld', NULL, 'wahlgmbhcokgspeditio@example.com'),
  ('Waräger GmbH', 'Kaiserstraße 137', NULL, '72764', 'DE', 'Reutlingen', NULL, 'wargergmbh@example.com'),
  ('WaterBeck GmbH', 'Reichardstraße 18', NULL, '31789', 'DE', 'Hameln', '+49 (0) 800 000 8403', 'info@waterbeck-gmbh.de'),
  ('Weldex Euro GmbH', 'Gewerbering 3A', NULL, '82140', 'DE', 'Olching', NULL, 'weldexeurogmbh@example.com'),
  ('Welmaet Handels GmbH', 'Ramsauerstrasse 11', NULL, '81379', 'DE', 'München', NULL, 'welmaethandelsgmbh@example.com'),
  ('Wenzel Marine GmbH & Co. KG', 'Rodendamm 25', NULL, '28816', 'DE', 'Stuhr', '+49  421 959250', 'mail@wenzelmarine.com'),
  ('Wermil Handels GmbH', 'Schäftlarnstr. 10', NULL, '81371', 'DE', 'München', NULL, 'wermilhandelsgmbh@example.com'),
  ('Werner Graf Holding GmbH', 'Gymnasiumstraße 67', NULL, '1190', 'AT', 'Vienna', NULL, 'wernergrafholdinggmb@example.com'),
  ('Weserra GmbH', 'Hermann-Oberth-Straße 9', NULL, '85640', 'DE', 'Putzbrunn', NULL, 'benau1@web.de'),
  ('Westfälische Handels GmbH', 'Niedersachsenweg 6', NULL, '44143', 'DE', 'Dortmund', NULL, 'isa.ozlemis@gmail.com'),
  ('Wever & Ducre GmbH', 'Riederstraße 1', NULL, '85229', 'DE', 'Markt Indersdorf', NULL, 'weverducregmbh@example.com'),
  ('Wever & Ducré BV', 'Spinnerijstraat 99/21', NULL, '8500', 'BE', 'Kortrijk', NULL, 'invoices@weverducre.com'),
  ('Wild Brain CPLG', 'Thalkirchner Straße 2', NULL, '80337', 'DE', 'Munich', '49 89 541999208', 'wildbraincplg@example.com'),
  ('Wild-Berghof Buchet - Thomas Gstettenbauer', 'Buchet 2', NULL, '94505', 'DE', 'Bernried-Buchet', '09905 - 248', 'info@wildberghof-buchet.de'),
  ('Wilhelm Kentner Kraftwagen-Spedition GmbH & Co. KG', 'Wilhelm-Kentner-Str. 1', NULL, '89520', 'DE', 'Heidenheim', NULL, 'wilhelmkentnerkraftw@example.com'),
  ('Wissenschaftliche Elektronik GmbH', 'Am Eichberg 5', NULL, '66440', 'DE', 'Blieskastel', NULL, 'info@wissel.eu'),
  ('Wittmann Battenfeld Deutschland GmbH', 'Werner-Battenfeld-Str. 1', NULL, '58540', 'DE', 'Meinerzhagen', NULL, 'wittmannbattenfeldde@example.com'),
  ('Wohnmoderne OHG', 'Klenzestraße 59', NULL, '80469', 'DE', 'München', NULL, 'wohnmoderneohg@example.com'),
  ('Wohnungs- und Siedlungsbau Bayern GmbH & Co. oHG', 'Hansastrasse 27f', NULL, '81373', 'DE', 'München', NULL, 'wohnungsundsiedlungs@example.com'),
  ('World of Less - Logistic Trading GmbH', 'Am Lenghardt 11', NULL, '84174', 'DE', 'Eching', '08709 / 943 298-0', 'anfrage@world-of-less.de'),
  ('Worldplast Sp. z o.o.', 'Irysowa 9', NULL, '55-040', 'PL', 'Bielany Wroc?awskie', NULL, 'worldplastspzoo@example.com'),
  ('Worldplast Sp. z o.o. 10457', 'Irysowa 9', NULL, '55-040', 'PL', 'Bielany Wroc?awskie', NULL, 'worldplastspzoo10457@example.com'),
  ('XAL GmbH', 'Riederstraße 1', NULL, '85229', 'DE', 'Markt Indersdorf', '+49 89 32373830', 'LV.DE@xal.com'),
  ('YCCP GmbH', 'Römerstraße 14', NULL, '80801', 'DE', 'München', NULL, 'yccpgmbh@example.com'),
  ('Z GLOBAL LOGISTICS S.R.L.', 'Sat Bascov, Comuna Bascov , Strada Pinilor nr 12, Camera C4', NULL, NULL, 'RO', 'Judet Arge?', NULL, 'zgloballogisticssrl@example.com'),
  ('ZEISST GmbH', 'Hofbrunnstrasse 45c', NULL, '81479', 'DE', 'München', NULL, 'zeisstgmbh@example.com'),
  ('Zambelli Dach + Fassadentechnik GmbH', 'Hans-Sachs-Straße 3+5', NULL, '94569', 'DE', 'Stephansposching', NULL, 'zambellidachfassaden@example.com'),
  ('Zambelli RIB-ROOF GmbH & Co. KG', 'Hans-Sachs-Straße 3+5', NULL, '94569', 'DE', 'Stephansposching', NULL, 'Juergen.Renner@zambelli.com'),
  ('Zeman & Co GmbH', 'Clemens-Holzmeister-Straße 6', NULL, '1100', 'AT', 'Wien', NULL, 'zemancogmbh@example.com'),
  ('acargo GmbH', 'Ellerholzdamm 9', NULL, '20457', 'DE', 'Hamburg', NULL, 'acargogmbh@example.com'),
  ('adamicus GmbH', 'Blumenstrasse 28', NULL, '80331', 'DE', 'München', NULL, 'adamicusgmbh@example.com'),
  ('albertZWEI media GmbH', 'Oettingenstraße 25', NULL, '80538', 'DE', 'München', NULL, 'albertzweimediagmbh@example.com'),
  ('aqua-vogt.de Gmbh', 'Fichtenweg 10', NULL, '75449', 'DE', 'Wurmberg', '07044-909786', 'info@aqua-vogt.de'),
  ('bernhard rüsing gmbh + co. kg', 'Mittelstrasse 5', NULL, '41469', 'DE', 'Neuss', NULL, 'bernhardrsinggmbhcok@example.com'),
  ('bikmed -Bildungsinstitut für Kompetenz in der Medizin GmbH', 'Wilhelm-Hale-Straße 46 B', NULL, '80639', 'DE', 'München', NULL, 'bikmedbildungsinstit@example.com'),
  ('boschen & oetting Automatisierungs-Bau GmbH', 'Wohlrabedamm 11', NULL, '13629', 'DE', 'Berlin', NULL, 'boschenoettingautoma@example.com'),
  ('e+p films GmbH', 'Heßstr. 48b', NULL, '80798', 'DE', 'München', NULL, 'epfilmsgmbh@example.com'),
  ('eVehicle for you GmbH', 'Maria-Theresia-Straße 1a', NULL, '81675', 'DE', 'München', NULL, 'evehicleforyougmbh@example.com'),
  ('german paper solutions GmbH & Co. KG', 'Wupperstr. 38', 'L. Nr. 8609', '58332', 'DE', 'Schwelm', NULL, 'info@erfurtspezialpapiere.com'),
  ('gül koc GmbH interior design + construction services', 'Reichenbachstraße 35', NULL, '80469', 'DE', 'München', NULL, 'glkocgmbhinteriordes@example.com'),
  ('i-log logistics solutions GmbH', 'Industriezeile 1, Objekt 5', NULL, '8401', 'AT', 'Kalsdorf', NULL, 'iloglogisticssolutio@example.com'),
  ('innovIT AG', 'Schloss Heiligenberg', NULL, '64342', 'DE', 'Seeheim-Jugenheim', NULL, 'innovitag@example.com'),
  ('inside', 'Wienerbergstrasse 11', NULL, '1100', 'AT', 'Wien', NULL, 'inside@example.com'),
  ('kg-pharma AB', 'Björnholmsvägen 4', NULL, '184 92', 'SE', 'Åkersberga/Stockholm län', NULL, 'kgpharmaab@example.com'),
  ('kg-pharma GmbH & Co. KG', 'Pestalozzistr. 25', NULL, '22305', 'DE', 'Hamburg', NULL, 'kgpharmagmbhcokg@example.com'),
  ('klarx GmbH', 'Koppstraße 16', NULL, '81379', 'DE', 'München', NULL, 'info@klarx.com'),
  ('koziol »ideas for friends GmbH', 'Werner-von-Siemens-Straße 90', NULL, '64711', 'DE', 'Erbach / Odenwald', '+49 6062 6040', 'info@koziol.de'),
  ('matten-zuschnitt.de', 'Gottlieb-Daimler-Str. 14', NULL, '68165', 'DE', 'Mannheim', NULL, 'mattenzuschnittde@example.com'),
  ('mefro Metallwarenfabrik Fischbacher GmbH', 'Ludwig-Thoma-Straße 29', NULL, '83101', 'DE', 'Rohrdorf', NULL, 'mefrometallwarenfabr@example.com'),
  ('mundotec GmbH', 'Hannöversche Straße 20A', NULL, '44143', 'DE', 'Dortmund', NULL, 'umran.coskun@mundotec.de'),
  ('qqq team', 'Fraunhoferstraße 5', NULL, '80469', 'DE', 'Munich', NULL, 'team@yarres-logistics.com'),
  ('re-fer GmbH', 'Neuenburger Straße 37', NULL, '79379', 'DE', 'Müllheim', NULL, 'refergmbh@example.com'),
  ('roko project & consulting GmbH', 'Sudetenstraße 2', NULL, '92259', 'DE', 'Neukirchen bei Sulzbach-Rosenberg', NULL, 'rokoprojectconsultin@example.com'),
  ('steintex GmbH', 'Industriestr. 12-16', NULL, '42929', 'DE', 'Wermelskirchen', NULL, 'hetze@steintex.de'),
  ('stela Laxhuber GmbH', 'Laxhuberplatz 1', NULL, '84323', 'DE', 'Massing', NULL, 'stelalaxhubergmbh@example.com'),
  ('transmaritim international GmbH', 'Willy-Brandt-Straße 23-25', NULL, '20457', 'DE', 'Hamburg', NULL, 'transmaritiminternat@example.com'),
  ('wisefood GmbH', 'Dieselstr. 28', NULL, '85748', 'DE', 'Garching bei München', NULL, 'wisefoodgmbh@example.com'),
  ('Ötztal Tourismus Congress GmbH', 'Gurglerstrasse 118', NULL, '6456', 'AT', 'Obergurgl', NULL, 'tztaltourismuscongre@example.com');